WITH
VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,max(inv.TOLERANCIA)as TOLERANCIA,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
     FROM XXER_AR_INVOICES_CONCILIACION_V inv
     where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen
     and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
     group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT),
        CB as (SELECT VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,VC.TOLERANCIA,AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM  VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT VE.NUMERO_DOCUMENTO,VE.REFERENCIA
		        ,LISTAGG(VE.FOLIO_PREIMPRESO, ',') WITHIN  GROUP (ORDER BY VE.FOLIO_PREIMPRESO) AS FOLIO_PREIMPRESOS
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VE
                WHERE TRUNC(VE.CORTE_FECHA_CREACION) BETWEEN (SELECT TRUNC(ADD_MONTHS(MAX(VC.FECHA),-1)) FROM VC) AND (SELECT TRUNC(MAX(VC.FECHA)+1) FROM VC)
                AND VE.TIPO_PAGO NOT IN('EFE','AMX') AND  TIPO_OPERACION NOT IN ('HO','FO')
                GROUP BY VE.NUMERO_DOCUMENTO,VE.REFERENCIA
                ),
        BVM AS(SELECT VM.NUMERO_DOCUMENTO,SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,LISTAGG(BR.FOLIO_PREIMPRESO, ',') WITHIN  GROUP (ORDER BY BR.FOLIO_PREIMPRESO) AS FOLIO_PREIMPRESOS 
		 FROM EXTRACCION_MISCELANEA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VM
		 INNER JOIN TMS_CORTES_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX CR
		 ON (CR.CORTE_ID = VM.CORTE_ID)
		 INNER JOIN TMS_BOLETOS_VENTA_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VT
		 ON (VT.FOLIO_PREIMPRESO = VM.NO_FOLIO 
		 AND TRUNC(VT.FECHA_CREACION) BETWEEN (SELECT TRUNC(ADD_MONTHS(MAX(VC.FECHA),-1)) FROM VC) AND (SELECT TRUNC(MAX(VC.FECHA)+1) FROM VC)
		 INNER JOIN TMS_BOLETOS_VENTA_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX BR ON BR.BOLETO_RELACIONADO_ID = VT.BOLETO_ID 
		 AND BR.TIPO_PAGO NOT IN ('EFE')
		 where 1=1 --AND SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1)='356087540'
		 and  TRUNC(VM.CORTE_FECHA_CREACION) BETWEEN (SELECT TRUNC(ADD_MONTHS(MAX(VC.FECHA),-1)) FROM VC) AND (SELECT TRUNC(MAX(VC.FECHA)+1) FROM VC)
		 GROUP BY VM.NUMERO_DOCUMENTO,SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1)
                ),          
                  TB AS (SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BV.NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID 
                       FROM CB INNER JOIN BV ON CB.REFERENCIA = BV.REFERENCIA
                       LEFT JOIN xxer_tbl_puente_header HD
                          ON  BV.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                       GROUP BY CB.AFILIACION,BV.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID
                         UNION ALL
                        SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVM.NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID
                          FROM CB INNER JOIN BVM ON CB.NO_OPERACION = BVM.REFERENCIA_PAGO
                          LEFT JOIN xxer_tbl_puente_header HD
                          ON  BVM.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                          GROUP BY CB.AFILIACION,BVM.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID
						  ),
						   BCT AS (SELECT CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.TOLERANCIA,AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO FROM CB GROUP BY CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.TOLERANCIA,AFILIACION,FECHA_DEPOSITO)
                          SELECT BCT.REFERENCE_PAYMENT,BCT.METODO_RECIBO,BCT.AFILIACION,BCT.FECHA_DEPOSITO,SUM(TB.IMPORTE) AS IMPORTE_TMS,BCT.IMPORTE AS IMPORTE_BANCO,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA,BCT.TOLERANCIA
                          ,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                          ,LISTAGG(NVL(TB.TABLA_PUENTE_ID,0), ',') WITHIN  GROUP (ORDER BY TB.TABLA_PUENTE_ID) AS TABLA_PUENTE_IDS
                          FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION        
                          GROUP BY BCT.FECHA_DEPOSITO,BCT.AFILIACION,BCT.IMPORTE,BCT.REFERENCE_PAYMENT,BCT.METODO_RECIBO,BCT.TOLERANCIA
						  ORDER BY DIFERENCIA ASC
						   
--QUERY CONSULTA 1
 WITH
	VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
		 FROM XXER_AR_INVOICES_CONCILIACION_V inv
		 where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen
		 and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
		 group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT)
		 SELECT VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO
					FROM VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')
					GROUP BY  VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,AFILIACION,FECHA_DEPOSITO;
--QUERY AJUSTE MISELANEAS TODOS LOS DATOS

	WITH
			CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
					FROM   TMS_COCILIACION_BANCOS_TBL where
					--TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND 
					USUARIO NOT IN('0670GGZM0')),
			BV AS(SELECT VE.NUMERO_DOCUMENTO,VE.REFERENCIA
					,LISTAGG(VE.FOLIO_PREIMPRESO, ',') WITHIN  GROUP (ORDER BY VE.FOLIO_PREIMPRESO) AS FOLIO_PREIMPRESOS
					FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VE
					WHERE TRUNC(VE.CORTE_FECHA_CREACION) BETWEEN (SELECT TRUNC(ADD_MONTHS(MIN(CB.FECHA_DEPOSITO),-1)) FROM CB) AND (SELECT TRUNC(MAX(CB.FECHA_DEPOSITO)+1) FROM CB)
					AND VE.TIPO_PAGO NOT IN('EFE','AMX') AND  TIPO_OPERACION NOT IN ('HO','FO')  --AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
					GROUP BY VE.NUMERO_DOCUMENTO,VE.REFERENCIA
					),
			BVM AS(
			 SELECT
	VM.NUMERO_DOCUMENTO,SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO))
	,1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO
	,LISTAGG(BR.FOLIO_PREIMPRESO, ',') WITHIN  GROUP (ORDER BY BR.FOLIO_PREIMPRESO) AS FOLIO_PREIMPRESOS
	FROM EXTRACCION_MISCELANEA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VM
	INNER JOIN TMS_CORTES_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX CR
	ON (CR.CORTE_ID = VM.CORTE_ID)
	INNER JOIN TMS_BOLETOS_VENTA_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VT
	ON (VT.FOLIO_PREIMPRESO = VM.NO_FOLIO
	AND TRUNC(VT.FECHA_CREACION) BETWEEN (SELECT TRUNC(ADD_MONTHS(MIN(CB.FECHA_DEPOSITO),-1)) FROM CB) AND (SELECT TRUNC(MAX(CB.FECHA_DEPOSITO)+1) FROM CB)
	--AND VT.TIPO_TRANSACCION = 'L'
	--AND VT.TIPO_PAGO IN ('BBV','BAB')
	)
	INNER JOIN TMS_BOLETOS_VENTA_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX BR
	ON BR.BOLETO_RELACIONADO_ID = VT.BOLETO_ID AND BR.TIPO_PAGO NOT IN ('EFE')
	where 1=1
	--AND SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1)='356087540'
	and  TRUNC(VM.CORTE_FECHA_CREACION) BETWEEN (SELECT TRUNC(ADD_MONTHS(MIN(CB.FECHA_DEPOSITO),-1)) FROM CB) AND (SELECT TRUNC(MAX(CB.FECHA_DEPOSITO)+1) FROM CB)
	GROUP BY VM.NUMERO_DOCUMENTO,SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO))
	,1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1)
					),          
					  TB AS (SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BV.NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID 
						   FROM CB INNER JOIN BV ON CB.REFERENCIA = BV.REFERENCIA
						   LEFT JOIN xxer_tbl_puente_header HD
							  ON  BV.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
						   GROUP BY CB.AFILIACION,BV.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID
							 UNION ALL
							SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVM.NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID
							  FROM CB INNER JOIN BVM ON CB.NO_OPERACION = BVM.REFERENCIA_PAGO
							  LEFT JOIN xxer_tbl_puente_header HD
							  ON  BVM.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
							  GROUP BY CB.AFILIACION,BVM.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID
							  ),
							   BCT AS (SELECT AFILIACION,SUM(IMPORTE) AS IMPORTE,FECHA_DEPOSITO FROM CB GROUP BY AFILIACION,FECHA_DEPOSITO)
							  SELECT BCT.AFILIACION,BCT.FECHA_DEPOSITO,SUM(TB.IMPORTE) AS IMPORTE_TMS,BCT.IMPORTE AS IMPORTE_BANCO,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA
							  ,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
							  ,LISTAGG(NVL(TB.TABLA_PUENTE_ID,0), ',') WITHIN  GROUP (ORDER BY TB.TABLA_PUENTE_ID) AS TABLA_PUENTE_IDS
							  FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION        
							  GROUP BY BCT.FECHA_DEPOSITO,BCT.AFILIACION,BCT.IMPORTE
							  ORDER BY DIFERENCIA ASC
						  
--conculta todos los datos NO ENCONTRDOS
WITH
        CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM  TMS_COCILIACION_BANCOS_TBL WHERE 1=1 
                --AND AFILIACION='9180159' AND TRUNC(FECHA_DEPOSITO)=TO_DATE('10/08/2021','DD/MM/YYYY') 
                AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT VE.NUMERO_DOCUMENTO,VE.REFERENCIA
		        ,LISTAGG(VE.FOLIO_PREIMPRESO_SOLO, ',') WITHIN  GROUP (ORDER BY VE.FOLIO_PREIMPRESO_SOLO) AS FOLIO_PREIMPRESOS
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VE
                WHERE TRUNC(VE.CORTE_FECHA_CREACION) BETWEEN TO_DATE('01/08/2021','DD/MM/YYYY') AND TO_DATE('30/09/2021','DD/MM/YYYY')
                AND VE.TIPO_PAGO NOT IN('EFE','AMX') AND  TIPO_OPERACION NOT IN ('HO','FO')  AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                GROUP BY VE.NUMERO_DOCUMENTO,VE.REFERENCIA
                ),
        BVM AS(
 SELECT
VM.NUMERO_DOCUMENTO,SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO))
,1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO
,LISTAGG(BR.FOLIO_PREIMPRESO, ',') WITHIN  GROUP (ORDER BY BR.FOLIO_PREIMPRESO) AS FOLIO_PREIMPRESOS
FROM EXTRACCION_MISCELANEA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VM
INNER JOIN TMS_CORTES_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX CR
ON (CR.CORTE_ID = VM.CORTE_ID)
INNER JOIN TMS_BOLETOS_VENTA_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VT
ON (VT.FOLIO_PREIMPRESO = VM.NO_FOLIO
AND TRUNC(VT.FECHA_CREACION) BETWEEN TO_DATE('01/08/2021','DD/MM/YYYY') AND TO_DATE('30/09/2021','DD/MM/YYYY')
AND VT.TIPO_TRANSACCION = 'L'
AND VT.TIPO_PAGO IN ('BBV','BAB'))
INNER JOIN TMS_BOLETOS_VENTA_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX BR
ON BR.BOLETO_RELACIONADO_ID = VT.BOLETO_ID AND BR.TIPO_PAGO NOT IN 'EFE'
where 1=1
--SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1)='347055192'
and  TRUNC(VM.CORTE_FECHA_CREACION) BETWEEN TO_DATE('01/08/2021','DD/MM/YYYY') AND TO_DATE('30/09/2021','DD/MM/YYYY')
GROUP BY VM.NUMERO_DOCUMENTO,SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO))
,1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1)
                ),          
                  TB AS (SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BV.NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID ,BV.REFERENCIA REFERENCIA,NULL REFERENCIA_PAGO,BV.FOLIO_PREIMPRESOS
                       FROM CB LEFT JOIN BV ON CB.REFERENCIA = BV.REFERENCIA                        
                       LEFT JOIN xxer_tbl_puente_header HD
                          ON  BV.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                       GROUP BY CB.AFILIACION,BV.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID,BV.REFERENCIA,BV.FOLIO_PREIMPRESOS,NULL),
                       TBM AS (
                        SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVM.NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID,NULL REFERENCIA,BVM.REFERENCIA_PAGO REFERENCIA_PAGO,BVM.FOLIO_PREIMPRESOS
                          FROM CB LEFT JOIN BVM ON CB.NO_OPERACION = BVM.REFERENCIA_PAGO 
                          LEFT JOIN xxer_tbl_puente_header HD
                          ON  BVM.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                          GROUP BY CB.AFILIACION,BVM.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID,BVM.REFERENCIA_PAGO,BVM.FOLIO_PREIMPRESOS,NULL
						  )
                          --SELECT * FROM TB
                          ,
                       CBN AS (
                                  SELECT  CB.AFILIACION,CB.FECHA_DEPOSITO,CB.IMPORTE,CB.REFERENCIA,CB.NO_OPERACION
                               FROM CB WHERE  NOT EXISTS (SELECT NULL
                                   FROM  TB
                                             WHERE TB.REFERENCIA = CB.REFERENCIA)
                                AND   NOT EXISTS (SELECT NULL
                                   FROM  TBM
                                             WHERE CB.NO_OPERACION= TBM.REFERENCIA_PAGO )
                                                  )                        
                          SELECT 
                          *
                          FROM CBN
                      
                 
                      

