SELECT SUM(cal.IMPORTE) AS IMPORTE,bank.IMPORTE from( WITH
        CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM TMS_COCILIACION_BANCOS_TBL
                Where TRUNC(FECHA_DEPOSITO) = TO_DATE('11/08/2021','DD/MM/YYYY') AND AFILIACION = 9180159 AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT TIPO_PAGO,ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@XER_BI_USER_REPLICA.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('05/08/2021','DD/MM/YYYY') AND TO_DATE('12/08/2021','DD/MM/YYYY') ),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO 
                      FROM (SELECT *  FROM BV  WHERE  TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 AND TIPO_PAGO != 'EFE')
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                      FROM (SELECT *  FROM BV WHERE  TIPO_OPERACION = 'HO' AND TIPO_PAGO != 'EFE')
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO)          
                  select CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                       from CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA 
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                union all
                  select CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                       from CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                       GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO)
					   
					   
SELECT sum(IMPORTE),AFILIACION,TRUNC(FECHA_DEPOSITO) AS FECHA_DEPOSITO FROM TMS_COCILIACION_BANCOS_TBL
Where 1=1
AND TRUNC(FECHA_DEPOSITO) = TO_DATE('09/08/2021','DD/MM/YYYY')
AND AFILIACION = 9180159
GROUP BY AFILIACION,FECHA_DEPOSITO;


SELECT SUM(IMPORTE) AS IMPORTE from( 
WITH
        CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) AS FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM TMS_COCILIACION_BANCOS_TBL
                Where TRUNC(FECHA_DEPOSITO) = TO_DATE('09/08/2021','DD/MM/YYYY') AND AFILIACION = 9180159 AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@XER_BI_USER_REPLICA.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('01/08/2021','DD/MM/YYYY') AND TO_DATE('30/08/2021','DD/MM/YYYY') ),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO 
                      FROM (SELECT *  FROM BV)
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                      FROM (SELECT *  FROM BV WHERE TIPO_OPERACION = 'HO' AND TO_NUMBER(ADICIONAL17)>0)
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO)          
                  SELECT CB.AFILIACION,SUM(CB.IMPORTE)AS IMPORTE,BVT.REFERENCIA ,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA 
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,BVT.REFERENCIA
                union all
                  SELECT CB.AFILIACION,sum(CB.IMPORTE)AS IMPORTE,BVP.REFERENCIA_PAGO ,BVP.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                       FROM CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                       GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,BVP.REFERENCIA_PAGO
                       );
WITH
        CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM TMS_COCILIACION_BANCOS_TBL
                Where TRUNC(FECHA_DEPOSITO) = TO_DATE('10/08/2021','DD/MM/YYYY') AND AFILIACION = 9180159 AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT TIPO_PAGO,ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@XER_BI_USER_REPLICA.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('05/08/2021','DD/MM/YYYY') AND TO_DATE('12/08/2021','DD/MM/YYYY') ),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO 
                      FROM (SELECT *  FROM BV  WHERE  TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 AND TIPO_PAGO != 'EFE')
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                      FROM (SELECT *  FROM BV WHERE  TIPO_OPERACION = 'HO' AND TIPO_PAGO != 'EFE')
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO)          
                  select CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                       from CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA 
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                union all
                  select CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                       from CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                       GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
					   
					   
 SET LONG 20000000 
 SET pagesize 50000
 WITH
         WITH
        CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM TMS_COCILIACION_BANCOS_TBL
                Where TRUNC(FECHA_DEPOSITO) IN( TO_DATE('27/09/2021','DD/MM/YYYY')) AND AFILIACION IN (9181868) AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT TIPO_PAGO,ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('20/09/2021','DD/MM/YYYY') AND TO_DATE('30/09/2021','DD/MM/YYYY') AND TIPO_PAGO != 'EFE'),
            BVT AS(SELECT REFERENCIA_PAGO,REFERENCIA,NUMERO_DOCUMENTO 
                      FROM (SELECT * FROM BV  WHERE TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                            UNION ALL
                            SELECT * FROM BV WHERE  TIPO_OPERACION = 'HO' AND TIPO_PAGO != 'EFE')
                      GROUP BY REFERENCIA_PAGO,REFERENCIA,NUMERO_DOCUMENTO),
                TB AS (SELECT 
                CB.AFILIACION,
                sum(CB.IMPORTE)as IMPORTE,
                BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,
                CB.FECHA_DEPOSITO,
                LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) as REFERENCIAS,
                LISTAGG(BVT.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA_PAGO) as REFERENCIAS_PAGO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA =BVT.REFERENCIA  OR CB.NO_OPERACION = BVT.REFERENCIA_PAGO
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO)
                       SELECT 
                       TB.AFILIACION,
                       sum(TB.IMPORTE)as IMPORTE,
                       TB.FECHA_DEPOSITO,
                       LISTAGG(TB.NUMERO_DOCUMENTO,',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO)  AS NUMEROS_DOCUMENTOS                       
                       --LISTAGG(TB.REFERENCIAS_BANCO, ',') WITHIN  GROUP (ORDER BY TB.REFERENCIAS_BANCO) as REFERENCIAS_BANCO
                       FROM TB
                       GROUP BY TB.AFILIACION,TB.FECHA_DEPOSITO
	--VERSION SIN VISTA 				   
			  
						  WITH
VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
     FROM XXER_AR_INVOICES_CONCILIACION_V inv
     where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen
     and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
     group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT),
        CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT TIPO_PAGO,ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('20/09/2021','DD/MM/YYYY') AND TO_DATE('29/09/2021','DD/MM/YYYY')AND TIPO_PAGO != 'EFE'),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO FROM BV  WHERE  TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION = 'HO' 
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO),          
                  TB AS (SELECT CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO--,LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) AS REFERENCIAS_BANCO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA 
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                         UNION ALL
                        SELECT CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO--,LISTAGG(BVP.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVP.REFERENCIA_PAGO) AS REFERENCIAS_BANCO
                          from CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                          GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO)
                          SELECT 
                          TB.AFILIACION,
                          sum(TB.IMPORTE)as IMPORTE,
                          TB.FECHA_DEPOSITO,
                          LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                          --,LISTAGG(TB.REFERENCIAS_BANCO, ',') WITHIN  GROUP (ORDER BY TB.REFERENCIAS_BANCO) AS REFERENCIAS_BANCO 
                          FROM TB
                          GROUP BY TB.AFILIACION,TB.FECHA_DEPOSITO;
						  
						  
						  
		---QUERYS CON REFERENCIA VISTA				  
						  
						  WITH
VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
     FROM XXER_AR_INVOICES_CONCILIACION_V inv
     where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
     group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT),
        CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT TIPO_PAGO,ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('01/09/2021','DD/MM/YYYY') AND TO_DATE('29/09/2021','DD/MM/YYYY')AND TIPO_PAGO != 'EFE'),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO FROM BV  WHERE  TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION = 'HO' 
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO),          
                  TB AS (SELECT CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO--,LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) AS REFERENCIAS_BANCO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA 
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                         UNION ALL
                        SELECT CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO--,LISTAGG(BVP.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVP.REFERENCIA_PAGO) AS REFERENCIAS_BANCO
                          from CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                          GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO)
                          SELECT 
                          TB.AFILIACION,
                          sum(BC.IMPORTE)as IMPORTE_BANCO,
                          sum(TB.IMPORTE)as IMPORTE,
                          TB.FECHA_DEPOSITO,
                          LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                          --,LISTAGG(TB.REFERENCIAS_BANCO, ',') WITHIN  GROUP (ORDER BY TB.REFERENCIAS_BANCO) AS REFERENCIAS_BANCO 
                          FROM TB,TMS_COCILIACION_BANCOS_TBL BC
                          WHERE BC.AFILIACION=TB.AFILIACION AND TRUNC(TB.FECHA_DEPOSITO)=TB.FECHA_DEPOSITO
                          GROUP BY TB.AFILIACION,TB.FECHA_DEPOSITO;
						  
						  
						  
						  
						  
 WITH
VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
     FROM XXER_AR_INVOICES_CONCILIACION_V inv
     where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen
     and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
     group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT),
        CB as (SELECT VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT TIPO_PAGO,ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('21/09/2021','DD/MM/YYYY') AND TO_DATE('26/09/2021','DD/MM/YYYY')AND TIPO_PAGO != 'EFE'),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO FROM BV  WHERE  TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION = 'HO' 
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO),          
                  TB AS (SELECT CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO--,LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) AS REFERENCIAS_BANCO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA 
                       GROUP BY CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                         UNION ALL
                        SELECT CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.AFILIACION,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO--,LISTAGG(BVP.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVP.REFERENCIA_PAGO) AS REFERENCIAS_BANCO
                          from CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                          GROUP BY CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO),
                  BCT AS (SELECT AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO FROM CB GROUP BY AFILIACION,FECHA_DEPOSITO)
                          SELECT TB.REFERENCE_PAYMENT,TB.METODO_RECIBO,BCT.AFILIACION,BCT.FECHA_DEPOSITO,SUM(TB.IMPORTE) AS IMPORTE_TMS,BCT.IMPORTE AS IMPORTE_BANCO,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA
                          ,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                          FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION 
                          GROUP BY BCT.FECHA_DEPOSITO,BCT.AFILIACION,TB.REFERENCE_PAYMENT,TB.METODO_RECIBO,BCT.IMPORTE
                          
--CON ID DE TABLA PUENTE 
 WITH
VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,max(inv.TOLERANCIA)as TOLERANCIA,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
     FROM XXER_AR_INVOICES_CONCILIACION_V inv
     where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen
     and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
     group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT),
        CB as (SELECT VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,VC.TOLERANCIA,AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT TIPO_PAGO,ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('21/09/2021','DD/MM/YYYY') AND TO_DATE('26/09/2021','DD/MM/YYYY')AND TIPO_PAGO != 'EFE'),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO FROM BV  WHERE  TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION = 'HO' 
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO),          
                  TB AS (SELECT CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.TOLERANCIA,CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID--,LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) AS REFERENCIAS_BANCO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA
                       LEFT JOIN XXER_TBL_PUENTE_HEADER HD ON BVT.NUMERO_DOCUMENTO=HD.NUMERO_DOCUMENTO 
                       GROUP BY CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.AFILIACION,CB.TOLERANCIA,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID
                         UNION ALL
                        SELECT CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.TOLERANCIA,CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID--,LISTAGG(BVP.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVP.REFERENCIA_PAGO) AS REFERENCIAS_BANCO
                          FROM CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                          LEFT JOIN XXER_TBL_PUENTE_HEADER HD ON BVP.NUMERO_DOCUMENTO=HD.NUMERO_DOCUMENTO
                          GROUP BY CB.REFERENCE_PAYMENT,CB.METODO_RECIBO,CB.AFILIACION,CB.TOLERANCIA,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID),
                  BCT AS (SELECT AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO FROM CB GROUP BY AFILIACION,FECHA_DEPOSITO)
                          SELECT TB.REFERENCE_PAYMENT,TB.METODO_RECIBO,BCT.AFILIACION,BCT.FECHA_DEPOSITO,SUM(TB.IMPORTE) AS IMPORTE_TMS,BCT.IMPORTE AS IMPORTE_BANCO,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA,TB.TOLERANCIA
                          ,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                          ,LISTAGG(NVL(TB.TABLA_PUENTE_ID,0), ',') WITHIN  GROUP (ORDER BY TB.TABLA_PUENTE_ID) AS TABLA_PUENTE_IDS
                          FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION 
                          GROUP BY BCT.FECHA_DEPOSITO,BCT.AFILIACION,TB.REFERENCE_PAYMENT,TB.TOLERANCIA,TB.METODO_RECIBO,BCT.IMPORTE
						  
						  
WITH
VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,max(inv.TOLERANCIA)as TOLERANCIA,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
     FROM XXER_AR_INVOICES_CONCILIACION_V inv
     where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen
     and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
     group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT),
        CB as (SELECT VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,VC.TOLERANCIA,AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT TIPO_PAGO,ADICIONAL17,TIPO_OPERACION,REFERENCIA,SUBSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),1,INSTR(SUBSTR(REFERENCIA_PAGO,INSTR(REFERENCIA_PAGO,';')+1 ,LENGTH(REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX
                WHERE TRUNC(CORTE_FECHA_CREACION) BETWEEN TO_DATE('10/09/2021','DD/MM/YYYY') AND TO_DATE('26/09/2021','DD/MM/YYYY')AND TIPO_PAGO != 'EFE'),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO FROM BV  WHERE  TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION = 'HO' 
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO),          
                  TB AS (SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO--,LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) AS REFERENCIAS_BANCO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                         UNION ALL
                        SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO--,LISTAGG(BVP.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVP.REFERENCIA_PAGO) AS REFERENCIAS_BANCO
                          FROM CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                          GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO
                          ),
                  BCT AS (SELECT REFERENCE_PAYMENT,METODO_RECIBO,TOLERANCIA,AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO FROM CB GROUP BY REFERENCE_PAYMENT,METODO_RECIBO,TOLERANCIA,AFILIACION,FECHA_DEPOSITO)
                          SELECT BCT.REFERENCE_PAYMENT,BCT.METODO_RECIBO,BCT.AFILIACION,BCT.FECHA_DEPOSITO,SUM(TB.IMPORTE) AS IMPORTE_TMS,BCT.IMPORTE AS IMPORTE_BANCO,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA,BCT.TOLERANCIA
                          ,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                          ,LISTAGG(NVL(HD.TABLA_PUENTE_ID,0), ',') WITHIN  GROUP (ORDER BY HD.TABLA_PUENTE_ID) AS TABLA_PUENTE_IDS
                          FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION 
                          LEFT JOIN XXER_TBL_PUENTE_HEADER HD ON TB.NUMERO_DOCUMENTO=HD.NUMERO_DOCUMENTO 
                          GROUP BY BCT.FECHA_DEPOSITO,BCT.AFILIACION,BCT.REFERENCE_PAYMENT,BCT.TOLERANCIA,BCT.METODO_RECIBO,BCT.IMPORTE
						  
						  
						  
						  -- VERSION CON MONTOS TOTALES tp TRANSACION
WITH
VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,max(inv.TOLERANCIA)as TOLERANCIA,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
     FROM XXER_AR_INVOICES_CONCILIACION_V inv
     where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen
     and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
     group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT),
        CB as (SELECT VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,VC.TOLERANCIA,AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT VE.TIPO_PAGO,VE.ADICIONAL17,VE.TIPO_OPERACION,VE.REFERENCIA,SUBSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),1,INSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,VE.NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VE
                WHERE TRUNC(VE.CORTE_FECHA_CREACION) BETWEEN TO_DATE('01/08/2021','DD/MM/YYYY') AND TO_DATE('30/09/2021','DD/MM/YYYY')AND VE.TIPO_PAGO != 'EFE'),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION != 'HO' AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION = 'HO' 
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO),          
                  TB AS (SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,HD.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO_SOA--,LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) AS REFERENCIAS_BANCO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA
                       LEFT JOIN xxer_tbl_puente_header HD
                          ON  BVT.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.NUMERO_DOCUMENTO
                         UNION ALL
                        SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,HD.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO_SOA--,LISTAGG(BVP.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVP.REFERENCIA_PAGO) AS REFERENCIAS_BANCO
                          FROM CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                          LEFT JOIN xxer_tbl_puente_header HD
                          ON  BVP.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                          GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.NUMERO_DOCUMENTO ),
                  BCT AS (SELECT REFERENCE_PAYMENT,METODO_RECIBO,TOLERANCIA,AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO FROM CB GROUP BY REFERENCE_PAYMENT,METODO_RECIBO,TOLERANCIA,AFILIACION,FECHA_DEPOSITO)
                          SELECT BCT.REFERENCE_PAYMENT,BCT.METODO_RECIBO,BCT.AFILIACION,BCT.FECHA_DEPOSITO,SUM(TB.IMPORTE) AS IMPORTE_TMS,BCT.IMPORTE AS IMPORTE_BANCO,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA,BCT.TOLERANCIA
                          ,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                          ,LISTAGG(TB.NUMERO_DOCUMENTO_SOA, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO_SOA) AS NUMEROS_DOCUMENTOS_SOA
                          --,LISTAGG(NVL(HD.TABLA_PUENTE_ID,0), ',') WITHIN  GROUP (ORDER BY HD.TABLA_PUENTE_ID) AS TABLA_PUENTE_IDS
                          FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION        
                          GROUP BY BCT.FECHA_DEPOSITO,BCT.AFILIACION,BCT.REFERENCE_PAYMENT,BCT.TOLERANCIA,BCT.METODO_RECIBO,BCT.IMPORTE
						  
						  
--BUSQUEDA REFERENCIAS CON INFORMACION PAGOS
WITH
	VC AS (SELECT inv.REFERENCE_PAYMENT,inv.METODO_RECIBO,TO_DATE(SUBSTR(inv.REFERENCE_PAYMENT, -8,8),'DDMMYYYY') AS FECHA,TO_NUMBER(SUBSTR(inv.REFERENCE_PAYMENT, -18,9)) AS AFIL
		 FROM XXER_AR_INVOICES_CONCILIACION_V inv
		 where 1=1 AND TRUNC(inv.FECHA_MOVIMIENTO)>= TRUNC(inv.FECHA_MOVIMIENTO) AND NVL(inv.unidad_negocio_origen,1)=unidad_negocio_origen
		 and inv.reference_payment=inv.reference_payment AND inv.METODO_RECIBO=inv.METODO_RECIBO AND SUBSTR(inv.reference_payment,1,4) IN ( 'AFIL')
		 group by inv.METODO_RECIBO,inv.REFERENCE_PAYMENT)
		 SELECT VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO
					FROM VC INNER JOIN TMS_COCILIACION_BANCOS_TBL ON TRUNC(FECHA_DEPOSITO) = TRUNC(VC.FECHA) AND AFILIACION = VC.AFIL AND USUARIO NOT IN('0670GGZM0')
					GROUP BY  VC.REFERENCE_PAYMENT,VC.METODO_RECIBO,AFILIACION,FECHA_DEPOSITO;
					
					
					9356614447
--LISTAR TODOS LOS PAGOS EN TABLA TMS BANCOS
--SE AGREGA A LA BUSQUEDA REFERENCIA_PAGO 'FO' POR QUE ASI SALEN CIERTOS PAGOS
--se enCONTRO SALDO  ADICIONAL  TRNASACCION CON FO AFIL:5256409,25/08/2021 REF:13298240821200656
--ANALISIS  and AFILIACION='5256409' and TRUNC(FECHA_DEPOSITO)=TO_DATE('18/08/2021','DD/MM/YYYY')and  IMPORTE='348' NO ENCONTRADO:13212170821142340
WITH
        CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM  TMS_COCILIACION_BANCOS_TBL WHERE 1=1 AND USUARIO NOT IN('0670GGZM0')),
        BV AS(SELECT VE.TIPO_PAGO,VE.ADICIONAL17,VE.TIPO_OPERACION,VE.REFERENCIA,SUBSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),1,INSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,VE.NUMERO_DOCUMENTO 
                FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VE
                WHERE TRUNC(VE.CORTE_FECHA_CREACION) BETWEEN TO_DATE('01/08/2021','DD/MM/YYYY') AND TO_DATE('30/09/2021','DD/MM/YYYY')AND VE.TIPO_PAGO NOT IN('EFE','AMX')),
            BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION NOT IN ('HO','FO')  AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                      GROUP BY REFERENCIA,NUMERO_DOCUMENTO),
            BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO FROM BV WHERE  TIPO_OPERACION IN ('HO','FO') 
                      GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO),          
                  TB AS (SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID --,LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) AS REFERENCIAS_BANCO
                       FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA
                       LEFT JOIN xxer_tbl_puente_header HD
                          ON  BVT.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                       GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID
                         UNION ALL
                        SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID--,LISTAGG(BVP.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVP.REFERENCIA_PAGO) AS REFERENCIAS_BANCO
                          FROM CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                          LEFT JOIN xxer_tbl_puente_header HD
                          ON  BVP.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                          GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID
						  ),
                  BCT AS (SELECT AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO FROM CB GROUP BY AFILIACION,FECHA_DEPOSITO)
                          SELECT BCT.AFILIACION,BCT.FECHA_DEPOSITO,SUM(TB.IMPORTE) AS IMPORTE_TMS,BCT.IMPORTE AS IMPORTE_BANCO,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA
                          ,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                          --,LISTAGG(TB.NUMERO_DOCUMENTO_SOA, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO_SOA) AS NUMEROS_DOCUMENTOS_SOA
                          ,LISTAGG(NVL(TB.TABLA_PUENTE_ID,0), ',') WITHIN  GROUP (ORDER BY TB.TABLA_PUENTE_ID) AS TABLA_PUENTE_IDS
                          FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION        
                          GROUP BY BCT.FECHA_DEPOSITO,BCT.AFILIACION,BCT.IMPORTE
                
                

select h.estatus,h.numero_documento,
h.fecha_movimiento,h.tabla_puente_id,
h.sistema_origen,h.tipo_documento,h.sucursal_venta,h.referencia_aplicacion,h.creation_date,h.adicional2,h.*
from xxer_tbl_puente_header h
where 1=1
--and h.tabla_puente_id=''
--and h.tipo_documento='LIQUIDACION'
and numero_documento in('0682119ERP44AERTF')--,'21621277CTP01TCTTF','21621115CTP04TCTTF','21621277CTP1MSCTTF')--,'TT-4188','TT-4187','TT-4186','TT-4184','TT-4183')
--and trunc(fecha_movimiento) = to_date('06/03/2019','DD/MM/RRRR')
--and h.estatus='P'
--and empresa_origen='Contactos Terrestres'
order by h.fecha_movimiento desc;



SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                FROM  TMS_COCILIACION_BANCOS_TBL WHERE 1=1 AND USUARIO NOT IN('0670GGZM0')
                and AFILIACION='5256409' and TRUNC(FECHA_DEPOSITO)=TO_DATE('18/08/2021','DD/MM/YYYY')and  IMPORTE='348'
                
                

SELECT VE.FOLIO_PREIMPRESO_SOLO,VE.REFERENCIA_AMX,VE.TIPO_PAGO,VE.ADICIONAL17,VE.TIPO_OPERACION,VE.REFERENCIA,SUBSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),1,INSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,VE.NUMERO_DOCUMENTO 
FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VE
                WHERE TRUNC(VE.CORTE_FECHA_CREACION) BETWEEN TO_DATE('10/08/2021','DD/MM/YYYY') AND TO_DATE('19/08/2021','DD/MM/YYYY')--AND VE.TIPO_PAGO != 'EFE'
                and VE.REFERENCIA in (SELECT REFERENCIA--,NO_OPERACION
                FROM  TMS_COCILIACION_BANCOS_TBL WHERE 1=1 AND USUARIO NOT IN('0670GGZM0')
                and AFILIACION='5256409' and TRUNC(FECHA_DEPOSITO)=TO_DATE('18/08/2021','DD/MM/YYYY')and  IMPORTE='348')
                
                AND SUBSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,
                LENGTH(VE.REFERENCIA_PAGO)),1,INSTR(SUBSTR(VE.REFERENCIA_PAGO,
                INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),';',-2)-1) in ('355180040')
                
		
--QUERY CON DETALLE DE BOLETO 
    WITH
            CB as (SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                    FROM  TMS_COCILIACION_BANCOS_TBL WHERE 1=1 AND USUARIO NOT IN('0670GGZM0')
                    and AFILIACION='5256409' 
                    and TRUNC(FECHA_DEPOSITO)=TO_DATE('18/08/2021','DD/MM/YYYY')
                    --and  IMPORTE='348'
                    ),
            BV AS(SELECT VE.FOLIO_PREIMPRESO_SOLO,VE.TIPO_PAGO,VE.ADICIONAL17,VE.TIPO_OPERACION,VE.REFERENCIA,SUBSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),1,INSTR(SUBSTR(VE.REFERENCIA_PAGO,INSTR(VE.REFERENCIA_PAGO,';')+1 ,LENGTH(VE.REFERENCIA_PAGO)),';',-2)-1) REFERENCIA_PAGO,VE.NUMERO_DOCUMENTO 
                    FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VE
                    WHERE TRUNC(VE.CORTE_FECHA_CREACION) BETWEEN TO_DATE('10/08/2021','DD/MM/YYYY') AND TO_DATE('19/08/2021','DD/MM/YYYY')AND VE.TIPO_PAGO != 'EFE'),
                BVT AS(SELECT REFERENCIA,NUMERO_DOCUMENTO--,FOLIO_PREIMPRESO_SOLO 
                FROM BV WHERE  TIPO_OPERACION NOT IN ('HO','FO') AND NVL (TO_NUMBER(ADICIONAL17),0) = 0 
                          GROUP BY REFERENCIA,NUMERO_DOCUMENTO--,FOLIO_PREIMPRESO_SOLO
                          ),
                BVP AS(SELECT REFERENCIA_PAGO,NUMERO_DOCUMENTO--,FOLIO_PREIMPRESO_SOLO 
                FROM BV WHERE  TIPO_OPERACION IN ('HO','FO') 
                          GROUP BY REFERENCIA_PAGO,NUMERO_DOCUMENTO--,FOLIO_PREIMPRESO_SOLO
                          ),          
                      TB AS (SELECT --CB.NO_OPERACION,
                      CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVT.NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO,BVT.REFERENCIA AS REFERENCIA--,BVT.FOLIO_PREIMPRESO_SOLO--,HD.TABLA_PUENTE_ID --,LISTAGG(BVT.REFERENCIA, ',') WITHIN  GROUP (ORDER BY BVT.REFERENCIA) AS REFERENCIAS_BANCO
                           FROM CB INNER JOIN BVT ON CB.REFERENCIA = BVT.REFERENCIA
                           /*LEFT JOIN xxer_tbl_puente_header HD
                              ON  BVT.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO*/
                           GROUP BY CB.AFILIACION,BVT.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,BVT.REFERENCIA--,CB.NO_OPERACION--,BVT.FOLIO_PREIMPRESO_SOLO--,HD.TABLA_PUENTE_ID
                             UNION ALL
                            SELECT --CB.NO_OPERACION,
                            CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE,BVP.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO,BVP.REFERENCIA_PAGO AS REFERENCIA--,BVP.FOLIO_PREIMPRESO_SOLO--,HD.TABLA_PUENTE_ID--,LISTAGG(BVP.REFERENCIA_PAGO, ',') WITHIN  GROUP (ORDER BY BVP.REFERENCIA_PAGO) AS REFERENCIAS_BANCO
                              FROM CB INNER JOIN BVP ON CB.NO_OPERACION = BVP.REFERENCIA_PAGO
                              /*LEFT JOIN xxer_tbl_puente_header HD
                              ON  BVP.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO*/
                              GROUP BY CB.AFILIACION,BVP.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,BVP.REFERENCIA_PAGO--,CB.NO_OPERACION--,BVP.FOLIO_PREIMPRESO_SOLO--,HD.TABLA_PUENTE_ID 
                              ),
                      BCT AS (SELECT AFILIACION,SUM(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO FROM CB GROUP BY AFILIACION,FECHA_DEPOSITO)
                              SELECT BCT.AFILIACION,TB.IMPORTE AS IMPORTE_TMS--,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA
                              ,TB.NUMERO_DOCUMENTO,TB.REFERENCIA--,TB.NO_OPERACION--,TB.FOLIO_PREIMPRESO_SOLO
                              --,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                              --,LISTAGG(TB.NUMERO_DOCUMENTO_SOA, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO_SOA) AS NUMEROS_DOCUMENTOS_SOA
                              --,LISTAGG(NVL(TB.TABLA_PUENTE_ID,0), ',') WITHIN  GROUP (ORDER BY TB.TABLA_PUENTE_ID) AS TABLA_PUENTE_IDS
                              FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION    
		