--------------------------------------------------------
-- Archivo creado  - martes-enero-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXER_COMPLEMENTS_AP_TBL
--------------------------------------------------------

  CREATE TABLE "PXERINTUSER"."XXER_COMPLEMENTS_AP_TBL" 
   (	"PAYMENT_ID" NUMBER, 
	"PAYMENT_NUMBER" VARCHAR2(150 CHAR), 
	"NOMBRE_EMISOR" VARCHAR2(150 CHAR), 
	"EMISOR_RFC" VARCHAR2(13 BYTE), 
	"NOMBRE_PRECEPTOR" VARCHAR2(150 CHAR), 
	"RECEPTOR_RFC" VARCHAR2(13 BYTE), 
	"PAYMENT_AMOUNT" NUMBER, 
	"PAYMENT_CURRENCY" VARCHAR2(50 BYTE), 
	"PAYMENT_DATE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(150 CHAR), 
	"STATUS_DESC" VARCHAR2(3000 CHAR), 
	"FOLIO_XML" VARCHAR2(50 CHAR), 
	"SERIE_XML" VARCHAR2(50 CHAR), 
	"NOMBRE_EMISOR_XML" VARCHAR2(150 CHAR), 
	"EMISOR_RFC_XML" VARCHAR2(13 BYTE), 
	"NOMBRE_RECEPTOR_XML" VARCHAR2(150 CHAR), 
	"RECEPTOR_RFC_XML" VARCHAR2(13 BYTE), 
	"TOTAL_XML" VARCHAR2(50 CHAR), 
	"SUBTOTAL_XML" VARCHAR2(50 CHAR), 
	"TIPO_CAMBIO_XML" VARCHAR2(50 CHAR), 
	"MONEDA_XML" VARCHAR2(150 CHAR), 
	"USO_CFDI_XML" VARCHAR2(150 CHAR), 
	"FORMA_PAGO_XML" VARCHAR2(50 CHAR), 
	"TIPO_COMPROBANTE_XML" VARCHAR2(150 CHAR), 
	"DESCRIPCION_XML" VARCHAR2(350 CHAR), 
	"UUID_XML" VARCHAR2(50 CHAR), 
	"FECHA_XML" VARCHAR2(50 CHAR), 
	"FECHA_TIMBRADO_XML" VARCHAR2(50 CHAR), 
	"ATTRIBUTE1" VARCHAR2(150 CHAR), 
	"ATTRIBUTE2" VARCHAR2(150 CHAR), 
	"ATTRIBUTE3" VARCHAR2(150 CHAR), 
	"ATTRIBUTE4" VARCHAR2(150 CHAR), 
	"ATTRIBUTE5" VARCHAR2(150 CHAR), 
	"CREATED_BY" VARCHAR2(150 CHAR), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT (sysdate), 
	"LAST_UPDATED_BY" VARCHAR2(150 CHAR), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"OBJECT_VERSION_NUMBER" NUMBER(9,0), 
	"OBJETO_IMP_XML" VARCHAR2(2 BYTE), 
	"RECEPTOR_REGIMEN" VARCHAR2(3 BYTE), 
	"EMISOR_REGIMEN" VARCHAR2(3 BYTE), 
	"RECEPTOR_REGIMEN_XML" VARCHAR2(3 BYTE), 
	"EMISOR_REGIMEN_XML" VARCHAR2(3 BYTE), 
	"VERSION_XML" VARCHAR2(3 BYTE), 
	"PAYMENT_STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0023938
--------------------------------------------------------

  CREATE UNIQUE INDEX "PXERINTUSER"."SYS_C0023938" ON "PXERINTUSER"."XXER_COMPLEMENTS_AP_TBL" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;
--------------------------------------------------------
--  Constraints for Table XXER_COMPLEMENTS_AP_TBL
--------------------------------------------------------

  ALTER TABLE "PXERINTUSER"."XXER_COMPLEMENTS_AP_TBL" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PXERINTUSER"."XXER_COMPLEMENTS_AP_TBL" ADD PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS"  ENABLE;
