  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XERINTUSER"."XXER_AR_INVOICES_CONCILIACION_V" ("NUMERO_DOCUMENTO", "TOTAL", "TABLA_PUENTE_ID", "RECEIPT_METHOD_ID", "ORGANIZATION_ID", "RFC_ORIGEN", "FRECUENCIA", "METODO_RECIBO", "REFERENCE_PAYMENT", "FECHA_MOVIMIENTO", "UNIDAD_NEGOCIO_ORIGEN", "TOLERANCIA") AS   
  WITH
TXN AS (SELECT H.NUMERO_DOCUMENTO , TRUNC(H.FECHA_MOVIMIENTO) FECHA_MOVIMIENTO , H.NOMBRE_FISCAL_ORIGEN , H.SISTEMA_ORIGEN , H.UNIDAD_NEGOCIO_ORIGEN ,
                                H.TIPO_DOCUMENTO , H.TIPO_MOVIMIENTO , H.SUCURSAL_VENTA , L.ORIGEN_SERVICIO
                               , L.DESTINO_SERVICIO , L.SERVICIO , L.CONCEPTO_MODALIDAD , L.FORMA_PAGO , H.RFC_ORIGEN ,
                               H.ADICIONAL1 , H.ADICIONAL3 , H.ADICIONAL4 , H.ADICIONAL5 , H.ADICIONAL6 , L.TOTAL
                               , H.ADICIONAL7 , H.ADICIONAL8 , H.ADICIONAL9 , H.ADICIONAL10 ,H.TABLA_PUENTE_ID ,L.TABLA_PUENTE_LINEA_ID
                FROM XXER_TBL_PUENTE_HEADER H, XXER_TBL_PUENTE_LINES L WHERE H.TABLA_PUENTE_ID = L.TABLA_PUENTE_ID AND H.SISTEMA_ORIGEN NOT IN ('EAM', 'INV', 'PORTAL')
                                 AND H.TIPO_DOCUMENTO NOT IN ('RECIBO', 'REVERSO RECIBO') )
,CNF AS (SELECT DISTINCT CF.*, 
NVL(REGEXP_SUBSTR(CF.METODO_RECIBO,'[^,]+',1,LEVEL),CF.METODO_RECIBO) METODO_RECIBO_M,
NVL(REGEXP_SUBSTR(CF.CONCILIACION,'[^,]+',1,LEVEL),CF.CONCILIACION) CONCILIACION_M,
NVL(REGEXP_SUBSTR(CF.PREFIJO_CONC,'[^,]+',1,LEVEL),CF.PREFIJO_CONC) PREFIJO_CONC_M,
NVL(REGEXP_SUBSTR(CF.MASCARA_CONC,'[^,]+',1,LEVEL),CF.MASCARA_CONC) MASCARA_CONC_M,
NVL(REGEXP_SUBSTR(CF.SUBFIJO_CONC,'[^,]+',1,LEVEL),CF.SUBFIJO_CONC) SUBFIJO_CONC_M,
NVL(REGEXP_SUBSTR(CF.FRECUENCIA_CONC,'[^,]+',1,LEVEL),CF.FRECUENCIA_CONC) FRECUENCIA_CONC_M,
NVL(REGEXP_SUBSTR(CF.TOLERANCIA_CONC,'[^,]+',1,LEVEL),CF.TOLERANCIA_CONC) TOLERANCIA_CONC_M
FROM XXER_CNF_INTERFASE_INGRESOS_AR CF 
  CONNECT BY LEVEL<=REGEXP_COUNT(CF.PREFIJO_CONC,',')+1)
SELECT 
RPC."NUMERO_DOCUMENTO",
RPC."TOTAL",
RPC."TABLA_PUENTE_ID",
RPC."RECEIPT_METHOD_ID",
RPC."ORGANIZATION_ID",
RPC."RFC_ORIGEN",
RPC."FRECUENCIA",
RPC."METODO_RECIBO",
RPC."REFERENCE_PAYMENT",
RPC."FECHA_MOVIMIENTO",
RPC."UNIDAD_NEGOCIO_ORIGEN",
RPC."TOLERANCIA" 
FROM (SELECT
     TXN.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO
    ,TXN.TOTAL AS TOTAL
    ,TXN.TABLA_PUENTE_ID AS TABLA_PUENTE_ID
    ,CNF.FRECUENCIA_CONC_M AS FRECUENCIA
    ,CNF.METODO_RECIBO_M AS METODO_RECIBO
    ,CNF.RECEIPT_METHOD_ID
    ,CNF.ORGANIZATION_ID
    ,TXN.RFC_ORIGEN
    ,(CASE
        WHEN SUBSTR(CNF.PREFIJO_CONC_M,1,4) = 'AFIL' THEN 
            CNF.PREFIJO_CONC_M||
			TO_CHAR(TO_DATE(TXN.FECHA_MOVIMIENTO)+
            (CASE MOD(TO_CHAR(TXN.FECHA_MOVIMIENTO,'J'),7)
            WHEN 4
            THEN 3
            WHEN 5
            THEN 2
            ELSE 1 END)
            ,CNF.MASCARA_CONC_M)||CNF.SUBFIJO_CONC_M
		WHEN SUBSTR(CNF.PREFIJO_CONC_M,1,9) = 'AMEXCO SE' THEN 
            CNF.PREFIJO_CONC_M||
			TO_CHAR(TO_DATE(TXN.FECHA_MOVIMIENTO)+
            (CASE MOD(TO_CHAR(TXN.FECHA_MOVIMIENTO,'J'),7)
            WHEN 4
            THEN 3
            WHEN 5
            THEN 2
            ELSE 1 END)
            ,CNF.MASCARA_CONC_M)||CNF.SUBFIJO_CONC_M
        ELSE
        (case
        WHEN CNF.FRECUENCIA_CONC_M = 'D' THEN CNF.PREFIJO_CONC_M||TO_CHAR(TXN.FECHA_MOVIMIENTO,CNF.MASCARA_CONC_M)||CNF.SUBFIJO_CONC_M
        WHEN CNF.FRECUENCIA_CONC_M = 'S' THEN CNF.PREFIJO_CONC_M||TO_CHAR(TXN.FECHA_MOVIMIENTO+(6-MOD(TO_CHAR(TXN.FECHA_MOVIMIENTO,'J'),7)),CNF.MASCARA_CONC_M)||CNF.SUBFIJO_CONC_M
        ELSE NULL END)
        end) as REFERENCE_PAYMENT
	,TXN.FECHA_MOVIMIENTO
	,TXN.UNIDAD_NEGOCIO_ORIGEN 
    ,NVL(CNF.TOLERANCIA_CONC_M,10) AS TOLERANCIA
FROM TXN
    LEFT JOIN CNF ON NVL (TXN.SISTEMA_ORIGEN, 1) = NVL (CNF.SISTEMA_ORIGEN, 1)
         AND NVL (TXN.TIPO_DOCUMENTO, 1) = NVL (CNF.TIPO_DOCUMENTO, 1)
         AND NVL (TXN.TIPO_MOVIMIENTO, 1) = NVL (CNF.TIPO_MOVIMIENTO, 1)
         AND NVL (TXN.RFC_ORIGEN, 1) = DECODE (NVL (CNF.SISTEMA_ORIGEN, 1),'NOMINA', NVL (TXN.RFC_ORIGEN, 1),NVL (CNF.RFC_ORIGEN, 1))
         AND NVL (TXN.SUCURSAL_VENTA, 1) = DECODE (NVL (CNF.SUCURSAL_VENTA, 1),'TODOS', NVL (TXN.SUCURSAL_VENTA, 1),NVL (CNF.SUCURSAL_VENTA, 1))
         AND NVL (TXN.ORIGEN_SERVICIO, 1) = DECODE (NVL (CNF.ORIGEN_SERVICIO, 1),'TODOS', NVL (TXN.ORIGEN_SERVICIO, 1),NVL (CNF.ORIGEN_SERVICIO, 1))
         AND NVL (TXN.DESTINO_SERVICIO, 1) = DECODE (NVL (CNF.DESTINO_SERVICIO, 1),'TODOS', NVL (TXN.DESTINO_SERVICIO, 1),NVL (CNF.DESTINO_SERVICIO, 1))
         AND NVL (TXN.SERVICIO, 1) = DECODE (NVL (CNF.SERVICIO, 1),'TODOS', NVL (TXN.SERVICIO, 1),NVL (CNF.SERVICIO, 1))
         AND NVL (TXN.CONCEPTO_MODALIDAD, 1) = NVL (CNF.CONCEPTO_MODALIDAD, 1)
         AND NVL (TXN.FORMA_PAGO, 1) = DECODE (NVL (CNF.FORMA_PAGO, 1),'TODOS', NVL (TXN.FORMA_PAGO, 1),NVL (CNF.FORMA_PAGO, 1))
         AND NVL (TXN.ADICIONAL1, 1) = NVL (CNF.ADICIONAL1, 1)
         AND NVL (TXN.ADICIONAL3, 1) = NVL (CNF.ADICIONAL3, 1)
         AND NVL (TXN.ADICIONAL4, 1) = NVL (CNF.ADICIONAL4, 1)
         AND NVL (TXN.ADICIONAL5, 1) = NVL (CNF.ADICIONAL5, 1)
         AND NVL (TXN.ADICIONAL6, 1) = NVL (CNF.ADICIONAL6, 1)
         AND NVL (TXN.ADICIONAL7, 1) = NVL (CNF.ADICIONAL7, 1)
         AND NVL (TXN.ADICIONAL8, 1) = NVL (CNF.ADICIONAL8, 1)
         AND NVL (TXN.ADICIONAL9, 1) = NVL (CNF.ADICIONAL9, 1)
         AND NVL (TXN.ADICIONAL10, 1) = NVL (CNF.ADICIONAL10, 1)
		 AND CNF.METODO_RECIBO_M IS NOT NULL
         
WHERE CNF.CONCILIACION_M = 'SI'
) RPC
    LEFT JOIN XXER_AR_CONCILIACION_TBL TCO ON RPC.REFERENCE_PAYMENT = TCO.REFERENCE_PAYMENT AND RPC.METODO_RECIBO = TCO.METODO_RECIBO
WHERE NVL(trim(TCO.STATUS),'NC') != 'C' 
AND TRUNC(RPC.FECHA_MOVIMIENTO)>= TRUNC(TO_DATE('30/03/2021','DD/MM/YYYY'))
--and RPC.NUMERO_DOCUMENTO in('0162115ERP01AERTF')
and RPC.REFERENCE_PAYMENT in ('AMEXCO SE 9356614447-10092021','AMEXCO SE 9356614447-13092021','AMEXCO SE 9356614447-14092021','AMEXCO SE 9356614447-15092021','26092021SURT','11052021CAPUT','05052021CAPUT','08052021CAPUT','09052021CAPUT','18052021CAPSETEXT','26052021CAPSETEXT','17052019WTCT','AFIL.-007273370-03052021','AFIL.-009270083-03052021','AFIL.-009270083-04052021','17052021WTCT','AFIL.-009180159-10082021','AFIL.-009181868-27092021','AFIL.-007273370-23092021','AFIL.-008180414-27092021','21082030PDESTT','AMEXCO SE 9356614447-21082027','21082027HUEJOT','21092025PDESTT','22082027SURT','AFIL.-009270083-22092021','AFIL.-008139649-22092021','AFIL.-008376766-22092021','AFIL.-009180159-22092021','AFIL.-005256409-22092021','AFIL.-008180414-22092021','AFIL.-009181868-22092021','AFIL.-007273370-22092021')
--and RPC.REFERENCE_PAYMENT in ('26092021SURT','AFIL.-009270083-22092021','AFIL.-009181868-22092021','21092021TAPOT','21092021HUEJOT')
;