
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "XERINTUSER"."XXER_AR_INVOICES_CONCILIACION_V" ("NUMERO_DOCUMENTO", "TOTAL", "TABLA_PUENTE_ID", "RECEIPT_METHOD_ID", "ORGANIZATION_ID", "RFC_ORIGEN", "FRECUENCIA", "METODO_RECIBO", "REFERENCE_PAYMENT", "FECHA_MOVIMIENTO", "UNIDAD_NEGOCIO_ORIGEN", "TOLERANCIA") AS 
  WITH
TXN AS (SELECT H.NUMERO_DOCUMENTO , TRUNC(H.FECHA_MOVIMIENTO) FECHA_MOVIMIENTO , H.NOMBRE_FISCAL_ORIGEN , H.SISTEMA_ORIGEN , H.UNIDAD_NEGOCIO_ORIGEN ,
                                H.TIPO_DOCUMENTO , H.TIPO_MOVIMIENTO , H.SUCURSAL_VENTA , L.ORIGEN_SERVICIO,
                                TO_NUMBER(to_char(TO_DATE(H.FECHA_MOVIMIENTO), 'DD')) as DIA,
(CASE
when  TO_NUMBER(to_char(TO_DATE(H.FECHA_MOVIMIENTO), 'MM'))<=2
then TO_NUMBER(to_char(TO_DATE(H.FECHA_MOVIMIENTO), 'MM'))+12
else TO_NUMBER(to_char(TO_DATE(H.FECHA_MOVIMIENTO), 'MM')) end)
as
MES,
(CASE
when  TO_NUMBER(to_char(TO_DATE(H.FECHA_MOVIMIENTO), 'MM'))<=2
then TO_NUMBER(to_char(TO_DATE(H.FECHA_MOVIMIENTO), 'YYYY'))-1
else TO_NUMBER(to_char(TO_DATE(H.FECHA_MOVIMIENTO), 'YYYY')) end)
as
ANIO
                               , L.DESTINO_SERVICIO , L.SERVICIO , L.CONCEPTO_MODALIDAD , L.FORMA_PAGO , H.RFC_ORIGEN ,
                               H.ADICIONAL1 , H.ADICIONAL3 , H.ADICIONAL4 , H.ADICIONAL5 , H.ADICIONAL6 , L.TOTAL
                               , H.ADICIONAL7 , H.ADICIONAL8 , H.ADICIONAL9 , H.ADICIONAL10 ,H.TABLA_PUENTE_ID ,L.TABLA_PUENTE_LINEA_ID
                FROM XXER_TBL_PUENTE_HEADER H, XXER_TBL_PUENTE_LINES L WHERE H.TABLA_PUENTE_ID = L.TABLA_PUENTE_ID AND H.SISTEMA_ORIGEN NOT IN ('EAM', 'INV', 'PORTAL')
                                 AND H.TIPO_DOCUMENTO NOT IN ('RECIBO', 'REVERSO RECIBO') )
,CNF AS (SELECT * FROM XXER_CNF_INTERFASE_INGRESOS_AR)
SELECT 
RPC."NUMERO_DOCUMENTO",
RPC."TOTAL",
RPC."TABLA_PUENTE_ID",
RPC."RECEIPT_METHOD_ID",
RPC."ORGANIZATION_ID",
RPC."RFC_ORIGEN",
RPC."FRECUENCIA",
RPC."METODO_RECIBO",
RPC."REFERENCE_PAYMENT",
RPC."FECHA_MOVIMIENTO",
RPC."UNIDAD_NEGOCIO_ORIGEN",
RPC."TOLERANCIA" 
FROM (SELECT
     TXN.NUMERO_DOCUMENTO as NUMERO_DOCUMENTO
    ,TXN.TOTAL AS TOTAL
    ,TXN.TABLA_PUENTE_ID AS TABLA_PUENTE_ID
    ,CNF.FRECUENCIA_CONC AS FRECUENCIA
    ,CNF.METODO_RECIBO AS METODO_RECIBO
    ,CNF.RECEIPT_METHOD_ID
    ,CNF.ORGANIZATION_ID
    ,TXN.RFC_ORIGEN
    ,(CASE
        WHEN SUBSTR(CNF.PREFIJO_CONC,1,4) = 'AFIL' THEN 
            CNF.PREFIJO_CONC||
			TO_CHAR(TO_DATE(TXN.FECHA_MOVIMIENTO)+
            (CASE MOD((TXN.DIA + FLOOR( (13 * (TXN.MES + 1)) / 5) + TXN.ANIO + FLOOR(TXN.ANIO/4) - FLOOR(TXN.ANIO / 100) + FLOOR(TXN.ANIO/400)) , 7)
            WHEN 6
            THEN 3
            WHEN 0
            THEN 2
            ELSE 1 END)
            ,CNF.MASCARA_CONC)||CNF.SUBFIJO_CONC
        ELSE
        (case
        WHEN CNF.FRECUENCIA_CONC = 'D' THEN CNF.PREFIJO_CONC||TO_CHAR(TXN.FECHA_MOVIMIENTO,CNF.MASCARA_CONC)||CNF.SUBFIJO_CONC
        WHEN CNF.FRECUENCIA_CONC = 'S'
            THEN CNF.PREFIJO_CONC||TO_CHAR(TO_DATE(TXN.FECHA_MOVIMIENTO)+(7- TO_CHAR(TO_DATE(TXN.FECHA_MOVIMIENTO),'D')),CNF.MASCARA_CONC)||CNF.SUBFIJO_CONC
        ELSE NULL END)
        end) as REFERENCE_PAYMENT
	,TXN.FECHA_MOVIMIENTO
	,TXN.UNIDAD_NEGOCIO_ORIGEN 
    ,NVL(CNF.TOLERANCIA_CONC,10) AS TOLERANCIA
FROM TXN
    LEFT JOIN CNF ON NVL (TXN.SISTEMA_ORIGEN, 1) = NVL (CNF.SISTEMA_ORIGEN, 1)
         AND NVL (TXN.TIPO_DOCUMENTO, 1) = NVL (CNF.TIPO_DOCUMENTO, 1)
         AND NVL (TXN.TIPO_MOVIMIENTO, 1) = NVL (CNF.TIPO_MOVIMIENTO, 1)
         AND NVL (TXN.RFC_ORIGEN, 1) = DECODE (NVL (CNF.SISTEMA_ORIGEN, 1),'NOMINA', NVL (TXN.RFC_ORIGEN, 1),NVL (CNF.RFC_ORIGEN, 1))
         AND NVL (TXN.SUCURSAL_VENTA, 1) = DECODE (NVL (CNF.SUCURSAL_VENTA, 1),'TODOS', NVL (TXN.SUCURSAL_VENTA, 1),NVL (CNF.SUCURSAL_VENTA, 1))
         AND NVL (TXN.ORIGEN_SERVICIO, 1) = DECODE (NVL (CNF.ORIGEN_SERVICIO, 1),'TODOS', NVL (TXN.ORIGEN_SERVICIO, 1),NVL (CNF.ORIGEN_SERVICIO, 1))
         AND NVL (TXN.DESTINO_SERVICIO, 1) = DECODE (NVL (CNF.DESTINO_SERVICIO, 1),'TODOS', NVL (TXN.DESTINO_SERVICIO, 1),NVL (CNF.DESTINO_SERVICIO, 1))
         AND NVL (TXN.SERVICIO, 1) = DECODE (NVL (CNF.SERVICIO, 1),'TODOS', NVL (TXN.SERVICIO, 1),NVL (CNF.SERVICIO, 1))
         AND NVL (TXN.CONCEPTO_MODALIDAD, 1) = NVL (CNF.CONCEPTO_MODALIDAD, 1)
         AND NVL (TXN.FORMA_PAGO, 1) = DECODE (NVL (CNF.FORMA_PAGO, 1),'TODOS', NVL (TXN.FORMA_PAGO, 1),NVL (CNF.FORMA_PAGO, 1))
         AND NVL (TXN.ADICIONAL1, 1) = NVL (CNF.ADICIONAL1, 1)
         AND NVL (TXN.ADICIONAL3, 1) = NVL (CNF.ADICIONAL3, 1)
         AND NVL (TXN.ADICIONAL4, 1) = NVL (CNF.ADICIONAL4, 1)
         AND NVL (TXN.ADICIONAL5, 1) = NVL (CNF.ADICIONAL5, 1)
         AND NVL (TXN.ADICIONAL6, 1) = NVL (CNF.ADICIONAL6, 1)
         AND NVL (TXN.ADICIONAL7, 1) = NVL (CNF.ADICIONAL7, 1)
         AND NVL (TXN.ADICIONAL8, 1) = NVL (CNF.ADICIONAL8, 1)
         AND NVL (TXN.ADICIONAL9, 1) = NVL (CNF.ADICIONAL9, 1)
         AND NVL (TXN.ADICIONAL10, 1) = NVL (CNF.ADICIONAL10, 1)
		 AND CNF.METODO_RECIBO IS NOT NULL
WHERE CNF.CONCILIACION = 'SI'
) RPC
    LEFT JOIN XXER_AR_CONCILIACION_TBL TCO ON RPC.REFERENCE_PAYMENT = TCO.REFERENCE_PAYMENT AND RPC.METODO_RECIBO = TCO.METODO_RECIBO
WHERE NVL(trim(TCO.STATUS),'NC') != 'C' 
--AND TRUNC(RPC.FECHA_MOVIMIENTO)>= TRUNC(TO_DATE('29/04/2021','DD/MM/YYYY'))
and RPC.REFERENCE_PAYMENT in ('11052021CAPUT','05052021CAPUT','08052021CAPUT','09052021CAPUT','18052021CAPSETEXT','26052021CAPSETEXT','17052019WTCT','AFIL.-007273370-03052021','AFIL.-009270083-03052021','AFIL.-009270083-04052021','17052021WTCT');
