--------------------------------------------------------
-- Archivo creado  - martes-enero-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXER_COMPLEMENTS_LINES_AP_TBL
--------------------------------------------------------

  CREATE TABLE "PXERINTUSER"."XXER_COMPLEMENTS_LINES_AP_TBL" 
   (	"DR_ID" NUMBER, 
	"PAYMENT_ID" NUMBER, 
	"INVOICE_ID" VARCHAR2(50 CHAR), 
	"STATUS" VARCHAR2(150 CHAR), 
	"STATUS_DESC" VARCHAR2(3000 CHAR), 
	"FOLIO_DR_XML" VARCHAR2(50 CHAR), 
	"SERIE_DR_XML" VARCHAR2(50 CHAR), 
	"UUID_DR_XML" VARCHAR2(50 CHAR), 
	"IMP_SALDO_ANT_DR_XML" VARCHAR2(50 CHAR), 
	"IMP_PAGO_DR_XML" VARCHAR2(50 CHAR), 
	"IMP_SALDO_INSOLUTO_DR_XML" VARCHAR2(50 CHAR), 
	"MONEDA_DR_XML" VARCHAR2(50 CHAR), 
	"METODO_PAGO_DR_XML" VARCHAR2(50 CHAR), 
	"TIPO_CAMBIO_DR_XML" VARCHAR2(50 CHAR), 
	"FORMA_PAGO_DR_XML" VARCHAR2(50 CHAR), 
	"FECHA_DR_XML" VARCHAR2(50 CHAR), 
	"ATTRIBUTE1" VARCHAR2(150 CHAR), 
	"ATTRIBUTE2" VARCHAR2(150 CHAR), 
	"ATTRIBUTE3" VARCHAR2(150 CHAR), 
	"ATTRIBUTE4" VARCHAR2(150 CHAR), 
	"ATTRIBUTE5" VARCHAR2(150 CHAR), 
	"CREATED_BY" VARCHAR2(150 CHAR), 
	"CREATION_DATE" TIMESTAMP (6) DEFAULT (sysdate), 
	"LAST_UPDATED_BY" VARCHAR2(150 CHAR), 
	"LAST_UPDATE_DATE" TIMESTAMP (6), 
	"OBJECT_VERSION_NUMBER" NUMBER(9,0), 
	"OBJETO_IMP_DR_XML" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0023862
--------------------------------------------------------

  CREATE UNIQUE INDEX "PXERINTUSER"."SYS_C0023862" ON "PXERINTUSER"."XXER_COMPLEMENTS_LINES_AP_TBL" ("DR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;
--------------------------------------------------------
--  Constraints for Table XXER_COMPLEMENTS_LINES_AP_TBL
--------------------------------------------------------

  ALTER TABLE "PXERINTUSER"."XXER_COMPLEMENTS_LINES_AP_TBL" MODIFY ("DR_ID" NOT NULL ENABLE);
  ALTER TABLE "PXERINTUSER"."XXER_COMPLEMENTS_LINES_AP_TBL" ADD PRIMARY KEY ("DR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS"  ENABLE;
