--------------------------------------------------------
-- Archivo creado  - martes-enero-23-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXER_AP_PAYMENTS_APOLO
--------------------------------------------------------

  CREATE TABLE "PXERINTUSER"."XXER_AP_PAYMENTS_APOLO" 
   (	"ID_PAGO" VARCHAR2(50 BYTE), 
	"FECHA_MENSAJE" DATE, 
	"MENSAJE" NUMBER, 
	"PAYMENT_STATUS" VARCHAR2(50 BYTE), 
	"VALIDACION_MANUAL" VARCHAR2(2000 BYTE), 
	"STATUS" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;
