25 a 30 min un mes imedio 1518 pagos 


SELECT DISTINCT 
          inv.REFERENCE_PAYMENT,
          inv.METODO_RECIBO,
          inv.TOLERANCIA,     
          inv.RECEIPT_METHOD_ID,
          inv.ORGANIZATION_ID,
          inv.FRECUENCIA,
          inv.RFC_ORIGEN
     FROM XXER_AR_INVOICES_CONCILIACION_V inv


--,'AFIL.-007273370','AFIL.-009270083'
select count(*) from XXER_AR_INVOICES_CONCILIACION_V
where
"REFERENCE_PAYMENT"='AFIL.-007273370-02052021'

select DISTINCT "NUMERO_DOCUMENTO",
"TOTAL","METODO_RECIBO",
"REFERENCE_PAYMENT" from XXER_AR_INVOICES_CONCILIACION_V
where
"REFERENCE_PAYMENT"='AFIL.-007273370-02052021'


AMEXCO SE 9350021565

select * from XXER_AR_CONCILIACION_TBL
select count(*) from XXER_AR_CONCILIACION_TBL

select * from XXER_CNF_INTERFASE_INGRESOS_AR
DELETE FROM XXER_AR_CONCILIACION_TBL;
commit;