create or replace TYPE XXER_AR_GETDATA_INVOICES_TYP
AS
OBJECT (
  RFC VARCHAR2(20),
  Business_Unit_Name VARCHAR2(250),
    Transaction_Batch_Source_Name VARCHAR2(250),
    Transaction_Type_Name VARCHAR2(50),
    Payment_Terms VARCHAR2(50),
    Transaction_Date DATE,
    Accounting_Date DATE,
    Transaction_Number VARCHAR2(50),
    Original_System_Bill_to_Customer_Reference VARCHAR2(250),
    Original_System_Bill_to_Customer_Address_Reference VARCHAR2(100),
    Original_System_Bill_to_Customer_Contact_Reference VARCHAR2(100),
    Original_System_Ship_to_Customer_Reference VARCHAR2(100),
    Original_System_Ship_to_Customer_Address_Reference VARCHAR2(100),
    Original_System_Ship_to_Customer_Contact_Reference VARCHAR2(100),
    Original_System_Ship_to_Customer_Account_Reference VARCHAR2(100),
    Original_System_Ship_to_Customer_Account_Address_Reference VARCHAR2(100),
    Original_System_Ship_to_Customer_Account_Contact_Reference VARCHAR2(100),
    Original_System_Sold_to_Customer_Reference VARCHAR2(100),
    Original_System_Sold_to_Customer_Account_Reference VARCHAR2(100),
    Bill_to_Customer_Account_Number NUMBER,
    Bill_to_Customer_Site_Number NUMBER,
    Bill_to_Contact_Party_Number VARCHAR2(100),
    Ship_to_Customer_Account_Number VARCHAR2(100),
    Ship_to_Customer_Site_Number VARCHAR2(100),
    Ship_to_Contact_Party_Number VARCHAR2(100),
    Sold_to_Customer_Account_Number VARCHAR2(100),
    Transaction_Line_Type VARCHAR2(100),
    Transaction_Line_Description VARCHAR2(250),
    Currency_Code VARCHAR2(10),
    Currency_Conversion_Type VARCHAR2(50),
    Currency_Conversion_Date DATE,
    Currency_Conversion_Rate NUMBER,
    Transaction_Line_Amount NUMBER,
    Transaction_Line_Quantity NUMBER,
    Customer_Ordered_Quantity VARCHAR2(100),
    Unit_Selling_Price NUMBER,
    Unit_Standard_Price NUMBER,
    Line_Transactions_Flexfield_Context VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_1 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_2 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_3 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_4 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_5 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_6 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_7 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_8 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_9 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_10 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_11 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_12 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_13 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_14 VARCHAR2(100),
    Line_Transactions_Flexfield_Segment_15 VARCHAR2(100),
    Primary_Salesperson_Number NUMBER,
    Tax_Classification_Code VARCHAR2(50),
    Legal_Entity_Identifier VARCHAR2(100),
    Accounted_Amount_in_Ledger_Currency VARCHAR2(100),
    Sales_Order_Number VARCHAR2(100),
    Sales_Order_Date VARCHAR2(100),
    Actual_Ship_Date VARCHAR2(100),
    Warehouse_Code VARCHAR2(100),
    Unit_of_Measure_Code VARCHAR2(50),
    Unit_of_Measure_Name VARCHAR2(50),
    Invoicing_Rule_Name VARCHAR2(100),
    Revenue_Scheduling_Rule_Name VARCHAR2(100),
    Number_of_Revenue_Periods VARCHAR2(100),
    Revenue_Scheduling_Rule_Start_Date VARCHAR2(100),
    Revenue_Scheduling_Rule_End_Date VARCHAR2(100),
    Reason_Code_Meaning VARCHAR2(100),
    Last_Period_to_Credit VARCHAR2(100),
    Transaction_Business_Category_Code VARCHAR2(100),
    Product_Fiscal_Classification_Code VARCHAR2(100),
    Product_Category_Code VARCHAR2(100),
    Product_Type VARCHAR2(100),
    Line_Intended_Use_Code VARCHAR2(100),
    Assessable_Value VARCHAR2(100),
    Document_Sub_Type VARCHAR2(100),
    Default_Taxation_Country VARCHAR2(100),
    User_Defined_Fiscal_Classification VARCHAR2(100),
    Tax_Invoice_Number VARCHAR2(100),
    Tax_Invoice_Date VARCHAR2(100),
    Tax_Regime_Code VARCHAR2(100),
    Tax VARCHAR2(100),
    Tax_Status_Code VARCHAR2(100),
    Tax_Rate_Code VARCHAR2(100),
    Tax_Jurisdiction_Code VARCHAR2(100),
    First_Party_Registration_Number VARCHAR2(100),
    Third_Party_Registration_Number VARCHAR2(100),
    Final_Discharge_Location VARCHAR2(100),
    Taxable_Amount VARCHAR2(100),
    Taxable_Flag VARCHAR2(100),
    Tax_Exemption_Flag VARCHAR2(100),
    Tax_Exemption_Reason_Code VARCHAR2(100),
    Tax_Exemption_Reason_Code_Meaning VARCHAR2(100),
    Tax_Exemption_Certificate_Number VARCHAR2(100),
    Line_Amount_Includes_Tax_Flag VARCHAR2(100),
    Tax_Precedence VARCHAR2(100),
    Credit_Method_To_Be_Used_For_Lines_With_Revenue_Scheduling_Rules VARCHAR2(100),
    Credit_Method_To_Be_Used_For_Transactions_With_Split_Payment_Terms VARCHAR2(100),
    Reason_Code VARCHAR2(100),
    Tax_Rate VARCHAR2(100),
    FOB_Point VARCHAR2(100),
    Carrier VARCHAR2(100),
    Shipping_Reference VARCHAR2(100),
    Sales_Order_Line_Number VARCHAR2(100),
    Sales_Order_Source VARCHAR2(100),
    Sales_Order_Revision_Number VARCHAR2(100),
    Purchase_Order_Number VARCHAR2(100),
    Purchase_Order_Revision_Number VARCHAR2(100),
    Purchase_Order_Date VARCHAR2(100),
    Agreement_Name VARCHAR2(100),
    Memo_Line_Name VARCHAR2(250),
    Document_Number VARCHAR2(100),
    Original_System_Batch_Name VARCHAR2(100),
    Link_to_Transactions_Flexfield_Context VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_1 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_2 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_3 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_4 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_5 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_6 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_7 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_8 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_9 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_10 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_11 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_12 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_13 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_14 VARCHAR2(100),
    Link_to_Transactions_Flexfield_Segment_15 VARCHAR2(100),
    Reference_Transactions_Flexfield_Context VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_1 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_2 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_3 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_4 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_5 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_6 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_7 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_8 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_9 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_10 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_11 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_12 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_13 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_14 VARCHAR2(100),
    Reference_Transactions_Flexfield_Segment_15 VARCHAR2(100),
    Link_To_Parent_Line_Context VARCHAR2(100),
    Link_To_Parent_Line_Segment_1 VARCHAR2(100),
    Link_To_Parent_Line_Segment_2 VARCHAR2(100),
    Link_To_Parent_Line_Segment_3 VARCHAR2(100),
    Link_To_Parent_Line_Segment_4 VARCHAR2(100),
    Link_To_Parent_Line_Segment_5 VARCHAR2(100),
    Link_To_Parent_Line_Segment_6 VARCHAR2(100),
    Link_To_Parent_Line_Segment_7 VARCHAR2(100),
    Link_To_Parent_Line_Segment_8 VARCHAR2(100),
    Link_To_Parent_Line_Segment_9 VARCHAR2(100),
    Link_To_Parent_Line_Segment_10 VARCHAR2(100),
    Link_To_Parent_Line_Segment_11 VARCHAR2(100),
    Link_To_Parent_Line_Segment_12 VARCHAR2(100),
    Link_To_Parent_Line_Segment_13 VARCHAR2(100),
    Link_To_Parent_Line_Segment_14 VARCHAR2(100),
    Link_To_Parent_Line_Segment_15 VARCHAR2(100),
    Receipt_Method_Name VARCHAR2(100),
    Printing_Option VARCHAR2(100),
    Related_Batch_Source_Name VARCHAR2(100),
    Related_Transaction_Number VARCHAR2(100),
    Inventory_Item_Number VARCHAR2(100),
    Inventory_Item_Segment_2 VARCHAR2(100),
    Inventory_Item_Segment_3 VARCHAR2(100),
    Inventory_Item_Segment_4 VARCHAR2(100),
    Inventory_Item_Segment_5 VARCHAR2(100),
    Inventory_Item_Segment_6 VARCHAR2(100),
    Inventory_Item_Segment_7 VARCHAR2(100),
    Inventory_Item_Segment_8 VARCHAR2(100),
    Inventory_Item_Segment_9 VARCHAR2(100),
    Inventory_Item_Segment_10 VARCHAR2(100),
    Inventory_Item_Segment_11 VARCHAR2(100),
    Inventory_Item_Segment_12 VARCHAR2(100),
    Inventory_Item_Segment_13 VARCHAR2(100),
    Inventory_Item_Segment_14 VARCHAR2(100),
    Inventory_Item_Segment_15 VARCHAR2(100),
    Inventory_Item_Segment_16 VARCHAR2(100),
    Inventory_Item_Segment_17 VARCHAR2(100),
    Inventory_Item_Segment_18 VARCHAR2(100),
    Inventory_Item_Segment_19 VARCHAR2(100),
    Inventory_Item_Segment_20 VARCHAR2(100),
    Bill_To_Customer_Bank_Account_Name VARCHAR2(100),
    Reset_Transaction_Date_Flag VARCHAR2(100),
    Payment_Server_Order_Number VARCHAR2(100),
    Last_Transaction_on_Debit_Authorization VARCHAR2(100),
    Approval_Code VARCHAR2(100),
    Address_Verification_Code VARCHAR2(100),
    Transaction_Line_Translated_Description VARCHAR2(100),
    Consolidated_Billing_Number VARCHAR2(100),
    Promised_Commitment_Amount VARCHAR2(100),
    Payment_Set_Identifier VARCHAR2(100),
    Original_Accounting_Date VARCHAR2(100),
    Invoiced_Line_Accounting_Level VARCHAR2(100),
    Override_AutoAccounting_Flag VARCHAR2(100),
    Historical_Flag VARCHAR2(100),
    Deferral_Exclusion_Flag VARCHAR2(100),
    Payment_Attributes VARCHAR2(100),
    Invoice_Billing_Date VARCHAR2(100),
    Invoice_Lines_Flexfield_Context VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_1 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_2 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_3 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_4 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_5 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_6 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_7 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_8 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_9 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_10 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_11 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_12 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_13 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_14 VARCHAR2(100),
    Invoice_Lines_Flexfield_Segment_15 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Context VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_1 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_2 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_3 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_4 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_5 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_6 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_7 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_8 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_9 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_10 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_11 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_12 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_13 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_14 VARCHAR2(100),
    Invoice_Transactions_Flexfield_Segment_15 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Context VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_1 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_2 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_3 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_4 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_5 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_6 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_7 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_8 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_9 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_10 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_11 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_12 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_13 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_14 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_15 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_16 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_17 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_18 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_19 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_20 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_21 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_22 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_23 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_24 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_25 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_26 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_27 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_28 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_29 VARCHAR2(100),
    Receivables_Transaction_Region_Information_Flexfield_Segment_30 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Attribute_Category VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_1 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_2 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_3 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_4 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_5 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_6 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_7 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_8 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_9 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_10 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_11 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_12 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_13 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_14 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_15 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_16 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_17 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_18 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_19 VARCHAR2(100),
    Line_Global_Descriptive_Flexfield_Segment_20 VARCHAR2(100),
    Comments VARCHAR2(250),
    Notes_from_Source  VARCHAR2(100),
    Enforce_Chronological_Document_Sequencing  VARCHAR2(100)
    )
;

create or replace TYPE XXER_AR_PARAMS_TO_UPD_TYPE AS OBJECT 
(
       BATCH_ID            VARCHAR2 (50 CHAR) ,
       TRANSACTION_NUMBER  VARCHAR2 (100 CHAR) 
)

create or replace TYPE XXER_AR_RECEIPT_INVOICE_TTYPE 
AS TABLE OF XXER_AR_RECEIPT_INVOICE_TYPE;

create or replace TYPE XXER_AR_RECEIPT_INVOICE_TYPE AS OBJECT 
(
       RFC                VARCHAR2 (20 CHAR) ,
       PARTY_NAME         VARCHAR2 (360 CHAR) ,
       PARTY_NUMBER       VARCHAR2 (30 CHAR) ,  /*se cambia de int a string*/
       PARTY_ID           NUMBER   (18) ,
       ACCOUNT_NUMBER     VARCHAR2 (30 CHAR) , /*se cambia de int a string*/
       CUST_ACCOUNT_ID    NUMBER   (18) ,
       CUST_ACCT_SITE_ID  NUMBER   (18) ,
       PARTY_SITE_NUMBER  VARCHAR2 (30 CHAR) , /*se cambia de int a string*/
       SITE_USE_ID        NUMBER   (18) ,
       SITE_USE_CODE      VARCHAR2 (30 CHAR) ,
       PRIMARY_FLAG       VARCHAR2 (1 CHAR) ,
       LOCATION           VARCHAR2 (150 CHAR) , /*se cambia de int a string*/
       LOCATION_ID        NUMBER   (18),
       PAYMENT_TERMS      VARCHAR2 (500 CHAR),
       ORG_ID             NUMBER   (25),
       BU_NAME            VARCHAR2 (150 CHAR)
 );
 
 create or replace TYPE XXER_COMPLEMENT_UPD_UUID_TTYPE 
AS TABLE OF XXER_COMPLEMENT_UPD_UUID_TYPE;

--XXER_TBL_PUENTE_AUX

create or replace TYPE XXER_COMPLEMENT_UPD_UUID_TYPE AS OBJECT 
(
       TRX_NUMBER  VARCHAR2 (50 CHAR) ,
       ORG_ID  NUMBER,
       UUID VARCHAR(150 CHAR))
;

create or replace TYPE XXER_ERROR_MESSAGES_INV_TTYPE
IS
  TABLE OF XXER_ERROR_MESSAGES_INV_TYPE
;

create or replace TYPE XXER_ERROR_MESSAGES_INV_TYPE AS OBJECT 
( 
       MESSAGE           VARCHAR2 (500 CHAR),
       DATA_VALUE        VARCHAR2 (250 CHAR)
       
);

create or replace TYPE XXER_INVOICE_LOAD_STATUS_TTYPE
IS
  TABLE OF XXER_INVOICE_LOAD_STATUS_TYPE
;

create or replace TYPE XXER_INVOICE_LOAD_STATUS_TYPE AS OBJECT 
(
       STATUS                VARCHAR2 (20 CHAR) ,
       TRX_NUMBER         VARCHAR2 (100 CHAR) ,
       MESSAGE_TEXT           VARCHAR2 (500 CHAR) ,
       INVALID_VALUE     VARCHAR2 (500 CHAR)
    
       
)

create or replace TYPE XXER_INVOICES_TO_UPDATE_TTYPE 
AS TABLE OF XXER_INVOICES_TO_UPDATE_TYPE
;

create or replace TYPE XXER_INVOICES_TO_UPDATE_TYPE AS OBJECT 
(
       TRX_NUMBER VARCHAR2 (100 CHAR),
       STATUS VARCHAR2(10)           
);