<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="BpelConciliationBankAmex" targetNamespace="http://soa.estrellaroja.com.mx/ConciliationEnt/BpelConciliationBankAmex" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://soa.estrellaroja.com.mx/ConciliationEnt/BpelConciliationBankAmex" xmlns:ns1="http://soa.estrellaroja.com.mx/ConciliationEnt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://soa.estrellaroja.com.mx/ConciliationEnt" schemaLocation="oramds:/apps/SOA/ConciliationEnt/ConciliationEnt.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="BpelConciliationBankAmexRequestMessage">
      <wsdl:part name="payload" element="ns1:ConciliationBankAmexRq"/>
   </wsdl:message>
   <wsdl:portType name="BpelConciliationBankAmex">
      <wsdl:operation name="process">
         <wsdl:input message="client:BpelConciliationBankAmexRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="BpelConciliationBankAmex">
      <plnk:role name="BpelConciliationBankAmexProvider" portType="client:BpelConciliationBankAmex"/>
   </plnk:partnerLinkType>
</wsdl:definitions>
