CREATE TABLE "XXER_TBL_PUENTE_AUXILIAR" 
   (	"TABLA_PUENTE_AUXILIAR_ID" NUMBER, 
	"TABLA_PUENTE_LINEA_ID" NUMBER, 
	"FOLIO_FACTURA_FISCAL" VARCHAR2(150 BYTE), 
	"RFC" VARCHAR2(100 BYTE), 
	"UUID" VARCHAR2(100 BYTE), 
	"SERIE" VARCHAR2(100 BYTE), 
	"SUBTOTAL" NUMBER(10,2), 
	"IVA" NUMBER(10,2), 
	"IVA_RETENIDO" NUMBER(10,2), 
	"RET_5MILLAR" NUMBER(10,2), 
	"DESCUENTO" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"FOLIO_FACTURA_AR" VARCHAR2(100 BYTE), 
	"ADICIONAL1" VARCHAR2(280 BYTE), 
	"ADICIONAL2" VARCHAR2(280 BYTE), 
	"ADICIONAL3" VARCHAR2(280 BYTE), 
	"ADICIONAL4" VARCHAR2(280 BYTE), 
	"ADICIONAL5" VARCHAR2(2028 BYTE), 
	"ADICIONAL6" VARCHAR2(280 BYTE), 
	"ADICIONAL7" VARCHAR2(280 BYTE), 
	"ADICIONAL8" VARCHAR2(280 BYTE), 
	"ADICIONAL9" VARCHAR2(280 BYTE), 
	"ADICIONAL10" VARCHAR2(280 BYTE), 
	"CREADO_POR" NUMBER, 
	"FECHA_CREACION" DATE, 
	"ULTIMA_ACTUALIZACION_POR" NUMBER, 
	"ULTIMA_FECHA_ACTUALIZACION" DATE
   ) ;
--------------------------------------------------------
--  DDL for Index XXER_TBL_PUENTE_AUXILIAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXER_TBL_PUENTE_AUXILIAR_PK" ON "XXER_TBL_PUENTE_AUXILIAR" ("TABLA_PUENTE_AUXILIAR_ID");
--------------------------------------------------------
--  Constraints for Table XXER_TBL_PUENTE_AUXILIAR
--------------------------------------------------------

  ALTER TABLE "XXER_TBL_PUENTE_AUXILIAR" MODIFY ("TABLA_PUENTE_AUXILIAR_ID" NOT NULL ENABLE);
  ALTER TABLE "XXER_TBL_PUENTE_AUXILIAR" MODIFY ("CREADO_POR" NOT NULL ENABLE);
  ALTER TABLE "XXER_TBL_PUENTE_AUXILIAR" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);
  ALTER TABLE "XXER_TBL_PUENTE_AUXILIAR" MODIFY ("ULTIMA_ACTUALIZACION_POR" NOT NULL ENABLE);
  ALTER TABLE "XXER_TBL_PUENTE_AUXILIAR" MODIFY ("ULTIMA_FECHA_ACTUALIZACION" NOT NULL ENABLE);
  ALTER TABLE "XXER_TBL_PUENTE_AUXILIAR" ADD CONSTRAINT "XXER_TBL_PUENTE_AUXILIAR_PK" PRIMARY KEY ("TABLA_PUENTE_AUXILIAR_ID");
