--------------------------------------------------------
-- Archivo creado  - jueves-marzo-07-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXER_TBL_PUENTE_HEADER
--------------------------------------------------------

  CREATE TABLE "XXER_TBL_PUENTE_HEADER" 
   (	"TABLA_PUENTE_ID" NUMBER, 
	"SISTEMA_ORIGEN" VARCHAR2(100 BYTE), 
	"TIPO_DOCUMENTO" VARCHAR2(50 BYTE), 
	"TIPO_MOVIMIENTO" VARCHAR2(50 BYTE), 
	"UNIDAD_NEGOCIO_ORIGEN" VARCHAR2(240 BYTE), 
	"NOMBRE_FISCAL_ORIGEN" VARCHAR2(240 BYTE), 
	"EMPRESA_ORIGEN" VARCHAR2(240 BYTE), 
	"RFC_ORIGEN" VARCHAR2(25 BYTE), 
	"UNIDAD_NEGOCIO_DESTINO" VARCHAR2(240 BYTE), 
	"NOMBRE_FISCAL_DESTINO" VARCHAR2(240 BYTE), 
	"EMPRESA_DESTINO" VARCHAR2(240 BYTE), 
	"RFC_DESTINO" VARCHAR2(25 BYTE), 
	"SUCURSAL_VENTA" VARCHAR2(240 BYTE), 
	"NUMERO_DOCUMENTO" VARCHAR2(25 BYTE), 
	"FECHA_MOVIMIENTO" DATE, 
	"REFERENCIA_APLICACION" VARCHAR2(1760 BYTE), 
	"ADICIONAL1" VARCHAR2(80 BYTE), 
	"ADICIONAL2" VARCHAR2(80 BYTE), 
	"ADICIONAL3" VARCHAR2(80 BYTE), 
	"ADICIONAL4" VARCHAR2(80 BYTE), 
	"ADICIONAL5" VARCHAR2(80 BYTE), 
	"ADICIONAL6" VARCHAR2(80 BYTE), 
	"ADICIONAL7" VARCHAR2(80 BYTE), 
	"ADICIONAL8" VARCHAR2(80 BYTE), 
	"ADICIONAL9" VARCHAR2(80 BYTE), 
	"ADICIONAL10" VARCHAR2(80 BYTE), 
	"ESTATUS" VARCHAR2(1 BYTE), 
	"DETALLE_ERROR" VARCHAR2(2000 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"ESTATUSAP" VARCHAR2(1 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Trigger AUDIT_TRIGGER_TPH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUDIT_TRIGGER_TPH" BEFORE INSERT OR UPDATE
  ON XXER_TBL_PUENTE_HEADER FOR EACH ROW
BEGIN
  IF INSERTING THEN
  :new.CREATION_DATE:=sysdate;
  :new.CREATED_BY:=APEX_UTIL.GET_CURRENT_USER_ID;
  ELSIF UPDATING THEN
  :new.LAST_UPDATE_DATE:=sysdate;
  :new.LAST_UPDATED_BY:=APEX_UTIL.GET_CURRENT_USER_ID;
  END IF;
END;
/
ALTER TRIGGER "AUDIT_TRIGGER_TPH" ENABLE;
--------------------------------------------------------
--  Constraints for Table XXER_TBL_PUENTE_HEADER
--------------------------------------------------------

  ALTER TABLE "XXER_TBL_PUENTE_HEADER" MODIFY ("TABLA_PUENTE_ID" NOT NULL ENABLE);
