declare
   
   

   COUNTER5        NUMBER ;
   COUNTER6        NUMBER ;
   COUNTER7        NUMBER ;
   COUNTER8        NUMBER ;
   COUNTER9        NUMBER ;
   COUNTER10       NUMBER ;

   
   

BEGIN






COUNTER5:=0;
COUNTER6:=0;
COUNTER7:=0;
COUNTER8:=0;
COUNTER9:=0;
COUNTER10:=0;




          INSERT INTO XERINTUSER.XXER_TBL_PUENTE_AUXILIAR_2
          (SELECT A2.* 
          FROM XXER.XXER_TBL_PUENTE_AUXILIAR_2@SUMASII_LINK.ESTRELLAROJA.COM.MX A2,
          XXER.XXER_TBL_PUENTE_HEADER@SUMASII_LINK.ESTRELLAROJA.COM.MX H1 
          WHERE A2.TABLA_PUENTE_HEADER_ID = H1.TABLA_PUENTE_ID
          --AND TRUNC(H1.FECHA_MOVIMIENTO)= TRUNC(SYSDATE-7)
           AND numero_documento  in ('301121CEDISTDDF')
          AND A2.tabla_puente_header_id not in (
              select A2.tabla_puente_header_id
              from XERINTUSER.XXER_TBL_PUENTE_AUXILIAR_2 a2
                   ,XXER_TBL_PUENTE_HEADER h1 
              where A2.tabla_puente_header_id = h1.tabla_puente_id
              --AND TRUNC(h1.FECHA_MOVIMIENTO)= TRUNC(SYSDATE-7)
              AND H1.SISTEMA_ORIGEN != 'DLIVER')
          );
          
           COMMIT;
           
           
             INSERT INTO XERINTUSER.XXER_TBL_PUENTE_LINES 
             (
             SELECT L1.* 
             FROM XXER.XXER_TBL_PUENTE_LINES@SUMASII_LINK.ESTRELLAROJA.COM.MX L1,
             XXER.XXER_TBL_PUENTE_HEADER@SUMASII_LINK.ESTRELLAROJA.COM.MX H1 
             WHERE L1.TABLA_PUENTE_ID = H1.TABLA_PUENTE_ID
             --AND TRUNC(H1.FECHA_MOVIMIENTO) = TRUNC(SYSDATE-7)
           AND numero_documento  in ('301121CEDISTDDF')
             AND H1.SISTEMA_ORIGEN != 'DLIVER'
             );
           
           COMMIT;
  
           
           INSERT INTO XERINTUSER.XXER_TBL_PUENTE_HEADER (TABLA_PUENTE_ID,SISTEMA_ORIGEN,TIPO_DOCUMENTO,TIPO_MOVIMIENTO,UNIDAD_NEGOCIO_ORIGEN,NOMBRE_FISCAL_ORIGEN,EMPRESA_ORIGEN,RFC_ORIGEN,UNIDAD_NEGOCIO_DESTINO,NOMBRE_FISCAL_DESTINO,EMPRESA_DESTINO,RFC_DESTINO,SUCURSAL_VENTA,NUMERO_DOCUMENTO,FECHA_MOVIMIENTO,REFERENCIA_APLICACION,CREATION_DATE,CREATED_BY,LAST_UPDATE_DATE,LAST_UPDATED_BY,LAST_UPDATE_LOGIN)   
           (
           SELECT H1.TABLA_PUENTE_ID,H1.SISTEMA_ORIGEN,H1.TIPO_DOCUMENTO,H1.TIPO_MOVIMIENTO,H1.UNIDAD_NEGOCIO_ORIGEN,H1.NOMBRE_FISCAL_ORIGEN,H1.EMPRESA_ORIGEN,H1.RFC_ORIGEN,H1.UNIDAD_NEGOCIO_DESTINO,H1.NOMBRE_FISCAL_DESTINO,H1.EMPRESA_DESTINO,H1.RFC_DESTINO,H1.SUCURSAL_VENTA,H1.NUMERO_DOCUMENTO,H1.FECHA_MOVIMIENTO,
                   H1.REFERENCIA_APLICACION,H1.CREATION_DATE,H1.CREATED_BY,H1.LAST_UPDATE_DATE,H1.LAST_UPDATED_BY,H1.LAST_UPDATE_LOGIN   
           FROM XXER.XXER_TBL_PUENTE_HEADER@SUMASII_LINK.ESTRELLAROJA.COM.MX H1 
           WHERE 
		   1=1
		   --AND TRUNC(H1.FECHA_MOVIMIENTO)  = TRUNC(SYSDATE-7)
           
           AND numero_documento  in ( '301121CEDISTDDF')
          --AND numero_documento  in ( '301121CDSTDCF')301121CPUTDCF,301121CEDISTDDF
           --AND numero_documento  in ('301121TPOTDDF')
           --AND numero_documento  in ('301121APOEFEF','301121APOTDDF')
		   --AND numero_documento  in ('301121APOEFEF','301121APOTDDF','30112115TTPIRF')
           AND H1.SISTEMA_ORIGEN != 'DLIVER'
           );

           
           COMMIT;
           
           
              
   
END ;