WITH LINES AS (
    SELECT
        RCTL2.CUSTOMER_TRX_ID ,
        RCTL2.LINE_NUMBER,
        RCTL2.DESCRIPTION,
        RCTL2.CUSTOMER_TRX_LINE_ID,
        NVL(RCTL2.QUANTITY_INVOICED,0)+ ABS(NVL(RCTL2.QUANTITY_CREDITED,0)) as QUANTITY_INVOICED,
        RCTL2.UNIT_SELLING_PRICE,
        RCTL2.LINE_TYPE,
        RCTL2.EXTENDED_AMOUNT,
        RCTL2.REVENUE_AMOUNT,
		RCTL2.UOM_CODE,
        RCTL.LINK_TO_CUST_TRX_LINE_ID,
        RCTL.TAX_RATE,
        RCTL.VAT_TAX_ID,
        RCTL2.TAX_EXEMPT_FLAG,
        RCTL.TAXABLE_AMOUNT,
        RCTL.TAX_LINE_ID,
        RCTL2.TAX_RECOVERABLE,
        RCTL2.TAX_CLASSIFICATION_CODE,
		RCTL2.ATTRIBUTE1,
		RCTL2.MEMO_LINE_SEQ_ID
    FROM
        RA_CUSTOMER_TRX_LINES_ALL  RCTL
        LEFT JOIN RA_CUSTOMER_TRX_LINES_ALL  RCTL2 ON RCTL.LINK_TO_CUST_TRX_LINE_ID = RCTL2.CUSTOMER_TRX_LINE_ID
    WHERE 1=1
         --AND RCTL2.CUSTOMER_TRX_ID =RCTL2.CUSTOMER_TRX_ID 
		  --AND RCTL2.CUSTOMER_TRX_ID IN ( 300000062196100, 300000062622184, 300000062622211,300000062196116 )
    UNION ALL
    SELECT
        RCTL2.CUSTOMER_TRX_ID,
        RCTL2.LINE_NUMBER,
        RCTL2.DESCRIPTION,
        RCTL2.CUSTOMER_TRX_LINE_ID,
        NVL(RCTL2.QUANTITY_INVOICED,0)+ ABS(NVL(RCTL2.QUANTITY_CREDITED,0)) as QUANTITY_INVOICED,
        RCTL2.UNIT_SELLING_PRICE,
        RCTL2.LINE_TYPE,
        RCTL2.EXTENDED_AMOUNT,
        RCTL2.REVENUE_AMOUNT,
        RCTL2.UOM_CODE,
        RCTL2.LINK_TO_CUST_TRX_LINE_ID,
        RCTL2.TAX_RATE,
        RCTL2.VAT_TAX_ID,
        RCTL2.TAX_EXEMPT_FLAG,
        RCTL2.TAXABLE_AMOUNT,
        RCTL2.TAX_LINE_ID,
        RCTL2.TAX_RECOVERABLE,
        RCTL2.TAX_CLASSIFICATION_CODE,
		RCTL2.ATTRIBUTE1,
		RCTL2.MEMO_LINE_SEQ_ID
    FROM
        RA_CUSTOMER_TRX_LINES_ALL RCTL2
    WHERE
	1=1
         --AND RCTL2.CUSTOMER_TRX_ID =RCTL2.CUSTOMER_TRX_ID --
		 --AND RCTL2.CUSTOMER_TRX_ID IN ( 300000062196100, 300000062622184, 300000062622211,300000062196116)
        AND RCTL2.LINE_TYPE = 'LINE'
        AND RCTL2.TAX_RECOVERABLE IS NULL
), TG AS (
    SELECT
        L.CUSTOMER_TRX_ID,
        ( CASE WHEN SUM(L.UNIT_SELLING_PRICE) != SUM(ABS(L.UNIT_SELLING_PRICE)) THEN'IMPUESTO COMPUESTO'
                ELSE'IMPUESTO NORMAL'END) AS TIPO_AGRUPADO
    FROM
        LINES L
    GROUP BY
        L.CUSTOMER_TRX_ID
),TDG AS (
SELECT
    L.CUSTOMER_TRX_ID,
	L.DESCRIPTION           AS "DESCRIPTION",
	L.QUANTITY_INVOICED     AS "QUANTITY",
    SUM(L.UNIT_SELLING_PRICE)  AS "UNIT_PRICE",
	L.LINE_TYPE AS "LINE_TYPE",
	SUM(L.EXTENDED_AMOUNT) AS "EXTENDED_AMOUNT",
    SUM(L.REVENUE_AMOUNT) AS "REVENUE_AMOUNT",     
	L.TAX_EXEMPT_FLAG AS "TAX_EXEMPT_FLAG",
	L.MEMO_LINE_SEQ_ID AS "MEMO_LINE_SEQ_ID",
	(LISTAGG(L.CUSTOMER_TRX_LINE_ID, ',') WITHIN GROUP(ORDER BY L.CUSTOMER_TRX_LINE_ID)) AS"CUSTOMER_TRX_LINE_ID",
	L.UOM_CODE AS "UOM_CODE",--REVISAR AGRUPACION
    (LISTAGG(L.LINE_NUMBER, '_') WITHIN GROUP(ORDER BY L.LINE_NUMBER)) AS "LINE_NUMBER",
   (LISTAGG(L.LINK_TO_CUST_TRX_LINE_ID, ',') WITHIN GROUP(ORDER BY L.LINK_TO_CUST_TRX_LINE_ID)) AS "LINK_TO_CUST_TRX_LINE_ID",
    (LISTAGG(L.TAX_RATE, ',') WITHIN GROUP(ORDER BY L.TAX_RATE)) AS "TAX_RATE",
   (LISTAGG(L.VAT_TAX_ID, ',') WITHIN GROUP(ORDER BY L.VAT_TAX_ID)) AS "VAT_TAX_ID",
   (LISTAGG(L.TAXABLE_AMOUNT, ',') WITHIN GROUP(ORDER BY L.TAXABLE_AMOUNT)) AS "TAXABLE_AMOUNT",
   (LISTAGG(L.TAX_LINE_ID, ',') WITHIN GROUP(ORDER BY L.TAX_LINE_ID))AS "TAX_LINE_ID",
   (LISTAGG(L.TAX_RECOVERABLE, ',') WITHIN GROUP(ORDER BY L.TAX_RECOVERABLE)) AS "TAX_RECOVERABLE",
   (LISTAGG(L.ATTRIBUTE1, ',') WITHIN GROUP(ORDER BY L.ATTRIBUTE1)) AS "PROPERTY_ACCOUNT",
   (LISTAGG(L.TAX_CLASSIFICATION_CODE, ',') WITHIN GROUP(ORDER BY L.TAX_CLASSIFICATION_CODE)) AS "TAX_CLASSIFICATION_CODE"
	FROM LINES L
	 INNER JOIN TG TG
	 ON TG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID  AND TG.TIPO_AGRUPADO='IMPUESTO COMPUESTO'	 
     GROUP BY 
	      L.CUSTOMER_TRX_ID,
		  L.DESCRIPTION ,
		  L.QUANTITY_INVOICED ,
    L.LINE_TYPE,	
	L.TAX_EXEMPT_FLAG,
	L.MEMO_LINE_SEQ_ID,
	L.UOM_CODE
	)
	,LINESA AS (SELECT
	TDG.CUSTOMER_TRX_ID AS "CUSTOMER_TRX_ID",
	0   AS "DISCOUNT",
	TDG."DESCRIPTION" AS "DESCRIPTION",
(SELECT MEMO.ATTRIBUTE1 FROM AR_MEMO_LINES_ALL_B MEMO WHERE  MEMO.MEMO_LINE_SEQ_ID=  TDG."MEMO_LINE_SEQ_ID" ) AS "PROD_SERV_KEY",
TDG."QUANTITY" AS "QUANTITY",
TDG."UNIT_PRICE" AS "UNIT_PRICE",
(SELECT IUM.ATTRIBUTE1 FROM INV_UNITS_OF_MEASURE_VL IUM WHERE IUM.UOM_CODE = TDG."UOM_CODE" ) AS "UNIT",
NVL(TDG."UOM_CODE",'E48')  AS "UNIT_KEY",
	TDG."EXTENDED_AMOUNT" AS "TAX_BASE",
	TDG."EXTENDED_AMOUNT" AS "AMOUNT",
    TDG."EXTENDED_AMOUNT" AS "SUBTOTAL",
	0 AS "TOTAL",
	(CASE WHEN ((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE L.TAX_RATE < 0  
              AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
			  AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%'
              GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION ) < 0 )
      THEN ABS((SELECT SUM(L.TAX_RECOVERABLE) FROM LINES L WHERE L.TAX_RATE < 0  
                AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
				AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%' 
                GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION )) 
	   ELSE 0 END) AS "RETENTION_VAT",
(CASE WHEN ((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE L.TAX_RATE < 0  
              AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
			  AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%'
              GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION ) < 0 )
      THEN ABS((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE L.TAX_RATE < 0  
                AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
				AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%'
                GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION ))/100 
	   ELSE 0 END)  AS "RETENTION_VAT_PERCENTAGE",
	            (CASE WHEN ((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE L.TAX_RATE < 0  
              AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
			  AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%'
              GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION ) < 0 )
      THEN (SELECT TO_CHAR(LISTAGG(L.TAX_CLASSIFICATION_CODE, ',') WITHIN GROUP(ORDER BY L.TAX_CLASSIFICATION_CODE)) FROM LINES L WHERE L.TAX_RATE < 0  
                AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
				AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%'
                GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION )
	   ELSE '' END)   AS "RETENCION_VAT_NAME",
	   0 AS "RETENTION_RT",
0 AS "RETENTION_RT_PERCENTAGE",
'' AS "RETENTION_RT_NAME",
(CASE WHEN ((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE L.TAX_RATE > 0  
              AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
              GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION ) > 0 )
      THEN ABS((SELECT SUM(L.TAX_RECOVERABLE) FROM LINES L WHERE L.TAX_RATE > 0  
                AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
                GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION )) 
	   ELSE 0 END) AS "VAT",
(CASE WHEN ((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE L.TAX_RATE > 0  
              AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
              GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION ) > 0 )
      THEN ABS((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE L.TAX_RATE > 0  
                AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
                GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION )) 
	   ELSE 0 END)  AS "VAT_PERCENTAGE",	   
	(CASE WHEN ((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE L.TAX_RATE > 0  
              AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
              GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION ) > 0 )
      THEN (SELECT TO_CHAR(LISTAGG(L.TAX_CLASSIFICATION_CODE, ',') WITHIN GROUP(ORDER BY L.TAX_CLASSIFICATION_CODE)) FROM LINES L WHERE L.TAX_RATE > 0  
                AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
                GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION )
	   ELSE '' END)    AS "VAT_NAME",	
0 AS"STPS",
0 AS "STPS_PERCENTAGE",
0 AS"IMP",
0 AS "IMP_PERCENTAGE",
0 AS"ST",
0 AS "ST_PERCENTAGE",
'' AS "ADDENDUM_INTERFACE_APPLY",
'' AS "ADDENDUM_INTERFACE_TYPE",
'' AS "ADDENDUM_INTERFACE_CONCEPT",
'Tasa' AS "FACTOR_TYPE",
ABS((SELECT SUM(L.TAX_RATE) FROM LINES L WHERE 1=1  
              AND TDG.CUSTOMER_TRX_ID=L.CUSTOMER_TRX_ID AND TDG."DESCRIPTION"=L.DESCRIPTION
			  and L.TAX_RATE >0
              GROUP BY L.CUSTOMER_TRX_ID,L.DESCRIPTION ))/100 AS "RATE_FEE",
(CASE WHEN TDG."TAX_CLASSIFICATION_CODE" LIKE '%IEPS%' THEN TO_CHAR('003')
      WHEN TDG."TAX_CLASSIFICATION_CODE" LIKE '%IVA%' THEN TO_CHAR('002')
      WHEN TDG."TAX_CLASSIFICATION_CODE" LIKE '%ISR%' THEN TO_CHAR('001')
	    WHEN TDG."TAX_CLASSIFICATION_CODE" LIKE '%ISR%' THEN TO_CHAR('001')
      ELSE NULL END)AS "TAX",
NVL(NULL,'02')  AS "TAXOBJECT",
	TDG."CUSTOMER_TRX_LINE_ID" AS "CUSTOMER_TRX_LINE_ID",
	TDG."LINE_NUMBER" AS "LINE_NUMBER",
	TDG."LINE_TYPE" AS "LINE_TYPE",
	TDG."EXTENDED_AMOUNT" AS "EXTENDED_AMOUNT",
    TDG."REVENUE_AMOUNT" AS "REVENUE_AMOUNT",
	TDG."LINK_TO_CUST_TRX_LINE_ID" AS "LINK_TO_CUST_TRX_LINE_ID",
	TDG."TAX_RATE" AS "TAX_RATE",
	TDG."VAT_TAX_ID" AS "VAT_TAX_ID",
	TDG."TAX_EXEMPT_FLAG" AS "TAX_EXEMPT_FLAG",	
	TDG."TAXABLE_AMOUNT" AS "TAXABLE_AMOUNT",
	TDG."TAX_LINE_ID" AS "TAX_LINE_ID",	
	TDG."TAX_RECOVERABLE" AS "TAX_RECOVERABLE",
	TDG."PROPERTY_ACCOUNT" AS "PROPERTY_ACCOUNT",
	TDG."TAX_CLASSIFICATION_CODE" AS "TAX_CLASSIFICATION_CODE"
FROM TDG
UNION ALL
SELECT
L.CUSTOMER_TRX_ID AS "CUSTOMER_TRX_ID",
    0                       AS "DISCOUNT",
    L.DESCRIPTION           AS "DESCRIPTION",
	(SELECT MEMO.ATTRIBUTE1 FROM AR_MEMO_LINES_ALL_B MEMO WHERE  MEMO.MEMO_LINE_SEQ_ID=  L.MEMO_LINE_SEQ_ID ) AS "PROD_SERV_KEY",
    L.QUANTITY_INVOICED     AS "QUANTITY",
    L.UNIT_SELLING_PRICE    AS "UNIT_PRICE",
    (SELECT IUM.ATTRIBUTE1 FROM INV_UNITS_OF_MEASURE_VL IUM WHERE IUM.UOM_CODE = L.UOM_CODE ) AS "UNIT",
	NVL(L.UOM_CODE,'E48')  AS "UNIT_KEY",
ABS(L.EXTENDED_AMOUNT) AS "TAX_BASE",
ABS(L.EXTENDED_AMOUNT) AS "AMOUNT",
ABS(L.EXTENDED_AMOUNT) AS "SUBTOTAL",
0 AS "TOTAL",
(CASE WHEN L.TAX_RATE < 0 AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%' THEN ABS(L.TAX_RECOVERABLE) ELSE 0 END) AS "RETENTION_VAT",
(CASE WHEN L.TAX_RATE < 0 AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%' THEN ABS(L.TAX_RATE)/100 ELSE 0 END)  AS "RETENTION_VAT_PERCENTAGE",
(CASE WHEN L.TAX_RATE < 0 AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%' THEN L.TAX_CLASSIFICATION_CODE ELSE '' END) AS "RETENCION_VAT_NAME",
0 AS "RETENTION_RT",
0 AS "RETENTION_RT_PERCENTAGE",
'' AS "RETENCION_RT_NAME",
(CASE WHEN L.TAX_RATE > 0 THEN ABS(L.TAX_RECOVERABLE) ELSE 0 END) AS "VAT",
(CASE WHEN L.TAX_RATE > 0 THEN ABS(L.TAX_RATE) ELSE 0 END) AS "VAT_PERCENTAGE",
(CASE WHEN L.TAX_RATE > 0 THEN L.TAX_CLASSIFICATION_CODE ELSE '' END) AS "VAT_NAME",
0 AS"STPS",
0 AS "STPS_PERCENTAGE",
0 AS"IMP",
0 AS "IMP_PERCENTAGE",
0 AS"ST",
0 AS "ST_PERCENTAGE",
'' AS "ADDENDUM_INTERFACE_APPLY",
'' AS "ADDENDUM_INTERFACE_TYPE",
'' AS "ADDENDUM_INTERFACE_CONCEPT",
  (CASE WHEN L.TAX_RECOVERABLE IS NOT NULL and UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%' THEN 'Tasa' 
  ELSE 'Exento' END) AS "FACTOR_TYPE",

(CASE WHEN L.TAX_RATE > 0 AND UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%' THEN ABS(L.TAX_RATE)/100 ELSE 0 END) AS "RATE_FEE",
(CASE WHEN L.TAX_CLASSIFICATION_CODE LIKE '%IEPS%' THEN TO_CHAR('003')
      WHEN L.TAX_CLASSIFICATION_CODE LIKE '%IVA%' THEN TO_CHAR('002')
      WHEN L.TAX_CLASSIFICATION_CODE LIKE '%ISR%' THEN TO_CHAR('001')
      ELSE NULL END)AS "TAX",
    (CASE WHEN L.TAX_RECOVERABLE IS NOT NULL and UPPER(L.TAX_CLASSIFICATION_CODE) NOT LIKE '%MILLAR%' THEN '02' ELSE '02' END) AS "TAXOBJECT",

   ''||L.CUSTOMER_TRX_LINE_ID AS "CUSTOMER_TRX_LINE_ID",
    ''||L.LINE_NUMBER AS "LINE_NUMBER",
    L.LINE_TYPE AS "LINE_TYPE",
    L.EXTENDED_AMOUNT AS "EXTENDED_AMOUNT",
    L.REVENUE_AMOUNT AS "REVENUE_AMOUNT",
    ''||L.LINK_TO_CUST_TRX_LINE_ID AS "LINK_TO_CUST_TRX_LINE_ID",
    ''||L.TAX_RATE AS "TAX_RATE",
    ''||L.VAT_TAX_ID AS "VAT_TAX_ID",
    L.TAX_EXEMPT_FLAG AS "TAX_EXEMPT_FLAG",
    ''||L.TAXABLE_AMOUNT AS "TAXABLE_AMOUNT",
    ''||L.TAX_LINE_ID AS "TAX_LINE_ID",
    ''||L.TAX_RECOVERABLE AS "TAX_RECOVERABLE",
	''||L.ATTRIBUTE1 AS "PROPERTY_ACCOUNT",
    ''||L.TAX_CLASSIFICATION_CODE AS "TAX_CLASSIFICATION_CODE"
	 FROM LINES L
INNER JOIN TG TG ON L.CUSTOMER_TRX_ID = TG.CUSTOMER_TRX_ID
                    AND TG.TIPO_AGRUPADO = 'IMPUESTO NORMAL')
		SELECT 
				CUSTOMER_TRX_ID as "CUSTOMER_TRX_ID",
				DISCOUNT as "discount",
				DESCRIPTION as "description",
				PROD_SERV_KEY as "prod_serv_key",
				QUANTITY as "quantity",
				ABS(NVL(UNIT_PRICE,0)) as "unit_price",
				UNIT as "unit",
				UNIT_KEY as "unit_key",
				ABS(NVL(TAX_BASE,0)) as "tax_base",
				ABS(NVL(AMOUNT,0)) as "amount",
				ABS(NVL(SUBTOTAL,0)) as "subtotal",
				ABS(NVL(TOTAL,0)) as "total",
				ABS(NVL(RETENTION_RT,0)) as "retention_rt",
				ABS(NVL(RETENTION_RT_PERCENTAGE,0)) as "retention_rt_percentage",
				RETENTION_RT_NAME as "retention_rt_name",
				ABS(NVL(RETENTION_VAT,0)) as "retention_vat",
				ABS(NVL(RETENTION_VAT_PERCENTAGE,0)) as "retention_vat_percentage",
				RETENCION_VAT_NAME as "retencion_vat_name",
				ABS(NVL(VAT,0)) as "vat",
				ABS(NVL(VAT_PERCENTAGE,0)) as "vat_percentage",
				VAT_NAME as "vat_name",
				STPS as "stps",
				STPS_PERCENTAGE as "stps_percentage",
				IMP as "imp",
				IMP_PERCENTAGE as "imp_percentage",
				ST as "st",
				ST_PERCENTAGE as "st_percentage",
				ADDENDUM_INTERFACE_APPLY as "addendum_interface_apply",
				ADDENDUM_INTERFACE_TYPE as "addendum_interface_type",
				ADDENDUM_INTERFACE_CONCEPT as "addendum_interface_concept",
				FACTOR_TYPE as "factor_type",
				ABS(NVL(RATE_FEE,0)) as "rate_fee",
				TAX as "tax",
				TAXOBJECT as "taxObject",
				CUSTOMER_TRX_LINE_ID as "customer_trx_line_id",
				LINE_NUMBER as "line_number",
				LINE_TYPE as "line_type",
				EXTENDED_AMOUNT as "extended_amount",
				REVENUE_AMOUNT as "revenue_amount",
				LINK_TO_CUST_TRX_LINE_ID as "link_to_cust_trx_line_id",
				TAX_RATE as "tax_rate",
				VAT_TAX_ID as "vat_tax_id",
				TAX_EXEMPT_FLAG as "tax_exempt_flag",
				TAXABLE_AMOUNT as "taxable_amount",
				TAX_LINE_ID as "tax_line_id",
				TAX_RECOVERABLE as "tax_recoverable",
				PROPERTY_ACCOUNT as "propertyAccount",
				TAX_CLASSIFICATION_CODE as "tax_classification_code"
					FROM LINESA