<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/erpInvoiceInstallmentsAP" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationApiTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:wo="http://soa.estrellaroja.com.mx/erpMaintenanceWorkOrders">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/InvoiceAP/erpInvoiceInstallmentsAP.xsd"/>
            <oracle-xsl-mapper:rootElement name="getInvoiceInstallmentsAPRs" namespace="http://soa.estrellaroja.com.mx/erpInvoiceInstallmentsAP"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationApiTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="GetInvoiceInstallmentsAPRs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationApiTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SUN NOV 26 11:43:36 CST 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:GetInvoiceInstallmentsAPRs>
         <cmn:Success/>
         <Result>
            <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:count">
               <ns0:count>
                  <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:count"/>
               </ns0:count>
            </xsl:if>
            <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:hasMore">
               <ns0:hasMore>
                  <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:hasMore"/>
               </ns0:hasMore>
            </xsl:if>
            <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:limit">
               <ns0:limit>
                  <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:limit"/>
               </ns0:limit>
            </xsl:if>
            <xsl:for-each select="/ns0:getInvoiceInstallmentsAPRs/ns0:links">
               <ns0:links>
                  <xsl:if test="ns0:href">
                     <ns0:href>
                        <xsl:value-of select="ns0:href"/>
                     </ns0:href>
                  </xsl:if>
                  <xsl:if test="ns0:kind">
                     <ns0:kind>
                        <xsl:value-of select="ns0:kind"/>
                     </ns0:kind>
                  </xsl:if>
                  <xsl:if test="ns0:name">
                     <ns0:name>
                        <xsl:value-of select="ns0:name"/>
                     </ns0:name>
                  </xsl:if>
                  <xsl:if test="ns0:properties">
                     <ns0:properties>
                        <xsl:if test="ns0:properties/ns0:changeIndicator">
                           <ns0:changeIndicator>
                              <xsl:value-of select="ns0:properties/ns0:changeIndicator"/>
                           </ns0:changeIndicator>
                        </xsl:if>
                     </ns0:properties>
                  </xsl:if>
                  <xsl:if test="ns0:rel">
                     <ns0:rel>
                        <xsl:value-of select="ns0:rel"/>
                     </ns0:rel>
                  </xsl:if>
               </ns0:links>
            </xsl:for-each>
            <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:offset">
               <ns0:offset>
                  <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:offset"/>
               </ns0:offset>
            </xsl:if>
            <items>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:BankAccount">
                  <ns0:BankAccount>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:BankAccount"/>
                  </ns0:BankAccount>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:CreatedBy">
                  <ns0:CreatedBy>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:CreatedBy"/>
                  </ns0:CreatedBy>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:CreationDate">
                  <ns0:CreationDate>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:CreationDate"/>
                  </ns0:CreationDate>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:DueDate">
                  <ns0:DueDate>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:DueDate"/>
                  </ns0:DueDate>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:ExternalBankAccountId">
                  <ns0:ExternalBankAccountId>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:ExternalBankAccountId"/>
                  </ns0:ExternalBankAccountId>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:FirstDiscountAmount">
                  <ns0:FirstDiscountAmount>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:FirstDiscountAmount"/>
                  </ns0:FirstDiscountAmount>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:FirstDiscountDate">
                  <ns0:FirstDiscountDate>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:FirstDiscountDate"/>
                  </ns0:FirstDiscountDate>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:GrossAmount">
                  <ns0:GrossAmount>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:GrossAmount"/>
                  </ns0:GrossAmount>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HeldBy">
                  <ns0:HeldBy>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HeldBy"/>
                  </ns0:HeldBy>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HoldDate">
                  <ns0:HoldDate>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HoldDate"/>
                  </ns0:HoldDate>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HoldFlag">
                  <ns0:HoldFlag>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HoldFlag"/>
                  </ns0:HoldFlag>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HoldReason">
                  <ns0:HoldReason>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HoldReason"/>
                  </ns0:HoldReason>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HoldType">
                  <ns0:HoldType>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:HoldType"/>
                  </ns0:HoldType>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:InstallmentNumber">
                  <ns0:InstallmentNumber>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:InstallmentNumber"/>
                  </ns0:InstallmentNumber>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:LastUpdateDate">
                  <ns0:LastUpdateDate>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:LastUpdateDate"/>
                  </ns0:LastUpdateDate>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:LastUpdateLogin">
                  <ns0:LastUpdateLogin>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:LastUpdateLogin"/>
                  </ns0:LastUpdateLogin>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:LastUpdatedBy">
                  <ns0:LastUpdatedBy>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:LastUpdatedBy"/>
                  </ns0:LastUpdatedBy>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:NetAmountOne">
                  <ns0:NetAmountOne>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:NetAmountOne"/>
                  </ns0:NetAmountOne>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:NetAmountThree">
                  <ns0:NetAmountThree>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:NetAmountThree"/>
                  </ns0:NetAmountThree>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:NetAmountTwo">
                  <ns0:NetAmountTwo>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:NetAmountTwo"/>
                  </ns0:NetAmountTwo>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:PaymentMethod">
                  <ns0:PaymentMethod>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:PaymentMethod"/>
                  </ns0:PaymentMethod>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:PaymentMethodCode">
                  <ns0:PaymentMethodCode>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:PaymentMethodCode"/>
                  </ns0:PaymentMethodCode>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:PaymentPriority">
                  <ns0:PaymentPriority>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:PaymentPriority"/>
                  </ns0:PaymentPriority>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemitToAddressName">
                  <ns0:RemitToAddressName>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemitToAddressName"/>
                  </ns0:RemitToAddressName>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemitToSupplier">
                  <ns0:RemitToSupplier>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemitToSupplier"/>
                  </ns0:RemitToSupplier>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemittanceMessageOne">
                  <ns0:RemittanceMessageOne>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemittanceMessageOne"/>
                  </ns0:RemittanceMessageOne>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemittanceMessageThree">
                  <ns0:RemittanceMessageThree>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemittanceMessageThree"/>
                  </ns0:RemittanceMessageThree>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemittanceMessageTwo">
                  <ns0:RemittanceMessageTwo>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:RemittanceMessageTwo"/>
                  </ns0:RemittanceMessageTwo>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:SecondDiscountAmount">
                  <ns0:SecondDiscountAmount>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:SecondDiscountAmount"/>
                  </ns0:SecondDiscountAmount>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:SecondDiscountDate">
                  <ns0:SecondDiscountDate>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:SecondDiscountDate"/>
                  </ns0:SecondDiscountDate>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:ThirdDiscountAmount">
                  <ns0:ThirdDiscountAmount>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:ThirdDiscountAmount"/>
                  </ns0:ThirdDiscountAmount>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:ThirdDiscountDate">
                  <ns0:ThirdDiscountDate>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:ThirdDiscountDate"/>
                  </ns0:ThirdDiscountDate>
               </xsl:if>
               <xsl:if test="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:UnpaidAmount">
                  <ns0:UnpaidAmount>
                     <xsl:value-of select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:UnpaidAmount"/>
                  </ns0:UnpaidAmount>
               </xsl:if>
               <xsl:for-each select="/ns0:getInvoiceInstallmentsAPRs/ns0:items/ns0:links">
                  <ns0:links>
                     <xsl:if test="ns0:href">
                        <ns0:href>
                           <xsl:value-of select="ns0:href"/>
                        </ns0:href>
                     </xsl:if>
                     <xsl:if test="ns0:kind">
                        <ns0:kind>
                           <xsl:value-of select="ns0:kind"/>
                        </ns0:kind>
                     </xsl:if>
                     <xsl:if test="ns0:name">
                        <ns0:name>
                           <xsl:value-of select="ns0:name"/>
                        </ns0:name>
                     </xsl:if>
                     <xsl:if test="ns0:properties">
                        <ns0:properties>
                           <xsl:if test="ns0:properties/ns0:changeIndicator">
                              <ns0:changeIndicator>
                                 <xsl:value-of select="ns0:properties/ns0:changeIndicator"/>
                              </ns0:changeIndicator>
                           </xsl:if>
                        </ns0:properties>
                     </xsl:if>
                     <xsl:if test="ns0:rel">
                        <ns0:rel>
                           <xsl:value-of select="ns0:rel"/>
                        </ns0:rel>
                     </xsl:if>
                  </ns0:links>
               </xsl:for-each>
            </items>
         </Result>
      </tns:GetInvoiceInstallmentsAPRs>
   </xsl:template>
</xsl:stylesheet>