<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:ns0="http://www.example.org" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationApiTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:inv="http://soa.estrellaroja.com.mx/erpInvoiceInstallmentsAP" xmlns:ns1="http://soa.estrellaroja.com.mx/erpMaintenanceWorkOrders">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/WorkOrder/erpMaintenanceWorkOrders.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateFlexMaintenanceWORs" namespace="http://soa.estrellaroja.com.mx/erpMaintenanceWorkOrders"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationApiTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="UpdateFlexMaintenanceWORs" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationApiTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU SEP 23 12:20:39 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:UpdateFlexMaintenanceWORs>
         <Result>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:Reclasificacion">
               <ns1:Reclasificacion>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:Reclasificacion"/>
               </ns1:Reclasificacion>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:WorkOrderId">
               <ns1:WorkOrderId>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:WorkOrderId"/>
               </ns1:WorkOrderId>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:centroDeCosto">
               <ns1:centroDeCosto>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:centroDeCosto"/>
               </ns1:centroDeCosto>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:comentarios">
               <ns1:comentarios>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:comentarios"/>
               </ns1:comentarios>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:estatusZam">
               <ns1:estatusZam>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:estatusZam"/>
               </ns1:estatusZam>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:fechaCompromiso">
               <ns1:fechaCompromiso>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:fechaCompromiso"/>
               </ns1:fechaCompromiso>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:ingreso">
               <ns1:ingreso>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:ingreso"/>
               </ns1:ingreso>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:lectura">
               <ns1:lectura>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:lectura"/>
               </ns1:lectura>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:nuevaFechaCompromiso">
               <ns1:nuevaFechaCompromiso>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:nuevaFechaCompromiso"/>
               </ns1:nuevaFechaCompromiso>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:numeroDeAccidente">
               <ns1:numeroDeAccidente>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:numeroDeAccidente"/>
               </ns1:numeroDeAccidente>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:numeroDeSolicitudDeMantenimien">
               <ns1:numeroDeSolicitudDeMantenimien>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:numeroDeSolicitudDeMantenimien"/>
               </ns1:numeroDeSolicitudDeMantenimien>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:observaciones">
               <ns1:observaciones>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:observaciones"/>
               </ns1:observaciones>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:operador">
               <ns1:operador>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:operador"/>
               </ns1:operador>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:ordenFacturada">
               <ns1:ordenFacturada>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:ordenFacturada"/>
               </ns1:ordenFacturada>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:ordenPrimariaOSecundaria">
               <ns1:ordenPrimariaOSecundaria>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:ordenPrimariaOSecundaria"/>
               </ns1:ordenPrimariaOSecundaria>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:pasajeros">
               <ns1:pasajeros>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:pasajeros"/>
               </ns1:pasajeros>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:reparacionRealizada">
               <ns1:reparacionRealizada>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:reparacionRealizada"/>
               </ns1:reparacionRealizada>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:responsabilidadTirado">
               <ns1:responsabilidadTirado>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:responsabilidadTirado"/>
               </ns1:responsabilidadTirado>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:responsable">
               <ns1:responsable>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:responsable"/>
               </ns1:responsable>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:seMandoGrua">
               <ns1:seMandoGrua>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:seMandoGrua"/>
               </ns1:seMandoGrua>
            </xsl:if>
            <xsl:if test="/ns1:updateFlexMaintenanceWORs/ns1:tallerDeServicio">
               <ns1:tallerDeServicio>
                  <xsl:value-of select="/ns1:updateFlexMaintenanceWORs/ns1:tallerDeServicio"/>
               </ns1:tallerDeServicio>
            </xsl:if>
            <xsl:for-each select="/ns1:updateFlexMaintenanceWORs/ns1:links">
               <ns1:links>
                  <xsl:if test="ns1:href">
                     <ns1:href>
                        <xsl:value-of select="ns1:href"/>
                     </ns1:href>
                  </xsl:if>
                  <xsl:if test="ns1:kind">
                     <ns1:kind>
                        <xsl:value-of select="ns1:kind"/>
                     </ns1:kind>
                  </xsl:if>
                  <xsl:if test="ns1:name">
                     <ns1:name>
                        <xsl:value-of select="ns1:name"/>
                     </ns1:name>
                  </xsl:if>
                  <xsl:if test="ns1:properties">
                     <ns1:properties>
                        <xsl:if test="ns1:properties/ns1:changeIndicator">
                           <ns1:changeIndicator>
                              <xsl:value-of select="ns1:properties/ns1:changeIndicator"/>
                           </ns1:changeIndicator>
                        </xsl:if>
                     </ns1:properties>
                  </xsl:if>
                  <xsl:if test="ns1:rel">
                     <ns1:rel>
                        <xsl:value-of select="ns1:rel"/>
                     </ns1:rel>
                  </xsl:if>
               </ns1:links>
            </xsl:for-each>
         </Result>
      </tns:UpdateFlexMaintenanceWORs>
   </xsl:template>
</xsl:stylesheet>