<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationApiTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:tns="http://soa.estrellaroja.com.mx/ERPIntegrationAPIs" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:ns1="http://soa.estrellaroja.com.mx/erpInvoiceInstallmentsAP" xmlns:wo="http://soa.estrellaroja.com.mx/erpMaintenanceWorkOrders">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationApiTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="UpdateInvoiceInstallmentsAPRq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationApiTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/External/InvoiceAP/erpInvoiceInstallmentsAP.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateInvoiceInstallmentsAPRq" namespace="http://soa.estrellaroja.com.mx/erpInvoiceInstallmentsAP"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU NOV 23 15:44:51 CST 2023].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns1:updateInvoiceInstallmentsAPRq>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:BankAccount">
            <ns1:BankAccount>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:BankAccount"/>
            </ns1:BankAccount>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:CreatedBy">
            <ns1:CreatedBy>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:CreatedBy"/>
            </ns1:CreatedBy>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:CreationDate">
            <ns1:CreationDate>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:CreationDate"/>
            </ns1:CreationDate>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:DueDate">
            <ns1:DueDate>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:DueDate"/>
            </ns1:DueDate>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:ExternalBankAccountId">
            <ns1:ExternalBankAccountId>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:ExternalBankAccountId"/>
            </ns1:ExternalBankAccountId>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:FirstDiscountAmount">
            <ns1:FirstDiscountAmount>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:FirstDiscountAmount"/>
            </ns1:FirstDiscountAmount>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:FirstDiscountDate">
            <ns1:FirstDiscountDate>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:FirstDiscountDate"/>
            </ns1:FirstDiscountDate>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:GrossAmount">
            <ns1:GrossAmount>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:GrossAmount"/>
            </ns1:GrossAmount>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HeldBy">
            <ns1:HeldBy>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HeldBy"/>
            </ns1:HeldBy>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HoldDate">
            <ns1:HoldDate>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HoldDate"/>
            </ns1:HoldDate>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HoldFlag">
            <ns1:HoldFlag>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HoldFlag"/>
            </ns1:HoldFlag>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HoldReason">
            <ns1:HoldReason>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HoldReason"/>
            </ns1:HoldReason>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HoldType">
            <ns1:HoldType>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:HoldType"/>
            </ns1:HoldType>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:InstallmentNumber">
            <ns1:InstallmentNumber>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:InstallmentNumber"/>
            </ns1:InstallmentNumber>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:LastUpdateDate">
            <ns1:LastUpdateDate>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:LastUpdateDate"/>
            </ns1:LastUpdateDate>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:LastUpdateLogin">
            <ns1:LastUpdateLogin>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:LastUpdateLogin"/>
            </ns1:LastUpdateLogin>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:LastUpdatedBy">
            <ns1:LastUpdatedBy>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:LastUpdatedBy"/>
            </ns1:LastUpdatedBy>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:NetAmountOne">
            <ns1:NetAmountOne>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:NetAmountOne"/>
            </ns1:NetAmountOne>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:NetAmountThree">
            <ns1:NetAmountThree>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:NetAmountThree"/>
            </ns1:NetAmountThree>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:NetAmountTwo">
            <ns1:NetAmountTwo>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:NetAmountTwo"/>
            </ns1:NetAmountTwo>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:PaymentMethod">
            <ns1:PaymentMethod>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:PaymentMethod"/>
            </ns1:PaymentMethod>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:PaymentMethodCode">
            <ns1:PaymentMethodCode>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:PaymentMethodCode"/>
            </ns1:PaymentMethodCode>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:PaymentPriority">
            <ns1:PaymentPriority>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:PaymentPriority"/>
            </ns1:PaymentPriority>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemitToAddressName">
            <ns1:RemitToAddressName>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemitToAddressName"/>
            </ns1:RemitToAddressName>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemitToSupplier">
            <ns1:RemitToSupplier>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemitToSupplier"/>
            </ns1:RemitToSupplier>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemittanceMessageOne">
            <ns1:RemittanceMessageOne>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemittanceMessageOne"/>
            </ns1:RemittanceMessageOne>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemittanceMessageThree">
            <ns1:RemittanceMessageThree>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemittanceMessageThree"/>
            </ns1:RemittanceMessageThree>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemittanceMessageTwo">
            <ns1:RemittanceMessageTwo>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:RemittanceMessageTwo"/>
            </ns1:RemittanceMessageTwo>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:SecondDiscountAmount">
            <ns1:SecondDiscountAmount>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:SecondDiscountAmount"/>
            </ns1:SecondDiscountAmount>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:SecondDiscountDate">
            <ns1:SecondDiscountDate>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:SecondDiscountDate"/>
            </ns1:SecondDiscountDate>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:ThirdDiscountAmount">
            <ns1:ThirdDiscountAmount>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:ThirdDiscountAmount"/>
            </ns1:ThirdDiscountAmount>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:ThirdDiscountDate">
            <ns1:ThirdDiscountDate>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:ThirdDiscountDate"/>
            </ns1:ThirdDiscountDate>
         </xsl:if>
         <xsl:if test="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:UnpaidAmount">
            <ns1:UnpaidAmount>
               <xsl:value-of select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:UnpaidAmount"/>
            </ns1:UnpaidAmount>
         </xsl:if>
         <xsl:for-each select="/ns0:UpdateInvoiceInstallmentsAPRq/ns1:links">
            <ns1:links>
               <xsl:if test="ns1:href">
                  <ns1:href>
                     <xsl:value-of select="ns1:href"/>
                  </ns1:href>
               </xsl:if>
               <xsl:if test="ns1:kind">
                  <ns1:kind>
                     <xsl:value-of select="ns1:kind"/>
                  </ns1:kind>
               </xsl:if>
               <xsl:if test="ns1:name">
                  <ns1:name>
                     <xsl:value-of select="ns1:name"/>
                  </ns1:name>
               </xsl:if>
               <xsl:if test="ns1:properties">
                  <ns1:properties>
                     <xsl:if test="ns1:properties/ns1:changeIndicator">
                        <ns1:changeIndicator>
                           <xsl:value-of select="ns1:properties/ns1:changeIndicator"/>
                        </ns1:changeIndicator>
                     </xsl:if>
                  </ns1:properties>
               </xsl:if>
               <xsl:if test="ns1:rel">
                  <ns1:rel>
                     <xsl:value-of select="ns1:rel"/>
                  </ns1:rel>
               </xsl:if>
            </ns1:links>
         </xsl:for-each>
      </ns1:updateInvoiceInstallmentsAPRq>
   </xsl:template>
</xsl:stylesheet>