<xsl:stylesheet version="1.0" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:tns="http://www.example.org" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:ns0="http://soa.estrellaroja.com.mx/ERPIntegrationApiTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons" xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd" xmlns:inv="http://soa.estrellaroja.com.mx/erpInvoiceInstallmentsAP" xmlns:wo="http://soa.estrellaroja.com.mx/erpMaintenanceWorkOrders">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/ERPIntegrationApiTec.xsd"/>
            <oracle-xsl-mapper:rootElement name="UpdateFlexMaintenanceWORq" namespace="http://soa.estrellaroja.com.mx/ERPIntegrationApiTec"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
<oracle-xsl-mapper:schema location="../Schemas/External/WorkOrder/erpMaintenanceWorkOrders.xsd"/>
            <oracle-xsl-mapper:rootElement name="updateFlexMaintenanceWORq" namespace="http://soa.estrellaroja.com.mx/erpMaintenanceWorkOrders"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU SEP 23 12:12:46 CDT 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <wo:updateFlexMaintenanceWORq>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:Reclasificacion">
            <wo:Reclasificacion>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:Reclasificacion"/>
            </wo:Reclasificacion>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:WorkOrderId">
            <wo:WorkOrderId>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:WorkOrderId"/>
            </wo:WorkOrderId>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:centroDeCosto">
            <wo:centroDeCosto>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:centroDeCosto"/>
            </wo:centroDeCosto>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:comentarios">
            <wo:comentarios>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:comentarios"/>
            </wo:comentarios>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:estatusZam">
            <wo:estatusZam>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:estatusZam"/>
            </wo:estatusZam>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:fechaCompromiso">
            <wo:fechaCompromiso>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:fechaCompromiso"/>
            </wo:fechaCompromiso>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:ingreso">
            <wo:ingreso>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:ingreso"/>
            </wo:ingreso>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:lectura">
            <wo:lectura>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:lectura"/>
            </wo:lectura>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:nuevaFechaCompromiso">
            <wo:nuevaFechaCompromiso>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:nuevaFechaCompromiso"/>
            </wo:nuevaFechaCompromiso>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:numeroDeAccidente">
            <wo:numeroDeAccidente>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:numeroDeAccidente"/>
            </wo:numeroDeAccidente>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:numeroDeSolicitudDeMantenimien">
            <wo:numeroDeSolicitudDeMantenimien>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:numeroDeSolicitudDeMantenimien"/>
            </wo:numeroDeSolicitudDeMantenimien>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:observaciones">
            <wo:observaciones>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:observaciones"/>
            </wo:observaciones>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:operador">
            <wo:operador>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:operador"/>
            </wo:operador>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:ordenFacturada">
            <wo:ordenFacturada>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:ordenFacturada"/>
            </wo:ordenFacturada>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:ordenPrimariaOSecundaria">
            <wo:ordenPrimariaOSecundaria>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:ordenPrimariaOSecundaria"/>
            </wo:ordenPrimariaOSecundaria>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:pasajeros">
            <wo:pasajeros>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:pasajeros"/>
            </wo:pasajeros>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:reparacionRealizada">
            <wo:reparacionRealizada>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:reparacionRealizada"/>
            </wo:reparacionRealizada>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:responsabilidadTirado">
            <wo:responsabilidadTirado>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:responsabilidadTirado"/>
            </wo:responsabilidadTirado>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:responsable">
            <wo:responsable>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:responsable"/>
            </wo:responsable>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:seMandoGrua">
            <wo:seMandoGrua>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:seMandoGrua"/>
            </wo:seMandoGrua>
         </xsl:if>
         <xsl:if test="/ns0:UpdateFlexMaintenanceWORq/wo:tallerDeServicio">
            <wo:tallerDeServicio>
               <xsl:value-of select="/ns0:UpdateFlexMaintenanceWORq/wo:tallerDeServicio"/>
            </wo:tallerDeServicio>
         </xsl:if>
         <xsl:for-each select="/ns0:UpdateFlexMaintenanceWORq/wo:links">
            <wo:links>
               <xsl:if test="wo:href">
                  <wo:href>
                     <xsl:value-of select="wo:href"/>
                  </wo:href>
               </xsl:if>
               <xsl:if test="wo:kind">
                  <wo:kind>
                     <xsl:value-of select="wo:kind"/>
                  </wo:kind>
               </xsl:if>
               <xsl:if test="wo:name">
                  <wo:name>
                     <xsl:value-of select="wo:name"/>
                  </wo:name>
               </xsl:if>
               <xsl:if test="wo:properties">
                  <wo:properties>
                     <xsl:if test="wo:properties/wo:changeIndicator">
                        <wo:changeIndicator>
                           <xsl:value-of select="wo:properties/wo:changeIndicator"/>
                        </wo:changeIndicator>
                     </xsl:if>
                  </wo:properties>
               </xsl:if>
               <xsl:if test="wo:rel">
                  <wo:rel>
                     <xsl:value-of select="wo:rel"/>
                  </wo:rel>
               </xsl:if>
            </wo:links>
         </xsl:for-each>
      </wo:updateFlexMaintenanceWORq>
   </xsl:template>
</xsl:stylesheet>