<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:ns0="http://soa.estrellaroja.com.mx/ValidationInvoicesAPEnt"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:tns="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns1="http://soa.estrellaroja.com.mx/AuditControlTec"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns2="http://soa.estrellaroja.com.mx/ValidationInvoicesAPEnt/types"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://soa.estrellaroja.com.mx/AuditControlTec/types"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns5="http://soa.estrellaroja.com.mx/Reports/XXER_AP_INVOICE_VALIDATION_AUTOMATICA"
                xmlns:ns4="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz/types">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationInvoicesAPEnt/ValidationInvoicesAPEnt.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ValidationInvoicesAPRq"
                                       namespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPEnt"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/OSB/AuditControlTec/AuditControlTec.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GetConfValInvoicesAPRs"
                                       namespace="http://soa.estrellaroja.com.mx/AuditControlTec"/>
      <oracle-xsl-mapper:param name="GetConfigValInvoicesAPRs"/>

      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationInvoicesAPBiz/ValidationInvoicesAPBiz.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ValidateInvoicesAPRq"
                                       namespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON OCT 10 15:50:10 CDT 2022].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:param name="GetConfigValInvoicesAPRs"/>
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="string-length (/ns0:ValidationInvoicesAPRq/ns0:ConfiguracionUsuario ) > 0">
        <tns:ValidateInvoicesAPRq>
          <tns:Config>
                      <ns0:Ambiente>
              <xsl:value-of select="/ns0:ValidationInvoicesAPRq/ns0:Ambiente"/>
            </ns0:Ambiente>
            <ns0:ConfiguracionUsuario>
              <xsl:value-of select="/ns0:ValidationInvoicesAPRq/ns0:ConfiguracionUsuario"/>
            </ns0:ConfiguracionUsuario>
            <ns0:CatalogoRetenciones>
              <xsl:for-each select="$GetConfigValInvoicesAPRs/ns1:GetConfValInvoicesAPRs/ns1:Return/ns1:XxerInvoicesApConfTbl">
                <xsl:choose>
                  <xsl:when test="ns1:proccess='CATALOGO_RETENCIONES'">
                    <ns0:Retencion>
                     <ns0:VersionCFDI>
                        <xsl:value-of select="ns1:cfdiVersion"/>
                      </ns0:VersionCFDI>
                      <ns0:TipoDocumento>
                        <xsl:value-of select="ns1:documentType"/>
                      </ns0:TipoDocumento>
                      <ns0:MensajeNotificacion>
                        <xsl:value-of select="ns1:notificationMessage"/>
                      </ns0:MensajeNotificacion>
                      <ns0:Accion>
                        <xsl:value-of select="ns1:action"/>
                      </ns0:Accion>
                      <ns0:RegimenFiscal>
                        <xsl:value-of select="ns1:parameter1"/>
                      </ns0:RegimenFiscal>
                      <ns0:Cuenta>
                        <xsl:value-of select="ns1:parameter2"/>
                      </ns0:Cuenta>
                      <ns0:IVA>
                        <xsl:value-of select="ns1:parameter3"/>
                      </ns0:IVA>
                      <ns0:ISR>
                        <xsl:value-of select="ns1:parameter4"/>
                      </ns0:ISR>
                      <ns0:TipoPersona>
                        <xsl:value-of select="ns1:parameter5"/>
                      </ns0:TipoPersona>
                    </ns0:Retencion>
                  </xsl:when>
                </xsl:choose>
              </xsl:for-each>
            </ns0:CatalogoRetenciones>
            <ns0:CatalogoCondicionesPago>
              <xsl:for-each select="$GetConfigValInvoicesAPRs/ns1:GetConfValInvoicesAPRs/ns1:Return/ns1:XxerInvoicesApConfTbl">
                <xsl:choose>
                  <xsl:when test="ns1:proccess ='CATALOGO_CONDICION_PAGO'">
                    <ns0:CondicionPago>
                                         <ns0:VersionCFDI>
                        <xsl:value-of select="ns1:cfdiVersion"/>
                      </ns0:VersionCFDI>
                      <ns0:TipoDocumento>
                        <xsl:value-of select="ns1:documentType"/>
                      </ns0:TipoDocumento>
                      <ns0:MensajeNotificacion>
                        <xsl:value-of select="ns1:notificationMessage"/>
                      </ns0:MensajeNotificacion>
                      <ns0:Accion>
                        <xsl:value-of select="ns1:action"/>
                      </ns0:Accion>
                      <ns0:CondicionPago>
                        <xsl:value-of select="ns1:parameter1"/>
                      </ns0:CondicionPago>
                      <ns0:MetodoPago>
                        <xsl:value-of select="ns1:parameter2"/>
                      </ns0:MetodoPago>
                    </ns0:CondicionPago>
                  </xsl:when>
                </xsl:choose>
              </xsl:for-each>
            </ns0:CatalogoCondicionesPago>
            <ns0:CatalogoFormasPago>
              <xsl:for-each select="$GetConfigValInvoicesAPRs/ns1:GetConfValInvoicesAPRs/ns1:Return/ns1:XxerInvoicesApConfTbl">
                <xsl:choose>
                  <xsl:when test="ns1:proccess ='CATALOGO_FORMA_PAGO'">
                    <ns0:FormaPago>
                                         <ns0:VersionCFDI>
                        <xsl:value-of select="ns1:cfdiVersion"/>
                      </ns0:VersionCFDI>
                      <ns0:TipoDocumento>
                        <xsl:value-of select="ns1:documentType"/>
                      </ns0:TipoDocumento>
                      <ns0:MensajeNotificacion>
                        <xsl:value-of select="ns1:notificationMessage"/>
                      </ns0:MensajeNotificacion>
                      <ns0:Accion>
                        <xsl:value-of select="ns1:action"/>
                      </ns0:Accion>
                      <ns0:FormaPago>
                        <xsl:value-of select="ns1:parameter1"/>
                      </ns0:FormaPago>
                      <ns0:MetodoPago>
                        <xsl:value-of select="ns1:parameter2"/>
                      </ns0:MetodoPago>
                    </ns0:FormaPago>
                  </xsl:when>
                </xsl:choose>
              </xsl:for-each>
            </ns0:CatalogoFormasPago>
            <ns0:CatalogoValidaciones>
              <xsl:for-each select="$GetConfigValInvoicesAPRs/ns1:GetConfValInvoicesAPRs/ns1:Return/ns1:XxerInvoicesApConfTbl">
                <xsl:choose>
                  <xsl:when test="ns1:proccess ='VALIDACION'">
                    <ns0:Validacion>
                      <ns0:Codigo>
                        <xsl:value-of select="ns1:code"/>
                      </ns0:Codigo>
                      <ns0:Orden>
                        <xsl:value-of select="ns1:orderProccess"/>
                      </ns0:Orden>
                                           <ns0:VersionCFDI>
                        <xsl:value-of select="ns1:cfdiVersion"/>
                      </ns0:VersionCFDI>
                      <ns0:TipoDocumento>
                        <xsl:value-of select="ns1:documentType"/>
                      </ns0:TipoDocumento>
                      <ns0:MensajeNotificacion>
                        <xsl:value-of select="ns1:notificationMessage"/>
                      </ns0:MensajeNotificacion>
                      <ns0:Accion>
                        <xsl:value-of select="ns1:action"/>
                      </ns0:Accion>
                      <ns0:Parametro1>
                        <xsl:value-of select="ns1:parameter1"/>
                      </ns0:Parametro1>
                      <ns0:Parametro2>
                        <xsl:value-of select="ns1:parameter2"/>
                      </ns0:Parametro2>
                      <ns0:Parametro3>
                        <xsl:value-of select="ns1:parameter3"/>
                      </ns0:Parametro3>
                      <ns0:Parametro4>
                        <xsl:value-of select="ns1:parameter4"/>
                      </ns0:Parametro4>
                      <ns0:Parametro5>
                        <xsl:value-of select="ns1:parameter5"/>
                      </ns0:Parametro5>
                    </ns0:Validacion>
                  </xsl:when>
                </xsl:choose>
              </xsl:for-each>
            </ns0:CatalogoValidaciones>
                        <ns0:CatalogoConfiguraciones>
              <xsl:for-each select="$GetConfigValInvoicesAPRs/ns1:GetConfValInvoicesAPRs/ns1:Return/ns1:XxerInvoicesApConfTbl">
                <xsl:choose>
                  <xsl:when test="ns1:proccess ='CONFIGURACION'">
                    <ns0:Configuracion>
                      <ns0:Codigo>
                        <xsl:value-of select="ns1:code"/>
                      </ns0:Codigo>
                      <ns0:Parametro1>
                        <xsl:value-of select="ns1:parameter1"/>
                      </ns0:Parametro1>
                      <ns0:Parametro2>
                        <xsl:value-of select="ns1:parameter2"/>
                      </ns0:Parametro2>
                      <ns0:Parametro3>
                        <xsl:value-of select="ns1:parameter3"/>
                      </ns0:Parametro3>
                      <ns0:Parametro4>
                        <xsl:value-of select="ns1:parameter4"/>
                      </ns0:Parametro4>
                      <ns0:Parametro5>
                        <xsl:value-of select="ns1:parameter5"/>
                      </ns0:Parametro5>
                    </ns0:Configuracion>
                  </xsl:when>
                </xsl:choose>
              </xsl:for-each>
            </ns0:CatalogoConfiguraciones>
          </tns:Config>
        </tns:ValidateInvoicesAPRq>
      </xsl:when>
      <xsl:otherwise>
        <tns:ValidateInvoicesAPRq>
          <tns:Config>
            <ns0:Ambiente>
              <xsl:value-of select="/ns0:ValidationInvoicesAPRq/ns0:Ambiente"/>
            </ns0:Ambiente>
            <ns0:ConfiguracionUsuario>
              <xsl:value-of select="/ns0:ValidationInvoicesAPRq/ns0:ConfiguracionUsuario"/>
            </ns0:ConfiguracionUsuario>
            <ns0:CatalogoRetenciones>
              <xsl:for-each select="/ns0:ValidationInvoicesAPRq/ns0:CatalogoRetenciones/ns0:Retencion">
                <ns0:Retencion>
                  <ns0:VersionCFDI>
                    <xsl:value-of select="ns0:VersionCFDI"/>
                  </ns0:VersionCFDI>
                  <ns0:TipoDocumento >
                    <xsl:value-of select="ns0:TipoDocumento"/>
                  </ns0:TipoDocumento>
                  <ns0:MensajeNotificacion >
                    <xsl:value-of select="ns0:MensajeNotificacion"/>
                  </ns0:MensajeNotificacion>
                  <ns0:Accion >
                    <xsl:value-of select="ns0:Accion"/>
                  </ns0:Accion>
                  <ns0:RegimenFiscal >
                    <xsl:value-of select="ns0:RegimenFiscal"/>
                  </ns0:RegimenFiscal>
                  <ns0:Cuenta >
                    <xsl:value-of select="ns0:Cuenta"/>
                  </ns0:Cuenta>
                  <ns0:IVA >
                    <xsl:value-of select="ns0:IVA"/>
                  </ns0:IVA>
                  <ns0:ISR >
                    <xsl:value-of select="ns0:ISR"/>
                  </ns0:ISR>
                  <ns0:TipoPersona>
                        <xsl:value-of select="ns0:TipoPersona"/>
                  </ns0:TipoPersona>
                </ns0:Retencion>
              </xsl:for-each>
            </ns0:CatalogoRetenciones>
            <ns0:CatalogoCondicionesPago>
              <xsl:for-each select="/ns0:ValidationInvoicesAPRq/ns0:CatalogoCondicionesPago/ns0:CondicionPago">
                <ns0:CondicionPago>
                <ns0:VersionCFDI>
                    <xsl:value-of select="ns0:VersionCFDI"/>
                  </ns0:VersionCFDI>
                  <ns0:TipoDocumento >
                    <xsl:value-of select="ns0:TipoDocumento"/>
                  </ns0:TipoDocumento>
                  <ns0:MensajeNotificacion >
                    <xsl:value-of select="ns0:MensajeNotificacion"/>
                  </ns0:MensajeNotificacion>
                  <ns0:Accion >
                    <xsl:value-of select="ns0:Accion"/>
                  </ns0:Accion>
                  <ns0:CondicionPago >
                    <xsl:value-of select="ns0:CondicionPago"/>
                  </ns0:CondicionPago>
                  <ns0:MetodoPago >
                    <xsl:value-of select="ns0:MetodoPago"/>
                  </ns0:MetodoPago>
                </ns0:CondicionPago>
              </xsl:for-each>
            </ns0:CatalogoCondicionesPago>
            <ns0:CatalogoFormasPago>
              <xsl:for-each select="/ns0:ValidationInvoicesAPRq/ns0:CatalogoFormasPago/ns0:FormaPago">
                <ns0:FormaPago>
                <ns0:VersionCFDI>
                    <xsl:value-of select="ns0:VersionCFDI"/>
                  </ns0:VersionCFDI>
                  <ns0:TipoDocumento>
                    <xsl:value-of select="ns0:TipoDocumento"/>
                  </ns0:TipoDocumento>
                  <ns0:MensajeNotificacion >
                    <xsl:value-of select="ns0:MensajeNotificacion"/>
                  </ns0:MensajeNotificacion>
                  <ns0:Accion>
                    <xsl:value-of select="ns0:Accion"/>
                  </ns0:Accion>
                  <ns0:FormaPago>
                    <xsl:value-of select="ns0:FormaPago"/>
                  </ns0:FormaPago>
                  <ns0:MetodoPago>
                    <xsl:value-of select="ns0:MetodoPago"/>
                  </ns0:MetodoPago>
                </ns0:FormaPago>
              </xsl:for-each>
            </ns0:CatalogoFormasPago>
            <ns0:CatalogoValidaciones>
              <xsl:for-each select="/ns0:ValidationInvoicesAPRq/ns0:CatalogoValidaciones/ns0:Validacion">
                <ns0:Validacion>
                  <ns0:Codigo>
                    <xsl:value-of select="ns0:Codigo"/>
                  </ns0:Codigo>
                  <ns0:Orden>
                    <xsl:value-of select="ns0:Orden"/>
                  </ns0:Orden>
                  <ns0:VersionCFDI>
                    <xsl:value-of select="ns0:VersionCFDI"/>
                  </ns0:VersionCFDI>
                  <ns0:TipoDocumento >
                    <xsl:value-of select="ns0:TipoDocumento"/>
                  </ns0:TipoDocumento>
                  <ns0:MensajeNotificacion >
                    <xsl:value-of select="ns0:MensajeNotificacion"/>
                  </ns0:MensajeNotificacion>
                  <ns0:Accion>
                    <xsl:value-of select="ns0:Accion"/>
                  </ns0:Accion>
                  <ns0:Parametro1>
                    <xsl:value-of select="ns0:Parametro1"/>
                  </ns0:Parametro1>
                  <ns0:Parametro2>
                    <xsl:value-of select="ns0:Parametro2"/>
                  </ns0:Parametro2>
                  <ns0:Parametro3>
                    <xsl:value-of select="ns0:Parametro3"/>
                  </ns0:Parametro3>
                  <ns0:Parametro4>
                    <xsl:value-of select="ns0:Parametro4"/>
                  </ns0:Parametro4>
                  <ns0:Parametro5>
                    <xsl:value-of select="ns0:Parametro5"/>
                  </ns0:Parametro5>
                </ns0:Validacion>
              </xsl:for-each>
            </ns0:CatalogoValidaciones>
            <ns0:CatalogoConfiguraciones>
              <xsl:for-each select="/ns0:ValidationInvoicesAPRq/ns0:CatalogoConfiguraciones/ns0:Configuracion">
                <ns0:Configuracion>
                  <ns0:Codigo>
                    <xsl:value-of select="ns0:Codigo"/>
                  </ns0:Codigo>
                  <ns0:Parametro1>
                    <xsl:value-of select="ns0:Parametro1"/>
                  </ns0:Parametro1>
                  <ns0:Parametro2>
                    <xsl:value-of select="ns0:Parametro2"/>
                  </ns0:Parametro2>
                  <ns0:Parametro3>
                    <xsl:value-of select="ns0:Parametro3"/>
                  </ns0:Parametro3>
                  <ns0:Parametro4>
                    <xsl:value-of select="ns0:Parametro4"/>
                  </ns0:Parametro4>
                  <ns0:Parametro5>
                    <xsl:value-of select="ns0:Parametro5"/>
                  </ns0:Parametro5>
                </ns0:Configuracion>
              </xsl:for-each>
            </ns0:CatalogoConfiguraciones>
          </tns:Config>
        </tns:ValidateInvoicesAPRq>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>
