<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns1="http://soa.estrellaroja.com.mx/Reports/XXER_AP_INVOICE_VALIDATION_AUTOMATICA" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns1 ns0 mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:ns2="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns4="http://soa.estrellaroja.com.mx/ValidationInvoicesAPEnt"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns3="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz/types"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:client="http://soa.estrellaroja.com.mx/ValidationInvoicesAPEnt/BPELValidationInvoicesAPEnt">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationInvoicesAPBiz/ValidationInvoicesAPBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ValidateInvoicesAPRq" namespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BPELValidationInvoicesAPEnt.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DATA_DS" namespace="http://soa.estrellaroja.com.mx/Reports/XXER_AP_INVOICE_VALIDATION_AUTOMATICA"/>
            <oracle-xsl-mapper:param name="v_invoices"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationInvoicesAPBiz/ValidationInvoicesAPBiz.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ValidateInvoicesAPRq" namespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [MON OCT 10 19:53:11 CDT 2022].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="v_invoices"/>
   <xsl:template match="/">
      <ns0:ValidateInvoicesAPRq>
         <ns0:Config>
            <ns4:ConfiguracionUsuario>
               <xsl:value-of select="/ns0:ValidateInvoicesAPRq/ns0:Config/ns4:ConfiguracionUsuario"/>
            </ns4:ConfiguracionUsuario>
            <ns4:Ambiente>
               <xsl:value-of select="/ns0:ValidateInvoicesAPRq/ns0:Config/ns4:Ambiente"/>
            </ns4:Ambiente>
            <ns4:CatalogoRetenciones>
               <xsl:for-each select="/ns0:ValidateInvoicesAPRq/ns0:Config/ns4:CatalogoRetenciones/ns4:Retencion">
                  <ns4:Retencion>
                     <ns4:VersionCFDI>
                        <xsl:value-of select="ns4:VersionCFDI"/>
                     </ns4:VersionCFDI>
                     <ns4:TipoDocumento>
                        <xsl:value-of select="ns4:TipoDocumento"/>
                     </ns4:TipoDocumento>
                     <ns4:MensajeNotificacion>
                        <xsl:value-of select="ns4:MensajeNotificacion"/>
                     </ns4:MensajeNotificacion>
                     <ns4:Accion>
                        <xsl:value-of select="ns4:Accion"/>
                     </ns4:Accion>
                     <ns4:RegimenFiscal>
                        <xsl:value-of select="ns4:RegimenFiscal"/>
                     </ns4:RegimenFiscal>
                     <ns4:Cuenta>
                        <xsl:value-of select="ns4:Cuenta"/>
                     </ns4:Cuenta>
                     <ns4:IVA>
                        <xsl:value-of select="ns4:IVA"/>
                     </ns4:IVA>
                     <ns4:ISR>
                        <xsl:value-of select="ns4:ISR"/>
                     </ns4:ISR>
                     <ns4:TipoPersona>
                        <xsl:value-of select="ns4:TipoPersona"/>
                     </ns4:TipoPersona>
                  </ns4:Retencion>
               </xsl:for-each>
            </ns4:CatalogoRetenciones>
            <ns4:CatalogoCondicionesPago>
               <xsl:for-each select="/ns0:ValidateInvoicesAPRq/ns0:Config/ns4:CatalogoCondicionesPago/ns4:CondicionPago">
                  <ns4:CondicionPago>
                     <ns4:VersionCFDI>
                        <xsl:value-of select="ns4:VersionCFDI"/>
                     </ns4:VersionCFDI>
                     <ns4:TipoDocumento>
                        <xsl:value-of select="ns4:TipoDocumento"/>
                     </ns4:TipoDocumento>
                     <ns4:MensajeNotificacion>
                        <xsl:value-of select="ns4:MensajeNotificacion"/>
                     </ns4:MensajeNotificacion>
                     <ns4:Accion>
                        <xsl:value-of select="ns4:Accion"/>
                     </ns4:Accion>
                     <ns4:CondicionPago>
                        <xsl:value-of select="ns4:CondicionPago"/>
                     </ns4:CondicionPago>
                     <ns4:MetodoPago>
                        <xsl:value-of select="ns4:MetodoPago"/>
                     </ns4:MetodoPago>
                  </ns4:CondicionPago>
               </xsl:for-each>
            </ns4:CatalogoCondicionesPago>
            <ns4:CatalogoFormasPago>
               <xsl:for-each select="/ns0:ValidateInvoicesAPRq/ns0:Config/ns4:CatalogoFormasPago/ns4:FormaPago">
                  <ns4:FormaPago>
                     <ns4:VersionCFDI>
                        <xsl:value-of select="ns4:VersionCFDI"/>
                     </ns4:VersionCFDI>
                     <ns4:TipoDocumento>
                        <xsl:value-of select="ns4:TipoDocumento"/>
                     </ns4:TipoDocumento>
                     <ns4:MensajeNotificacion>
                        <xsl:value-of select="ns4:MensajeNotificacion"/>
                     </ns4:MensajeNotificacion>
                     <ns4:Accion>
                        <xsl:value-of select="ns4:Accion"/>
                     </ns4:Accion>
                     <ns4:FormaPago>
                        <xsl:value-of select="ns4:FormaPago"/>
                     </ns4:FormaPago>
                     <ns4:MetodoPago>
                        <xsl:value-of select="ns4:MetodoPago"/>
                     </ns4:MetodoPago>
                  </ns4:FormaPago>
               </xsl:for-each>
            </ns4:CatalogoFormasPago>
            <ns4:CatalogoValidaciones>
               <xsl:for-each select="/ns0:ValidateInvoicesAPRq/ns0:Config/ns4:CatalogoValidaciones/ns4:Validacion">
                 <xsl:sort select="ns4:Orden" data-type="number" order="ascending"/>
                  <ns4:Validacion>
                     <ns4:Codigo>
                        <xsl:value-of select="ns4:Codigo"/>
                     </ns4:Codigo>
                     <ns4:Orden>
                        <xsl:value-of select="ns4:Orden"/>
                     </ns4:Orden>
                     <ns4:VersionCFDI>
                        <xsl:value-of select="ns4:VersionCFDI"/>
                     </ns4:VersionCFDI>
                     <ns4:TipoDocumento>
                        <xsl:value-of select="ns4:TipoDocumento"/>
                     </ns4:TipoDocumento>
                     <ns4:MensajeNotificacion>
                        <xsl:value-of select="ns4:MensajeNotificacion"/>
                     </ns4:MensajeNotificacion>
                     <ns4:Accion>
                        <xsl:value-of select="ns4:Accion"/>
                     </ns4:Accion>
                     <ns4:Parametro1>
                        <xsl:value-of select="ns4:Parametro1"/>
                     </ns4:Parametro1>
                     <ns4:Parametro2>
                        <xsl:value-of select="ns4:Parametro2"/>
                     </ns4:Parametro2>
                     <ns4:Parametro3>
                        <xsl:value-of select="ns4:Parametro3"/>
                     </ns4:Parametro3>
                     <ns4:Parametro4>
                        <xsl:value-of select="ns4:Parametro4"/>
                     </ns4:Parametro4>
                     <ns4:Parametro5>
                        <xsl:value-of select="ns4:Parametro5"/>
                     </ns4:Parametro5>
                  </ns4:Validacion>
               </xsl:for-each>
            </ns4:CatalogoValidaciones>
            <ns4:CatalogoConfiguraciones>
               <xsl:for-each select="/ns0:ValidateInvoicesAPRq/ns0:Config/ns4:CatalogoConfiguraciones/ns4:Configuracion">
                  <ns4:Configuracion>
                     <ns4:Codigo>
                        <xsl:value-of select="ns4:Codigo"/>
                     </ns4:Codigo>
                     <ns4:Parametro1>
                        <xsl:value-of select="ns4:Parametro1"/>
                     </ns4:Parametro1>
                     <ns4:Parametro2>
                        <xsl:value-of select="ns4:Parametro2"/>
                     </ns4:Parametro2>
                     <ns4:Parametro3>
                        <xsl:value-of select="ns4:Parametro3"/>
                     </ns4:Parametro3>
                     <ns4:Parametro4>
                        <xsl:value-of select="ns4:Parametro4"/>
                     </ns4:Parametro4>
                     <ns4:Parametro5>
                        <xsl:value-of select="ns4:Parametro5"/>
                     </ns4:Parametro5>
                  </ns4:Configuracion>
               </xsl:for-each>
            </ns4:CatalogoConfiguraciones>
         </ns0:Config>
         <ns1:DATA_DS>
            <ns1:NUM_INTENTOS>
               <xsl:value-of select="$v_invoices/ns1:DATA_DS/ns1:NUM_INTENTOS"/>
            </ns1:NUM_INTENTOS>
            <ns1:NUM_DIAS_INTENTOS>
               <xsl:value-of select="$v_invoices/ns1:DATA_DS/ns1:NUM_DIAS_INTENTOS"/>
            </ns1:NUM_DIAS_INTENTOS>
            <xsl:for-each select="$v_invoices/ns1:DATA_DS/ns1:G_INVOICES">
               <ns1:G_INVOICES>
                  <ns1:INVOICE_PERCENTAGE_RATE>
                     <xsl:value-of select="ns1:INVOICE_PERCENTAGE_RATE"/>
                  </ns1:INVOICE_PERCENTAGE_RATE>
                  <ns1:SUPPLIER_PERCENTAGE_RATE>
                     <xsl:value-of select="ns1:SUPPLIER_PERCENTAGE_RATE"/>
                  </ns1:SUPPLIER_PERCENTAGE_RATE>
                  <ns1:INVOICE_SOURCE>
                     <xsl:value-of select="ns1:INVOICE_SOURCE"/>
                  </ns1:INVOICE_SOURCE>
                  <ns1:INVOICE_ID>
                     <xsl:value-of select="ns1:INVOICE_ID"/>
                  </ns1:INVOICE_ID>
                  <ns1:INVOICE_NUMBER>
                     <xsl:value-of select="ns1:INVOICE_NUMBER"/>
                  </ns1:INVOICE_NUMBER>
                  <ns1:INVOICE_TYPE>
                     <xsl:value-of select="ns1:INVOICE_TYPE"/>
                  </ns1:INVOICE_TYPE>
                  <ns1:SUBTOTAL>
                     <xsl:value-of select="ns1:SUBTOTAL"/>
                  </ns1:SUBTOTAL>
                  <ns1:TOTAL_TAX_AMOUNT>
                     <xsl:value-of select="ns1:TOTAL_TAX_AMOUNT"/>
                  </ns1:TOTAL_TAX_AMOUNT>
                  <ns1:TOTAL>
                     <xsl:value-of select="ns1:TOTAL"/>
                  </ns1:TOTAL>
                  <ns1:CURRENCY>
                     <xsl:value-of select="ns1:CURRENCY"/>
                  </ns1:CURRENCY>
                  <ns1:CREATION_DATE>
                     <xsl:value-of select="ns1:CREATION_DATE"/>
                  </ns1:CREATION_DATE>
                  <ns1:LAST_UPDATE_DATE>
                     <xsl:value-of select="ns1:LAST_UPDATE_DATE"/>
                  </ns1:LAST_UPDATE_DATE>
                  <ns1:INVOICE_DATE>
                     <xsl:value-of select="ns1:INVOICE_DATE"/>
                  </ns1:INVOICE_DATE>
                  <ns1:INVOICETERMSID>
                     <xsl:value-of select="ns1:INVOICETERMSID"/>
                  </ns1:INVOICETERMSID>
                  <ns1:INVOICE_TERMS_NAME>
                     <xsl:value-of select="ns1:INVOICE_TERMS_NAME"/>
                  </ns1:INVOICE_TERMS_NAME>
                  <ns1:INVOICE_TERMS_DESC>
                     <xsl:value-of select="ns1:INVOICE_TERMS_DESC"/>
                  </ns1:INVOICE_TERMS_DESC>
                  <ns1:APPROVAL_STATUS_DESC>
                     <xsl:value-of select="ns1:APPROVAL_STATUS_DESC"/>
                  </ns1:APPROVAL_STATUS_DESC>
                  <ns1:APPROVALS_TATUS>
                     <xsl:value-of select="ns1:APPROVALS_TATUS"/>
                  </ns1:APPROVALS_TATUS>
                  <ns1:SUPPLIER_ID>
                     <xsl:value-of select="ns1:SUPPLIER_ID"/>
                  </ns1:SUPPLIER_ID>
                  <ns1:SUPPLIER_NUMBER>
                     <xsl:value-of select="ns1:SUPPLIER_NUMBER"/>
                  </ns1:SUPPLIER_NUMBER>
                  <ns1:SUPPLIER_PARTY_ID>
                     <xsl:value-of select="ns1:SUPPLIER_PARTY_ID"/>
                  </ns1:SUPPLIER_PARTY_ID>
                  <ns1:SUPPLIER_NAME>
                     <xsl:value-of select="ns1:SUPPLIER_NAME"/>
                  </ns1:SUPPLIER_NAME>
                  <ns1:SUPPLIER_SITE_ID>
                     <xsl:value-of select="ns1:SUPPLIER_SITE_ID"/>
                  </ns1:SUPPLIER_SITE_ID>
                  <ns1:SUPPLIER_SITE_CODE>
                     <xsl:value-of select="ns1:SUPPLIER_SITE_CODE"/>
                  </ns1:SUPPLIER_SITE_CODE>
                  <ns1:SUPPLIER_SITE_BUSINESSUNIT_ID>
                     <xsl:value-of select="ns1:SUPPLIER_SITE_BUSINESSUNIT_ID"/>
                  </ns1:SUPPLIER_SITE_BUSINESSUNIT_ID>
                  <ns1:SUPPLIER_RFC>
                     <xsl:value-of select="ns1:SUPPLIER_RFC"/>
                  </ns1:SUPPLIER_RFC>
                  <ns1:SUPPLIER_TYPE>
                     <xsl:value-of select="ns1:SUPPLIER_TYPE"/>
                  </ns1:SUPPLIER_TYPE>
                  <ns1:SUPPLIER_STATE>
                     <xsl:value-of select="ns1:SUPPLIER_STATE"/>
                  </ns1:SUPPLIER_STATE>
                  <ns1:SUPPLIER_CITY>
                     <xsl:value-of select="ns1:SUPPLIER_CITY"/>
                  </ns1:SUPPLIER_CITY>
                  <ns1:SUPPLIER_ADDRESS>
                     <xsl:value-of select="ns1:SUPPLIER_ADDRESS"/>
                  </ns1:SUPPLIER_ADDRESS>
                  <ns1:SUPPLIER_ZIP_CODE>
                     <xsl:value-of select="ns1:SUPPLIER_ZIP_CODE"/>
                  </ns1:SUPPLIER_ZIP_CODE>
                  <ns1:ORDER_ID>
                     <xsl:value-of select="ns1:ORDER_ID"/>
                  </ns1:ORDER_ID>
                  <ns1:ORDER_NUMBER>
                     <xsl:value-of select="ns1:ORDER_NUMBER"/>
                  </ns1:ORDER_NUMBER>
                  <ns1:ORDER_BILL_BU_ID>
                     <xsl:value-of select="ns1:ORDER_BILL_BU_ID"/>
                  </ns1:ORDER_BILL_BU_ID>
                  <ns1:ORDER_SUPPLIER_ID>
                     <xsl:value-of select="ns1:ORDER_SUPPLIER_ID"/>
                  </ns1:ORDER_SUPPLIER_ID>
                  <ns1:ORDER_EMAIL>
                     <xsl:value-of select="ns1:ORDER_EMAIL"/>
                  </ns1:ORDER_EMAIL>
                  <ns1:ORDER_TERMS_ID>
                     <xsl:value-of select="ns1:ORDER_TERMS_ID"/>
                  </ns1:ORDER_TERMS_ID>
                  <ns1:REGISTRATION_NAME>
                     <xsl:value-of select="ns1:REGISTRATION_NAME"/>
                  </ns1:REGISTRATION_NAME>
                  <ns1:LEGAL_ENTITY_ZIP_CODE>
                     <xsl:value-of select="ns1:LEGAL_ENTITY_ZIP_CODE"/>
                  </ns1:LEGAL_ENTITY_ZIP_CODE>
                  <ns1:LEGAL_ENTITY_NAME>
                     <xsl:value-of select="ns1:LEGAL_ENTITY_NAME"/>
                  </ns1:LEGAL_ENTITY_NAME>
                  <ns1:LEGAL_ENTITY_REGIMEN>
                     <xsl:value-of select="ns1:LEGAL_ENTITY_REGIMEN"/>
                  </ns1:LEGAL_ENTITY_REGIMEN>
                  <ns1:LEGAL_ENTITY_SEGMENT>
                     <xsl:value-of select="ns1:LEGAL_ENTITY_SEGMENT"/>
                  </ns1:LEGAL_ENTITY_SEGMENT>
                  <ns1:ERROR_VALIDACION>
                     <xsl:value-of select="ns1:ERROR_VALIDACION"/>
                  </ns1:ERROR_VALIDACION>
                  <ns1:XML_NAME>
                     <xsl:value-of select="ns1:XML_NAME"/>
                  </ns1:XML_NAME>
                  <ns1:XML_REGISTRADOS>
                     <xsl:value-of select="ns1:XML_REGISTRADOS"/>
                  </ns1:XML_REGISTRADOS>
                  <ns1:ORGANIZATION_ID>
                     <xsl:value-of select="ns1:ORGANIZATION_ID"/>
                  </ns1:ORGANIZATION_ID>
                  <ns1:BUSINESS_UNIT>
                     <xsl:value-of select="ns1:BUSINESS_UNIT"/>
                  </ns1:BUSINESS_UNIT>
                  <ns1:LEGAL_ENTITY_ID>
                     <xsl:value-of select="ns1:LEGAL_ENTITY_ID"/>
                  </ns1:LEGAL_ENTITY_ID>
                  <ns1:REGISTRATION_RFC>
                     <xsl:value-of select="ns1:REGISTRATION_RFC"/>
                  </ns1:REGISTRATION_RFC>
                  <ns1:PDF_NAME>
                     <xsl:value-of select="ns1:PDF_NAME"/>
                  </ns1:PDF_NAME>
                  <ns1:PDF_REGISTRADOS>
                     <xsl:value-of select="ns1:PDF_REGISTRADOS"/>
                  </ns1:PDF_REGISTRADOS>
                  <ns1:INVOICE_AWT_GROUP_ID>
                     <xsl:value-of select="ns1:INVOICE_AWT_GROUP_ID"/>
                  </ns1:INVOICE_AWT_GROUP_ID>
                  <ns1:INVOICE_AWT_GROUP_CODE>
                     <xsl:value-of select="ns1:INVOICE_AWT_GROUP_CODE"/>
                  </ns1:INVOICE_AWT_GROUP_CODE>
                  <xsl:if test="string-length (ns1:INVOICE_RET_IVA )>0">
                     <ns1:INVOICE_RET_IVA>
                        <xsl:value-of select="ns1:INVOICE_RET_IVA"/>
                     </ns1:INVOICE_RET_IVA>
                  </xsl:if>
                  <xsl:if test="string-length (ns1:INVOICE_RET_ISR )>0">
                     <ns1:INVOICE_RET_ISR>
                        <xsl:value-of select="ns1:INVOICE_RET_ISR"/>
                     </ns1:INVOICE_RET_ISR>
                  </xsl:if>
                  <ns1:SUPPLIER_SITE_AWT_GROUP_ID>
                     <xsl:value-of select="ns1:SUPPLIER_SITE_AWT_GROUP_ID"/>
                  </ns1:SUPPLIER_SITE_AWT_GROUP_ID>
                  <ns1:SUPPLIER_SITE_AWT_GROUP_CODE>
                     <xsl:value-of select="ns1:SUPPLIER_SITE_AWT_GROUP_CODE"/>
                  </ns1:SUPPLIER_SITE_AWT_GROUP_CODE>
                  <xsl:if test="string-length (ns1:SUPPLIER_RET_IVA )>0">
                     <ns1:SUPPLIER_RET_IVA>
                        <xsl:value-of select="ns1:SUPPLIER_RET_IVA"/>
                     </ns1:SUPPLIER_RET_IVA>
                  </xsl:if>
                  <xsl:if test="string-length (ns1:SUPPLIER_RET_ISR )>0">
                     <ns1:SUPPLIER_RET_ISR>
                        <xsl:value-of select="ns1:SUPPLIER_RET_ISR"/>
                     </ns1:SUPPLIER_RET_ISR>
                  </xsl:if>
                  <ns1:RETENCION>
                     <xsl:value-of select="ns1:RETENCION"/>
                  </ns1:RETENCION>
                  <ns1:DIAS_INTENTADOS>
                     <xsl:value-of select="ns1:DIAS_INTENTADOS"/>
                  </ns1:DIAS_INTENTADOS>
                  <ns1:INTENTOS_HOY>
                     <xsl:value-of select="ns1:INTENTOS_HOY"/>
                  </ns1:INTENTOS_HOY>
                  <xsl:for-each select="ns1:G_INVOICES1">
                     <ns1:G_INVOICES1>
                        <ns1:PERCENTAGE_RATE>
                           <xsl:value-of select="ns1:PERCENTAGE_RATE"/>
                        </ns1:PERCENTAGE_RATE>
                        <ns1:INVOICE_ID>
                           <xsl:value-of select="ns1:INVOICE_ID"/>
                        </ns1:INVOICE_ID>
                        <ns1:ID_LINE_NUMBER>
                           <xsl:value-of select="ns1:ID_LINE_NUMBER"/>
                        </ns1:ID_LINE_NUMBER>
                        <ns1:ID_LINE_TYPE>
                           <xsl:value-of select="ns1:ID_LINE_TYPE"/>
                        </ns1:ID_LINE_TYPE>
                        <ns1:ID_DESCRIPTION>
                           <xsl:value-of select="ns1:ID_DESCRIPTION"/>
                        </ns1:ID_DESCRIPTION>
                        <ns1:ID_LINE_SOURCE>
                           <xsl:value-of select="ns1:ID_LINE_SOURCE"/>
                        </ns1:ID_LINE_SOURCE>
                        <ns1:ID_ORGANIZATION_ID>
                           <xsl:value-of select="ns1:ID_ORGANIZATION_ID"/>
                        </ns1:ID_ORGANIZATION_ID>
                        <ns1:ID_ITEM_ID>
                           <xsl:value-of select="ns1:ID_ITEM_ID"/>
                        </ns1:ID_ITEM_ID>
                        <ns1:ID_ITEM_DESCRIPTION>
                           <xsl:value-of select="ns1:ID_ITEM_DESCRIPTION"/>
                        </ns1:ID_ITEM_DESCRIPTION>
                        <ns1:ID_UNIT_CODE>
                           <xsl:value-of select="ns1:ID_UNIT_CODE"/>
                        </ns1:ID_UNIT_CODE>
                        <ns1:ID_UNIT_PRICE>
                           <xsl:value-of select="ns1:ID_UNIT_PRICE"/>
                        </ns1:ID_UNIT_PRICE>
                        <ns1:ID_QUANTITY>
                           <xsl:value-of select="ns1:ID_QUANTITY"/>
                        </ns1:ID_QUANTITY>
                        <ns1:ID_AMOUNT>
                           <xsl:value-of select="ns1:ID_AMOUNT"/>
                        </ns1:ID_AMOUNT>
                        <ns1:ID_TAX_CLASS_CODE>
                           <xsl:value-of select="ns1:ID_TAX_CLASS_CODE"/>
                        </ns1:ID_TAX_CLASS_CODE>
                        <ns1:ORDER_ID>
                           <xsl:value-of select="ns1:ORDER_ID"/>
                        </ns1:ORDER_ID>
                        <ns1:ORDER_DETAIL_ID>
                           <xsl:value-of select="ns1:ORDER_DETAIL_ID"/>
                        </ns1:ORDER_DETAIL_ID>
                        <ns1:OD_LIST_PRICE>
                           <xsl:value-of select="ns1:OD_LIST_PRICE"/>
                        </ns1:OD_LIST_PRICE>
                        <ns1:OD_LINE_TYPE_ID>
                           <xsl:value-of select="ns1:OD_LINE_TYPE_ID"/>
                        </ns1:OD_LINE_TYPE_ID>
                        <ns1:OD_ITEM_ID>
                           <xsl:value-of select="ns1:OD_ITEM_ID"/>
                        </ns1:OD_ITEM_ID>
                        <ns1:OD_ITEM_DESCRIPTION>
                           <xsl:value-of select="ns1:OD_ITEM_DESCRIPTION"/>
                        </ns1:OD_ITEM_DESCRIPTION>
                        <ns1:OD_UNIT_CODE>
                           <xsl:value-of select="ns1:OD_UNIT_CODE"/>
                        </ns1:OD_UNIT_CODE>
                        <ns1:OD_UNIT_PRICE>
                           <xsl:value-of select="ns1:OD_UNIT_PRICE"/>
                        </ns1:OD_UNIT_PRICE>
                        <ns1:OD_QUANTITY>
                           <xsl:value-of select="ns1:OD_QUANTITY"/>
                        </ns1:OD_QUANTITY>
                        <ns1:OD_AMOUNT>
                           <xsl:value-of select="ns1:OD_AMOUNT"/>
                        </ns1:OD_AMOUNT>
                        <ns1:OD_CODE_COMBINATION_ID>
                           <xsl:value-of select="ns1:OD_CODE_COMBINATION_ID"/>
                        </ns1:OD_CODE_COMBINATION_ID>
                        <ns1:OD_DEST_ORGANIZATION_ID>
                           <xsl:value-of select="ns1:OD_DEST_ORGANIZATION_ID"/>
                        </ns1:OD_DEST_ORGANIZATION_ID>
                        <ns1:GCC_ACCOUN_TTYPE>
                           <xsl:value-of select="ns1:GCC_ACCOUN_TTYPE"/>
                        </ns1:GCC_ACCOUN_TTYPE>
                        <ns1:GCC_SEGMENT1>
                           <xsl:value-of select="ns1:GCC_SEGMENT1"/>
                        </ns1:GCC_SEGMENT1>
                        <ns1:GCC_SEGMENT2>
                           <xsl:value-of select="ns1:GCC_SEGMENT2"/>
                        </ns1:GCC_SEGMENT2>
                        <ns1:GCC_SEGMENT3>
                           <xsl:value-of select="ns1:GCC_SEGMENT3"/>
                        </ns1:GCC_SEGMENT3>
                        <ns1:GCC_SEGMENT4>
                           <xsl:value-of select="ns1:GCC_SEGMENT4"/>
                        </ns1:GCC_SEGMENT4>
                        <ns1:GCC_SEGMENT5>
                           <xsl:value-of select="ns1:GCC_SEGMENT5"/>
                        </ns1:GCC_SEGMENT5>
                        <ns1:ID_TAX_LINE_ID>
                           <xsl:value-of select="ns1:ID_TAX_LINE_ID"/>
                        </ns1:ID_TAX_LINE_ID>
                        <ns1:ID_TAX_REGIME_CODE>
                           <xsl:value-of select="ns1:ID_TAX_REGIME_CODE"/>
                        </ns1:ID_TAX_REGIME_CODE>
                        <ns1:ID_TAX>
                           <xsl:value-of select="ns1:ID_TAX"/>
                        </ns1:ID_TAX>
                        <ns1:ID_TAX_JURIS_DICTION_CODE>
                           <xsl:value-of select="ns1:ID_TAX_JURIS_DICTION_CODE"/>
                        </ns1:ID_TAX_JURIS_DICTION_CODE>
                        <ns1:ID_TAX_STATUS_CODE>
                           <xsl:value-of select="ns1:ID_TAX_STATUS_CODE"/>
                        </ns1:ID_TAX_STATUS_CODE>
                        <ns1:ID_TAX_RATE_ID>
                           <xsl:value-of select="ns1:ID_TAX_RATE_ID"/>
                        </ns1:ID_TAX_RATE_ID>
                        <ns1:ID_TAX_RATE_CODE>
                           <xsl:value-of select="ns1:ID_TAX_RATE_CODE"/>
                        </ns1:ID_TAX_RATE_CODE>
                        <ns1:ID_TAX_RATE>
                           <xsl:value-of select="ns1:ID_TAX_RATE"/>
                        </ns1:ID_TAX_RATE>
                        <ns1:ID_AWT_GROUP_ID>
                           <xsl:value-of select="ns1:ID_AWT_GROUP_ID"/>
                        </ns1:ID_AWT_GROUP_ID>
                        <ns1:ID_AWT_GROUP_CODE>
                           <xsl:value-of select="ns1:ID_AWT_GROUP_CODE"/>
                        </ns1:ID_AWT_GROUP_CODE>
                        <xsl:if test="string-length (ns1:INVOICE_RET_IVA )>0">
                           <ns1:INVOICE_RET_IVA>
                              <xsl:value-of select="ns1:INVOICE_RET_IVA"/>
                           </ns1:INVOICE_RET_IVA>
                        </xsl:if>
                        <xsl:if test="string-length (ns1:INVOICE_RET_ISR )>0">
                           <ns1:INVOICE_RET_ISR>
                              <xsl:value-of select="ns1:INVOICE_RET_ISR"/>
                           </ns1:INVOICE_RET_ISR>
                        </xsl:if>
                        <ns1:ID_BASE_AMOUNT>
                           <xsl:value-of select="ns1:ID_BASE_AMOUNT"/>
                        </ns1:ID_BASE_AMOUNT>
                     </ns1:G_INVOICES1>
                  </xsl:for-each>
               </ns1:G_INVOICES>
            </xsl:for-each>
         </ns1:DATA_DS>
      </ns0:ValidateInvoicesAPRq>
   </xsl:template>
</xsl:stylesheet>
