
  CREATE TABLE "PXERINTUSER"."XXER_TBL_PUENTE_HEADER" 
   (	"TABLA_PUENTE_ID" NUMBER NOT NULL ENABLE, 
	"SISTEMA_ORIGEN" VARCHAR2(100 BYTE), 
	"TIPO_DOCUMENTO" VARCHAR2(50 BYTE), 
	"TIPO_MOVIMIENTO" VARCHAR2(50 BYTE), 
	"UNIDAD_NEGOCIO_ORIGEN" VARCHAR2(240 BYTE), 
	"NOMBRE_FISCAL_ORIGEN" VARCHAR2(240 BYTE), 
	"EMPRESA_ORIGEN" VARCHAR2(240 BYTE), 
	"RFC_ORIGEN" VARCHAR2(25 BYTE), 
	"UNIDAD_NEGOCIO_DESTINO" VARCHAR2(240 BYTE), 
	"NOMBRE_FISCAL_DESTINO" VARCHAR2(240 BYTE), 
	"EMPRESA_DESTINO" VARCHAR2(240 BYTE), 
	"RFC_DESTINO" VARCHAR2(25 BYTE), 
	"SUCURSAL_VENTA" VARCHAR2(240 BYTE), 
	"NUMERO_DOCUMENTO" VARCHAR2(25 BYTE), 
	"FECHA_MOVIMIENTO" DATE, 
	"REFERENCIA_APLICACION" VARCHAR2(1760 BYTE), 
	"ADICIONAL1" VARCHAR2(80 BYTE), 
	"ADICIONAL2" VARCHAR2(80 BYTE), 
	"ADICIONAL3" VARCHAR2(80 BYTE), 
	"ADICIONAL4" VARCHAR2(80 BYTE), 
	"ADICIONAL5" VARCHAR2(80 BYTE), 
	"ADICIONAL6" VARCHAR2(80 BYTE), 
	"ADICIONAL7" VARCHAR2(80 BYTE), 
	"ADICIONAL8" VARCHAR2(80 BYTE), 
	"ADICIONAL9" VARCHAR2(80 BYTE), 
	"ADICIONAL10" VARCHAR2(80 BYTE), 
	"ESTATUS" VARCHAR2(1 BYTE), 
	"DETALLE_ERROR" VARCHAR2(2000 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"ESTATUSAP" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;


  CREATE TABLE "PXERINTUSER"."XXER_TBL_PUENTE_LINES" 
   (	"TABLA_PUENTE_LINEA_ID" NUMBER NOT NULL ENABLE, 
	"TABLA_PUENTE_ID" NUMBER NOT NULL ENABLE, 
	"ORIGEN_SERVICIO" VARCHAR2(240 BYTE), 
	"DESTINO_SERVICIO" VARCHAR2(240 BYTE), 
	"SERVICIO" VARCHAR2(240 BYTE), 
	"CONCEPTO_MODALIDAD" VARCHAR2(240 BYTE), 
	"FORMA_PAGO" VARCHAR2(15 BYTE), 
	"CANTIDAD" NUMBER, 
	"NO_LINEA" NUMBER, 
	"LINEA_ARTICULO" VARCHAR2(100 BYTE), 
	"UNIDAD_MEDIDA" VARCHAR2(25 BYTE), 
	"REFERENCIA_APLICACION" VARCHAR2(150 BYTE), 
	"SUBTOTAL" NUMBER, 
	"CODIGO_IVA" VARCHAR2(25 BYTE), 
	"TASA_IVA" NUMBER, 
	"MONTO_IVA" NUMBER, 
	"CODIGO_RETENCION_IVA" VARCHAR2(25 BYTE), 
	"TASA_RET_IVA" NUMBER, 
	"MONTO_RET_IVA" NUMBER, 
	"CODIGO_RETENCION_ISR" VARCHAR2(25 BYTE), 
	"TASA_RET_ISR" NUMBER, 
	"MONTO_RET_ISR" NUMBER, 
	"TOTAL" NUMBER, 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;


  CREATE TABLE "PXERINTUSER"."XXER_TBL_PUENTE_AUXILIAR_2" 
   (	"TABLA_PUENTE_AUXILIAR_ID" NUMBER NOT NULL ENABLE, 
	"TABLA_PUENTE_HEADER_ID" NUMBER, 
	"FOLIO_FACTURA_FISCAL" VARCHAR2(150 BYTE), 
	"RFC" VARCHAR2(100 BYTE), 
	"UUID" VARCHAR2(100 BYTE), 
	"SERIE" VARCHAR2(100 BYTE), 
	"SUBTOTAL" NUMBER(10,2), 
	"IVA" NUMBER(10,2), 
	"IVA_RETENIDO" NUMBER(10,2), 
	"RET_5MILLAR" NUMBER(10,2), 
	"DESCUENTO" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"FOLIO_FACTURA_AR" VARCHAR2(100 BYTE), 
	"ADICIONAL1" VARCHAR2(280 BYTE), 
	"ADICIONAL2" VARCHAR2(280 BYTE), 
	"ADICIONAL3" VARCHAR2(280 BYTE), 
	"ADICIONAL4" VARCHAR2(280 BYTE), 
	"ADICIONAL5" VARCHAR2(2028 BYTE), 
	"ADICIONAL6" VARCHAR2(280 BYTE), 
	"ADICIONAL7" VARCHAR2(280 BYTE), 
	"ADICIONAL8" VARCHAR2(280 BYTE), 
	"ADICIONAL9" VARCHAR2(280 BYTE), 
	"ADICIONAL10" VARCHAR2(280 BYTE), 
	"CREADO_POR" NUMBER NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	"ULTIMA_ACTUALIZACION_POR" NUMBER NOT NULL ENABLE, 
	"ULTIMA_FECHA_ACTUALIZACION" DATE NOT NULL ENABLE, 
	 CONSTRAINT "XXER_TBL_PUENTE_AUXILIAR_2_PK" PRIMARY KEY ("TABLA_PUENTE_AUXILIAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;


  CREATE TABLE "PXERINTUSER"."XXER_CNF_INTERFASE_INGRESOS_AR" 
   (	"ID_INTERFAZ" NUMBER NOT NULL ENABLE, 
	"CD_UNIDAD_OPERATIVA" NUMBER, 
	"UNIDAD_OPERATIVA" VARCHAR2(100 BYTE), 
	"SISTEMA_ORIGEN" VARCHAR2(30 BYTE), 
	"TIPO_DOCUMENTO" VARCHAR2(30 BYTE), 
	"TIPO_MOVIMIENTO" VARCHAR2(30 BYTE), 
	"COORDINADO" VARCHAR2(30 BYTE), 
	"IMPUESTO" VARCHAR2(25 BYTE), 
	"ORIGEN_TRANSACCION" VARCHAR2(30 BYTE), 
	"TIPO_TRANSACCION_AR" VARCHAR2(30 BYTE), 
	"METODO_RECIBO" VARCHAR2(30 BYTE), 
	"UNIDAD_NEGOCIO_ORIGEN" VARCHAR2(50 BYTE), 
	"NOMBRE_FISCAL_ORIGEN" VARCHAR2(50 BYTE), 
	"EMPRESA_ORIGEN" VARCHAR2(240 BYTE), 
	"RFC_ORIGEN" VARCHAR2(50 BYTE), 
	"UNIDAD_NEGOCIO_DESTINO" VARCHAR2(50 BYTE), 
	"NOMBRE_FISCAL_DESTINO" VARCHAR2(50 BYTE), 
	"EMPRESA_DESTINO" VARCHAR2(240 BYTE), 
	"RFC_DESTINO" VARCHAR2(50 BYTE), 
	"SUCURSAL_VENTA" VARCHAR2(240 BYTE), 
	"ORIGEN_SERVICIO" VARCHAR2(240 BYTE), 
	"DESTINO_SERVICIO" VARCHAR2(240 BYTE), 
	"SERVICIO" VARCHAR2(100 BYTE), 
	"CONCEPTO_MODALIDAD" VARCHAR2(50 BYTE), 
	"FORMA_PAGO" VARCHAR2(30 BYTE), 
	"SUMARIZADO" VARCHAR2(30 BYTE), 
	"APLICA_AR" VARCHAR2(30 BYTE), 
	"APLICA_AP" VARCHAR2(30 BYTE), 
	"CUENTA_INGRESOS" VARCHAR2(50 BYTE), 
	"CUENTA_COBRAR" VARCHAR2(50 BYTE), 
	"CUENTA_IMPUESTO" VARCHAR2(50 BYTE), 
	"CUENTA_RETENCION" VARCHAR2(50 BYTE), 
	"CUENTA_AP" VARCHAR2(50 BYTE), 
	"ADICIONAL1" VARCHAR2(80 BYTE), 
	"ADICIONAL2" VARCHAR2(80 BYTE), 
	"ADICIONAL3" VARCHAR2(80 BYTE), 
	"ADICIONAL4" VARCHAR2(80 BYTE), 
	"ADICIONAL5" VARCHAR2(80 BYTE), 
	"ADICIONAL6" VARCHAR2(80 BYTE), 
	"ADICIONAL7" VARCHAR2(80 BYTE), 
	"ADICIONAL8" VARCHAR2(80 BYTE), 
	"ADICIONAL9" VARCHAR2(80 BYTE), 
	"ADICIONAL10" VARCHAR2(80 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"CUENTA_INGRESOS_DESC" VARCHAR2(240 BYTE), 
	"CUENTA_COBRAR_DESC" VARCHAR2(240 BYTE), 
	"CUENTA_IMPUESTO_DESC" VARCHAR2(240 BYTE), 
	"CUENTA_RETENCION_DESC" VARCHAR2(240 BYTE), 
	"CUENTA_AP_DESC" VARCHAR2(240 BYTE), 
	"MEMO_LINE" VARCHAR2(120 BYTE), 
	"RECEIPT_METHOD_ID" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"UNIDAD_OPERATIVA_DESTINO" VARCHAR2(100 BYTE), 
	"AP_TERCEROS" NUMBER, 
	 CONSTRAINT "XXER_CNF_INTERFASE_INGRESOS_PK" PRIMARY KEY ("ID_INTERFAZ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PXERINTUSER"."ID_INTERFAZ_SEQ" 
	BEFORE INSERT ON XXER_CNF_INTERFASE_INGRESOS_AR
	FOR EACH ROW
BEGIN
    IF :NEW.ID_INTERFAZ IS NULL THEN
		SELECT ID_INTERFAZ_S.NEXTVAL INTO :NEW.ID_INTERFAZ FROM SYS.DUAL;
	END IF;
END;
/
ALTER TRIGGER "PXERINTUSER"."ID_INTERFAZ_SEQ" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PXERINTUSER"."XXER_CNF_INTERFASE_IMP_TGR" 
BEFORE INSERT
ON XXER_CNF_INTERFASE_INGRESOS_AR
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
/******************************************************************************
   NAME:       XXER_CNF_INTERFASE_IMP_TGR
   PURPOSE:    

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        27/03/2018      imunoz       1. Created this trigger.

   NOTES:

   Automatically available Auto Replace Keywords:
      Object Name:     XXER_CNF_INTERFASE_IMP_TGR
      Sysdate:         27/03/2018
      Date and Time:   27/03/2018, 01:23:20 p.m., and 27/03/2018 01:23:20 p.m.
      Username:        imunoz (set in TOAD Options, Proc Templates)
      Table Name:      XXER_CNF_INTERFASE_INGRESOS_AR (set in the "New PL/SQL Object" dialog)
      Trigger Options:  (set in the "New PL/SQL Object" dialog)
******************************************************************************/
BEGIN
   
   CASE 
     WHEN :NEW.IMPUESTO = 'AR_IVA_EXENTO' THEN :NEW.IMPUESTO := 'TAS-IVAEXE';  
     WHEN :NEW.IMPUESTO = 'AR_IVA00' THEN :NEW.IMPUESTO := 'TAS-IVACERO';  
     WHEN :NEW.IMPUESTO = 'AR_IVA16' THEN :NEW.IMPUESTO := 'TAS-IVAAR16%';
     WHEN :NEW.IMPUESTO = 'AP_IVA_NO_GRAVADO' THEN :NEW.IMPUESTO := 'IMP-IVAAP';
     ELSE NULL;  
   END CASE;
   
   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END XXER_CNF_INTERFASE_IMP_TGR;
/
ALTER TRIGGER "PXERINTUSER"."XXER_CNF_INTERFASE_IMP_TGR" ENABLE;

