SELECT 
	 STATUS
	,TRX_NUMBER
	,REQUEST_ID
	,MESSAGE_TEXT
	,INVALID_VALUE
	,TRX_DATE_ERROR
FROM 	
(
SELECT
  'LOADED' STATUS  
  ,CUST.TRX_NUMBER  
  ,CUST.REQUEST_ID
  ,NULL MESSAGE_TEXT
  ,NULL INVALID_VALUE
  ,NULL TRX_DATE_ERROR
  
FROM 
  RA_CUSTOMER_TRX_ALL CUST
WHERE 1 = 1

UNION

SELECT 
 'ERROR' STATUS
, RAI.TRX_NUMBER
, RAI.REQUEST_ID
, RAIE.MESSAGE_TEXT
, RAIE. INVALID_VALUE
, RAI. TRX_DATE TRX_DATE_ERROR
  FROM RA_INTERFACE_LINES_ALL RAI
, RA_INTERFACE_ERRORS_ALL RAIE
WHERE RAI.INTERFACE_LINE_ID = RAIE.INTERFACE_LINE_ID (+)
)
WHERE 1        = 1
AND TRX_NUMBER IN (:P_TRX_NUMBER)
ORDER BY  REQUEST_ID DESC