<wsdl:definitions
     name="ReceiveFileSantanderEx"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/GER_SOA/SFTPBankEnt/ReceiveFileSantanderEx"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/GER_SOA/SFTPBankEnt/ReceiveFileSantanderEx"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
    >
  <plt:partnerLinkType name="ReceiveFile_plt" >
    <plt:role name="ReceiveFile_role" >
      <plt:portType name="tns:ReceiveFile_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
    <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/opaque/"
            xmlns="http://www.w3.org/2001/XMLSchema" >
      <element name="opaqueElement" type="base64Binary" />
    </schema>
    </wsdl:types>
    <wsdl:message name="ReceiveFile_msg">
        <wsdl:part name="opaque" element="opaque:opaqueElement"/>
    </wsdl:message>
    <wsdl:portType name="ReceiveFile_ptt">
        <wsdl:operation name="ReceiveFile">
            <wsdl:input message="tns:ReceiveFile_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
