<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://soa.estrellaroja.com.mx/SFTPBankEnt"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://soa.estrellaroja.com.mx/SFTPBankEnt"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="BpelProccessFile">
        <plnk:role name="SFTPBankEntPort" portType="tns:SFTPBankEntPort"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soa.estrellaroja.com.mx/SFTPBankEnt" location="oramds:/apps/SOA/SFTPBankEnt/SFTPBankEnt.wsdl"/>
</wsdl:definitions>
