					  
WITH
            CB as (
			SELECT AFILIACION,IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO,REFERENCIA,NO_OPERACION
                    FROM  TMS_COCILIACION_BANCOS_TBL WHERE 1=1 AND USUARIO NOT IN('0670GGZM0')
                    and AFILIACION='008139649' 
                    and TRUNC(FECHA_DEPOSITO)=TO_DATE('19/11/2021','DD/MM/YYYY')
			),
            BV AS(SELECT VE.NUMERO_DOCUMENTO,VE.REFERENCIA
            ,SUM(VE.IMPORTE_BOLETO) IMPORTE_TMS
                    ,LISTAGG(VE.FOLIO_PREIMPRESO||'_'||VE.IMPORTE_BOLETO, ',') WITHIN  GROUP (ORDER BY VE.FOLIO_PREIMPRESO) AS FOLIOS_PREIMPRESOS
                    FROM PCENTRAL.EXTRACCION_VENTA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VE
                    WHERE TRUNC(VE.CORTE_FECHA_CREACION) BETWEEN TO_DATE('10/11/21','DD/MM/YY') AND TO_DATE('20/11/21','DD/MM/YY')
                    AND VE.TIPO_PAGO NOT IN('EFE','AMX') AND  TIPO_OPERACION NOT IN ('HO','FO')
                    GROUP BY VE.NUMERO_DOCUMENTO,VE.REFERENCIA
                    ),
            BVM AS(SELECT VM.NUMERO_DOCUMENTO,
			SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1) REFERENCIA
			,SUM(VM.TOTAL) IMPORTE_TMS
			,LISTAGG(BR.FOLIO_PREIMPRESO||'_'||VM.TOTAL, ',') WITHIN  GROUP (ORDER BY BR.FOLIO_PREIMPRESO) AS FOLIOS_PREIMPRESOS 
             FROM EXTRACCION_MISCELANEA_TP_VIEW@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VM
             INNER JOIN TMS_CORTES_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX CR
             ON (CR.CORTE_ID = VM.CORTE_ID)
             INNER JOIN TMS_BOLETOS_VENTA_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX VT
             ON (VT.FOLIO_PREIMPRESO = VM.NO_FOLIO 
             AND TRUNC(VT.FECHA_CREACION) BETWEEN TO_DATE('10/11/21','DD/MM/YY') AND TO_DATE('20/11/21','DD/MM/YY'))
             INNER JOIN TMS_BOLETOS_VENTA_TBL@PCENTRAL_LINK.ESTRELLAROJA.COM.MX BR ON BR.BOLETO_RELACIONADO_ID = VT.BOLETO_ID 
             AND BR.TIPO_PAGO NOT IN ('EFE')
             where 1=1 --AND SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1)='356087540'
             and  TRUNC(VM.CORTE_FECHA_CREACION) BETWEEN TO_DATE('10/11/21','DD/MM/YY') AND TO_DATE('20/11/21','DD/MM/YY')
             GROUP BY VM.NUMERO_DOCUMENTO,SUBSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),1,INSTR(SUBSTR(BR.REFERENCIA_PAGO,INSTR(BR.REFERENCIA_PAGO,';')+1 ,LENGTH(BR.REFERENCIA_PAGO)),';',-2)-1)
                    ),          
                      TB AS (SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE
					  ,BV.NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID ,BV.REFERENCIA,BV.FOLIOS_PREIMPRESOS,BV.IMPORTE_TMS
                           FROM CB INNER JOIN BV ON CB.REFERENCIA = BV.REFERENCIA
                           LEFT JOIN xxer_tbl_puente_header HD
                              ON  BV.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                           GROUP BY CB.AFILIACION,BV.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID,BV.REFERENCIA,BV.FOLIOS_PREIMPRESOS,BV.IMPORTE_TMS
                             UNION ALL
                            SELECT CB.AFILIACION,CB.FECHA_DEPOSITO,sum(CB.IMPORTE)as IMPORTE
							,BVM.NUMERO_DOCUMENTO,HD.TABLA_PUENTE_ID,BVM.REFERENCIA,BVM.FOLIOS_PREIMPRESOS,BVM.IMPORTE_TMS
                              FROM CB INNER JOIN BVM ON CB.NO_OPERACION = BVM.REFERENCIA
                              LEFT JOIN xxer_tbl_puente_header HD
                              ON  BVM.NUMERO_DOCUMENTO =HD.NUMERO_DOCUMENTO
                              GROUP BY CB.AFILIACION,BVM.NUMERO_DOCUMENTO,CB.FECHA_DEPOSITO,HD.TABLA_PUENTE_ID,BVM.REFERENCIA,BVM.FOLIOS_PREIMPRESOS,BVM.IMPORTE_TMS
                              ),
                               BCT AS (SELECT AFILIACION,sum(IMPORTE) AS IMPORTE,TRUNC(FECHA_DEPOSITO) as FECHA_DEPOSITO FROM CB GROUP BY AFILIACION,FECHA_DEPOSITO)
                              SELECT BCT.AFILIACION,BCT.FECHA_DEPOSITO,TB.IMPORTE AS IMPORTE_BANCO,TB.IMPORTE_TMS--,BCT.IMPORTE AS IMPORTE_BANCO--,(SUM(TB.IMPORTE)-BCT.IMPORTE) AS DIFERENCIA
                              ,(TB.IMPORTE - TB.IMPORTE_TMS) AS DIFERENCIA
                              ,TB.FOLIOS_PREIMPRESOS,TB.NUMERO_DOCUMENTO,TB.REFERENCIA
							  --,LISTAGG(TB.NUMERO_DOCUMENTO||'_'||TB.IMPORTE, ',') WITHIN  GROUP (ORDER BY TB.NUMERO_DOCUMENTO) AS NUMEROS_DOCUMENTOS
                              --,LISTAGG(NVL(TB.TABLA_PUENTE_ID,0), ',') WITHIN  GROUP (ORDER BY TB.TABLA_PUENTE_ID) AS TABLA_PUENTE_IDS
                              FROM TB INNER JOIN BCT ON TRUNC(TB.FECHA_DEPOSITO) = TRUNC(BCT.FECHA_DEPOSITO) AND TB.AFILIACION = BCT.AFILIACION        
                              --GROUP BY BCT.FECHA_DEPOSITO,BCT.AFILIACION,BCT.IMPORTE