<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions targetNamespace="http://soa.estrellaroja.com.mx/SFTPBankEnt"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://soa.estrellaroja.com.mx/SFTPBankEnt"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://soa.estrellaroja.com.mx/SFTPBankEnt/types" elementFormDefault="qualified"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://soa.estrellaroja.com.mx/SFTPBankEnt" schemaLocation="SFTPBankEnt.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ProcessFileRq">
    <wsdl:part name="ProcessFileRq" element="tns:ProcessFileRq"/>
  </wsdl:message>
  <wsdl:message name="ProcessFileRs">
    <wsdl:part name="ProcessFileRs" element="tns:ProcessFileRs"/>
  </wsdl:message>
  <wsdl:portType name="SFTPBankEntPort">
    <wsdl:operation name="ProcessFile">
      <wsdl:input message="tns:ProcessFileRq"/>
      <wsdl:output message="tns:ProcessFileRs"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SFTPBankEntBinding" type="tns:SFTPBankEntPort">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ProcessFile">
      <soap12:operation style="document" soapAction="http://soa.estrellarojacleyton.com.mx/SFTPBankEnt/ProcessFile"
                        soapActionRequired="false"/>
      <wsdl:input>
        <soap12:body use="literal" parts="ProcessFileRq"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" parts="ProcessFileRs"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SFTPBankEnt">
    <wsdl:port name="SFTPBankEntPort" binding="tns:SFTPBankEntBinding">
      <soap:address location="http://ersoaprod02lab-soa-0.snproduccin.vcner.oraclevcn.com:9073/soa-infra/services/Commons/SFTPBankEnt/SFTPBankEnt"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
