DROP TABLE  xxer_ar_conciliacion_tbl ;
COMMIT;
CREATE TABLE "XXER_AR_CONCILIACION_TBL" 
   (	"CONCILIACION_ID" NUMBER(18,0) DEFAULT "XXER_AR_CONCILIACION_S"."NEXTVAL" NOT NULL ENABLE, 
	"REFERENCE_PAYMENT" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PAYMENT_NUMBER" VARCHAR2(50 BYTE), 
	"AMOUNT_TRANSACTIONS" NUMBER, 
	"AMOUNT_PAYMENT" NUMBER, 
	"TOLERANCE" NUMBER, 
	"STATUS" CHAR(3 BYTE), 
	"MSJ_VALIDATION" VARCHAR2(300 BYTE), 
	"REFERENCE_TRANSACTIONS_ID" CLOB, 
	"REFERENCE_TRANSACTIONS" CLOB, 
	"FECHA_CONCILIACION" TIMESTAMP (6), 
	"METODO_RECIBO" VARCHAR2(50 BYTE)
   );
  
  
   CREATE SEQUENCE  "PXERINTUSER"."XXER_AR_CONCILIACION_S"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 581 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


INSERT INTO "XERINTUSER"."XXER_AR_CONCILIACION_TBL" 
(REFERENCE_PAYMENT, AMOUNT_TRANSACTIONS, AMOUNT_PAYMENT, STATUS, MSJ_VALIDATION, REFERENCE_TRANSACTIONS_ID, REFERENCE_TRANSACTIONS, FECHA_CONCILIACION, METODO_RECIBO) 
VALUES ('PREF06092019SUBF', '320', '320', 'C', 'Success', '803168', '06919115TPP16GTTP1TF', TO_TIMESTAMP('2021-05-19 10:59:17.170000000', 'YYYY-MM-DD HH24:MI:SS.FF'), 'TEST_1234');

commit;

--Creamos y ponemos en estatus process
MERGE INTO XXER_AR_CONCILIACION_TBL c USING (SELECT DISTINCT 
          inv.REFERENCE_PAYMENT,
          inv.METODO_RECIBO,
          inv.TOLERANCIA
     FROM XXER_AR_INVOICES_CONCILIACION_V inv
     where 
     TRUNC(inv.FECHA_MOVIMIENTO)>= NVL(TRUNC(TO_DATE(p_fromDate,'DD/MM/YYYY')),TRUNC(inv.FECHA_MOVIMIENTO))
     and NVL(inv.unidad_negocio_origen,1)=NVL(p_businessUnit,inv.unidad_negocio_origen)
     and inv.reference_payment=NVL(p_paymentReference,inv.reference_payment)) vc
ON (c.REFERENCE_PAYMENT = vc.REFERENCE_PAYMENT and c.METODO_RECIBO=vc.METODO_RECIBO)
WHEN MATCHED THEN
UPDATE SET 
c.AMOUNT_TRANSACTIONS=null,
c.AMOUNT_PAYMENT=null,
c.TOLERANCE = vc.TOLERANCIA,
c.STATUS='P',
c.MSJ_VALIDATION=null,
c.REFERENCE_TRANSACTIONS_ID=null,
c.REFERENCE_TRANSACTIONS=null,
c.FECHA_CONCILIACION=sysdate
WHEN NOT MATCHED THEN
INSERT (REFERENCE_PAYMENT, AMOUNT_TRANSACTIONS, AMOUNT_PAYMENT,TOLERANCE, STATUS, MSJ_VALIDATION, REFERENCE_TRANSACTIONS_ID, REFERENCE_TRANSACTIONS, FECHA_CONCILIACION, METODO_RECIBO)
VALUES (vc.REFERENCE_PAYMENT,null,null, vc.TOLERANCIA,'P',null,null,null,sysdate, vc.METODO_RECIBO);
--update 

UPDATE  XXER_AR_CONCILIACION_TBL  SET 
AMOUNT_TRANSACTIONS=null,
AMOUNT_PAYMENT=null,
TOLERANCE = null,
STATUS='C',
MSJ_VALIDATION=null,
REFERENCE_TRANSACTIONS_ID=null,
REFERENCE_TRANSACTIONS=null,
FECHA_CONCILIACION=sysdate
 where 1=1
 and REFERENCE_PAYMENT ='AFIL.-008180414-04052021'  
 and METODO_RECIBO='SANTANDER_3550';

