<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://soa.estrellaroja.com.mx/ValidationPaymentsAPBiz" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:cmn="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:inv="http://soa.estrellaroja.com.mx/erpInvoiceInstallmentsAP"
                xmlns:cp="http://soa.estrellaroja.com.mx/Reports/XXER_ValidationComplement">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationPaymentsAPBiz/ValidationPaymentsAPBiz.xsd"/>
            <oracle-xsl-mapper:rootElement name="UpdateSupplierInvoicesInstallmentsAPRs" namespace="http://soa.estrellaroja.com.mx/ValidationPaymentsAPBiz"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationPaymentsAPBiz/ValidationPaymentsAPBiz.xsd"/>
            <oracle-xsl-mapper:rootElement name="UpdateInvoicesInstallmentsAPRs" namespace="http://soa.estrellaroja.com.mx/ValidationPaymentsAPBiz"/>
            <oracle-xsl-mapper:param name="BpelUpdateInvoicesInstallmentsAPRs.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="oramds:/apps/SOA/ValidationPaymentsAPBiz/ValidationPaymentsAPBiz.xsd"/>
            <oracle-xsl-mapper:rootElement name="UpdateSupplierInvoicesInstallmentsAPRs" namespace="http://soa.estrellaroja.com.mx/ValidationPaymentsAPBiz"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [WED JAN 17 23:44:43 CST 2024].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="BpelUpdateInvoicesInstallmentsAPRs.payload"/>
   <xsl:template match="/">
      <ns0:UpdateSupplierInvoicesInstallmentsAPRs>
         <xsl:if test="/ns0:UpdateSupplierInvoicesInstallmentsAPRs/cmn:Errors">
            <cmn:Errors>
               <xsl:for-each select="/ns0:UpdateSupplierInvoicesInstallmentsAPRs/cmn:Errors/cmn:Error">
                  <cmn:Error>
                     <cmn:ErrorCode>
                        <xsl:value-of select="cmn:ErrorCode"/>
                     </cmn:ErrorCode>
                     <cmn:ShortDescription>
                        <xsl:value-of select="cmn:ShortDescription"/>
                     </cmn:ShortDescription>
                     <cmn:Description>
                        <xsl:value-of select="cmn:Description"/>
                     </cmn:Description>
                     <cmn:BusinessProcess>
                        <xsl:value-of select="cmn:BusinessProcess"/>
                     </cmn:BusinessProcess>
                     <cmn:FailedService>
                        <xsl:value-of select="cmn:FailedService"/>
                     </cmn:FailedService>
                     <cmn:TimeStamp>
                        <xsl:value-of select="cmn:TimeStamp"/>
                     </cmn:TimeStamp>
                  </cmn:Error>
               </xsl:for-each>
            </cmn:Errors>
         </xsl:if>
         <xsl:for-each select="/ns0:UpdateSupplierInvoicesInstallmentsAPRs/ns0:Supplier">
            <ns0:Supplier>
               <ns0:supplier_number>
                  <xsl:value-of select="ns0:supplier_number"/>
               </ns0:supplier_number>
               <ns0:supplier_rfc>
                  <xsl:value-of select="ns0:supplier_rfc"/>
               </ns0:supplier_rfc>
               <xsl:for-each select="ns0:invoice">
                  <ns0:invoice>
                     <xsl:if test="/ns0:UpdateSupplierInvoicesInstallmentsAPRs/cmn:Errors">
                        <cmn:Errors>
                           <xsl:for-each select="/ns0:UpdateSupplierInvoicesInstallmentsAPRs/cmn:Errors/cmn:Error">
                              <cmn:Error>
                                 <cmn:ErrorCode>
                                    <xsl:value-of select="cmn:ErrorCode"/>
                                 </cmn:ErrorCode>
                                 <cmn:ShortDescription>
                                    <xsl:value-of select="cmn:ShortDescription"/>
                                 </cmn:ShortDescription>
                                 <cmn:Description>
                                    <xsl:value-of select="cmn:Description"/>
                                 </cmn:Description>
                                 <cmn:BusinessProcess>
                                    <xsl:value-of select="cmn:BusinessProcess"/>
                                 </cmn:BusinessProcess>
                                 <cmn:FailedService>
                                    <xsl:value-of select="cmn:FailedService"/>
                                 </cmn:FailedService>
                                 <cmn:TimeStamp>
                                    <xsl:value-of select="cmn:TimeStamp"/>
                                 </cmn:TimeStamp>
                              </cmn:Error>
                           </xsl:for-each>
                        </cmn:Errors>
                     </xsl:if>
                     <xsl:for-each select="ns0:invoice">
                        <ns0:invoice>
                           <ns0:invoice_id>
                              <xsl:value-of select="ns0:invoice_id"/>
                           </ns0:invoice_id>
                           <xsl:for-each select="ns0:InvoiceInstallment">
                              <ns0:InvoiceInstallment>
                                 <xsl:if test="/ns0:UpdateSupplierInvoicesInstallmentsAPRs/cmn:Errors">
                                    <cmn:Errors>
                                       <xsl:for-each select="/ns0:UpdateSupplierInvoicesInstallmentsAPRs/cmn:Errors/cmn:Error">
                                          <cmn:Error>
                                             <cmn:ErrorCode>
                                                <xsl:value-of select="cmn:ErrorCode"/>
                                             </cmn:ErrorCode>
                                             <cmn:ShortDescription>
                                                <xsl:value-of select="cmn:ShortDescription"/>
                                             </cmn:ShortDescription>
                                             <cmn:Description>
                                                <xsl:value-of select="cmn:Description"/>
                                             </cmn:Description>
                                             <cmn:BusinessProcess>
                                                <xsl:value-of select="cmn:BusinessProcess"/>
                                             </cmn:BusinessProcess>
                                             <cmn:FailedService>
                                                <xsl:value-of select="cmn:FailedService"/>
                                             </cmn:FailedService>
                                             <cmn:TimeStamp>
                                                <xsl:value-of select="cmn:TimeStamp"/>
                                             </cmn:TimeStamp>
                                          </cmn:Error>
                                       </xsl:for-each>
                                    </cmn:Errors>
                                 </xsl:if>
                                 <ns0:Result>
                                    <xsl:if test="ns0:Result/inv:BankAccount">
                                       <inv:BankAccount>
                                          <xsl:value-of select="ns0:Result/inv:BankAccount"/>
                                       </inv:BankAccount>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:CreatedBy">
                                       <inv:CreatedBy>
                                          <xsl:value-of select="ns0:Result/inv:CreatedBy"/>
                                       </inv:CreatedBy>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:CreationDate">
                                       <inv:CreationDate>
                                          <xsl:value-of select="ns0:Result/inv:CreationDate"/>
                                       </inv:CreationDate>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:DueDate">
                                       <inv:DueDate>
                                          <xsl:value-of select="ns0:Result/inv:DueDate"/>
                                       </inv:DueDate>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:ExternalBankAccountId">
                                       <inv:ExternalBankAccountId>
                                          <xsl:value-of select="ns0:Result/inv:ExternalBankAccountId"/>
                                       </inv:ExternalBankAccountId>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:FirstDiscountAmount">
                                       <inv:FirstDiscountAmount>
                                          <xsl:value-of select="ns0:Result/inv:FirstDiscountAmount"/>
                                       </inv:FirstDiscountAmount>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:FirstDiscountDate">
                                       <inv:FirstDiscountDate>
                                          <xsl:value-of select="ns0:Result/inv:FirstDiscountDate"/>
                                       </inv:FirstDiscountDate>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:GrossAmount">
                                       <inv:GrossAmount>
                                          <xsl:value-of select="ns0:Result/inv:GrossAmount"/>
                                       </inv:GrossAmount>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:HeldBy">
                                       <inv:HeldBy>
                                          <xsl:value-of select="ns0:Result/inv:HeldBy"/>
                                       </inv:HeldBy>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:HoldDate">
                                       <inv:HoldDate>
                                          <xsl:value-of select="ns0:Result/inv:HoldDate"/>
                                       </inv:HoldDate>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:HoldFlag">
                                       <inv:HoldFlag>
                                          <xsl:value-of select="ns0:Result/inv:HoldFlag"/>
                                       </inv:HoldFlag>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:HoldReason">
                                       <inv:HoldReason>
                                          <xsl:value-of select="ns0:Result/inv:HoldReason"/>
                                       </inv:HoldReason>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:HoldType">
                                       <inv:HoldType>
                                          <xsl:value-of select="ns0:Result/inv:HoldType"/>
                                       </inv:HoldType>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:InstallmentNumber">
                                       <inv:InstallmentNumber>
                                          <xsl:value-of select="ns0:Result/inv:InstallmentNumber"/>
                                       </inv:InstallmentNumber>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:LastUpdateDate">
                                       <inv:LastUpdateDate>
                                          <xsl:value-of select="ns0:Result/inv:LastUpdateDate"/>
                                       </inv:LastUpdateDate>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:LastUpdateLogin">
                                       <inv:LastUpdateLogin>
                                          <xsl:value-of select="ns0:Result/inv:LastUpdateLogin"/>
                                       </inv:LastUpdateLogin>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:LastUpdatedBy">
                                       <inv:LastUpdatedBy>
                                          <xsl:value-of select="ns0:Result/inv:LastUpdatedBy"/>
                                       </inv:LastUpdatedBy>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:NetAmountOne">
                                       <inv:NetAmountOne>
                                          <xsl:value-of select="ns0:Result/inv:NetAmountOne"/>
                                       </inv:NetAmountOne>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:NetAmountThree">
                                       <inv:NetAmountThree>
                                          <xsl:value-of select="ns0:Result/inv:NetAmountThree"/>
                                       </inv:NetAmountThree>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:NetAmountTwo">
                                       <inv:NetAmountTwo>
                                          <xsl:value-of select="ns0:Result/inv:NetAmountTwo"/>
                                       </inv:NetAmountTwo>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:PaymentMethod">
                                       <inv:PaymentMethod>
                                          <xsl:value-of select="ns0:Result/inv:PaymentMethod"/>
                                       </inv:PaymentMethod>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:PaymentMethodCode">
                                       <inv:PaymentMethodCode>
                                          <xsl:value-of select="ns0:Result/inv:PaymentMethodCode"/>
                                       </inv:PaymentMethodCode>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:PaymentPriority">
                                       <inv:PaymentPriority>
                                          <xsl:value-of select="ns0:Result/inv:PaymentPriority"/>
                                       </inv:PaymentPriority>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:RemitToAddressName">
                                       <inv:RemitToAddressName>
                                          <xsl:value-of select="ns0:Result/inv:RemitToAddressName"/>
                                       </inv:RemitToAddressName>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:RemitToSupplier">
                                       <inv:RemitToSupplier>
                                          <xsl:value-of select="ns0:Result/inv:RemitToSupplier"/>
                                       </inv:RemitToSupplier>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:RemittanceMessageOne">
                                       <inv:RemittanceMessageOne>
                                          <xsl:value-of select="ns0:Result/inv:RemittanceMessageOne"/>
                                       </inv:RemittanceMessageOne>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:RemittanceMessageThree">
                                       <inv:RemittanceMessageThree>
                                          <xsl:value-of select="ns0:Result/inv:RemittanceMessageThree"/>
                                       </inv:RemittanceMessageThree>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:RemittanceMessageTwo">
                                       <inv:RemittanceMessageTwo>
                                          <xsl:value-of select="ns0:Result/inv:RemittanceMessageTwo"/>
                                       </inv:RemittanceMessageTwo>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:SecondDiscountAmount">
                                       <inv:SecondDiscountAmount>
                                          <xsl:value-of select="ns0:Result/inv:SecondDiscountAmount"/>
                                       </inv:SecondDiscountAmount>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:SecondDiscountDate">
                                       <inv:SecondDiscountDate>
                                          <xsl:value-of select="ns0:Result/inv:SecondDiscountDate"/>
                                       </inv:SecondDiscountDate>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:ThirdDiscountAmount">
                                       <inv:ThirdDiscountAmount>
                                          <xsl:value-of select="ns0:Result/inv:ThirdDiscountAmount"/>
                                       </inv:ThirdDiscountAmount>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:ThirdDiscountDate">
                                       <inv:ThirdDiscountDate>
                                          <xsl:value-of select="ns0:Result/inv:ThirdDiscountDate"/>
                                       </inv:ThirdDiscountDate>
                                    </xsl:if>
                                    <xsl:if test="ns0:Result/inv:UnpaidAmount">
                                       <inv:UnpaidAmount>
                                          <xsl:value-of select="ns0:Result/inv:UnpaidAmount"/>
                                       </inv:UnpaidAmount>
                                    </xsl:if>
                                    <xsl:for-each select="ns0:Result/inv:links">
                                       <inv:links>
                                          <xsl:if test="inv:href">
                                             <inv:href>
                                                <xsl:value-of select="inv:href"/>
                                             </inv:href>
                                          </xsl:if>
                                          <xsl:if test="inv:kind">
                                             <inv:kind>
                                                <xsl:value-of select="inv:kind"/>
                                             </inv:kind>
                                          </xsl:if>
                                          <xsl:if test="inv:name">
                                             <inv:name>
                                                <xsl:value-of select="inv:name"/>
                                             </inv:name>
                                          </xsl:if>
                                          <xsl:if test="inv:properties">
                                             <inv:properties>
                                                <xsl:if test="inv:properties/inv:changeIndicator">
                                                   <inv:changeIndicator>
                                                      <xsl:value-of select="inv:properties/inv:changeIndicator"/>
                                                   </inv:changeIndicator>
                                                </xsl:if>
                                             </inv:properties>
                                          </xsl:if>
                                          <xsl:if test="inv:rel">
                                             <inv:rel>
                                                <xsl:value-of select="inv:rel"/>
                                             </inv:rel>
                                          </xsl:if>
                                       </inv:links>
                                    </xsl:for-each>
                                 </ns0:Result>
                              </ns0:InvoiceInstallment>
                           </xsl:for-each>
                        </ns0:invoice>
                     </xsl:for-each>
                  </ns0:invoice>
               </xsl:for-each>
            </ns0:Supplier>
         </xsl:for-each>
            <ns0:Supplier>
            <xsl:if test="$BpelUpdateInvoicesInstallmentsAPRs.payload/ns0:UpdateInvoicesInstallmentsAPRs">
               <ns0:invoices>
                  <cmn:Success>
                     <xsl:value-of select="$BpelUpdateInvoicesInstallmentsAPRs.payload/ns0:UpdateInvoicesInstallmentsAPRs/ns0:invoice/ns0:invoice_id"/>
                  </cmn:Success>
                  <xsl:if test="$BpelUpdateInvoicesInstallmentsAPRs.payload/ns0:UpdateInvoicesInstallmentsAPRs/cmn:Errors">
                     <cmn:Errors>
                        <xsl:for-each select="$BpelUpdateInvoicesInstallmentsAPRs.payload/ns0:UpdateInvoicesInstallmentsAPRs/cmn:Errors/cmn:Error">
                           <cmn:Error>
                              <cmn:ErrorCode>
                                 <xsl:value-of select="cmn:ErrorCode"/>
                              </cmn:ErrorCode>
                              <cmn:ShortDescription>
                                 <xsl:value-of select="cmn:ShortDescription"/>
                              </cmn:ShortDescription>
                              <cmn:Description>
                                 <xsl:value-of select="cmn:Description"/>
                              </cmn:Description>
                              <cmn:BusinessProcess>
                                 <xsl:value-of select="cmn:BusinessProcess"/>
                              </cmn:BusinessProcess>
                              <cmn:FailedService>
                                 <xsl:value-of select="cmn:FailedService"/>
                              </cmn:FailedService>
                              <cmn:TimeStamp>
                                 <xsl:value-of select="cmn:TimeStamp"/>
                              </cmn:TimeStamp>
                           </cmn:Error>
                        </xsl:for-each>
                     </cmn:Errors>
                  </xsl:if>
                  <xsl:for-each select="$BpelUpdateInvoicesInstallmentsAPRs.payload/ns0:UpdateInvoicesInstallmentsAPRs/ns0:invoice">
                     <ns0:invoice>
                        <ns0:invoice_id>
                           <xsl:value-of select="ns0:invoice_id"/>
                        </ns0:invoice_id>
                        <xsl:for-each select="ns0:InvoiceInstallment">
                           <ns0:InvoiceInstallment>
                              <xsl:if test="$BpelUpdateInvoicesInstallmentsAPRs.payload/ns0:UpdateInvoicesInstallmentsAPRs/cmn:Errors">
                                 <cmn:Errors>
                                    <xsl:for-each select="$BpelUpdateInvoicesInstallmentsAPRs.payload/ns0:UpdateInvoicesInstallmentsAPRs/cmn:Errors/cmn:Error">
                                       <cmn:Error>
                                          <cmn:ErrorCode>
                                             <xsl:value-of select="cmn:ErrorCode"/>
                                          </cmn:ErrorCode>
                                          <cmn:ShortDescription>
                                             <xsl:value-of select="cmn:ShortDescription"/>
                                          </cmn:ShortDescription>
                                          <cmn:Description>
                                             <xsl:value-of select="cmn:Description"/>
                                          </cmn:Description>
                                          <cmn:BusinessProcess>
                                             <xsl:value-of select="cmn:BusinessProcess"/>
                                          </cmn:BusinessProcess>
                                          <cmn:FailedService>
                                             <xsl:value-of select="cmn:FailedService"/>
                                          </cmn:FailedService>
                                          <cmn:TimeStamp>
                                             <xsl:value-of select="cmn:TimeStamp"/>
                                          </cmn:TimeStamp>
                                       </cmn:Error>
                                    </xsl:for-each>
                                 </cmn:Errors>
                              </xsl:if>
                              <ns0:Result>
                                 <xsl:if test="ns0:Result/inv:BankAccount">
                                    <inv:BankAccount>
                                       <xsl:value-of select="ns0:Result/inv:BankAccount"/>
                                    </inv:BankAccount>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:CreatedBy">
                                    <inv:CreatedBy>
                                       <xsl:value-of select="ns0:Result/inv:CreatedBy"/>
                                    </inv:CreatedBy>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:CreationDate">
                                    <inv:CreationDate>
                                       <xsl:value-of select="ns0:Result/inv:CreationDate"/>
                                    </inv:CreationDate>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:DueDate">
                                    <inv:DueDate>
                                       <xsl:value-of select="ns0:Result/inv:DueDate"/>
                                    </inv:DueDate>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:ExternalBankAccountId">
                                    <inv:ExternalBankAccountId>
                                       <xsl:value-of select="ns0:Result/inv:ExternalBankAccountId"/>
                                    </inv:ExternalBankAccountId>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:FirstDiscountAmount">
                                    <inv:FirstDiscountAmount>
                                       <xsl:value-of select="ns0:Result/inv:FirstDiscountAmount"/>
                                    </inv:FirstDiscountAmount>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:FirstDiscountDate">
                                    <inv:FirstDiscountDate>
                                       <xsl:value-of select="ns0:Result/inv:FirstDiscountDate"/>
                                    </inv:FirstDiscountDate>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:GrossAmount">
                                    <inv:GrossAmount>
                                       <xsl:value-of select="ns0:Result/inv:GrossAmount"/>
                                    </inv:GrossAmount>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:HeldBy">
                                    <inv:HeldBy>
                                       <xsl:value-of select="ns0:Result/inv:HeldBy"/>
                                    </inv:HeldBy>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:HoldDate">
                                    <inv:HoldDate>
                                       <xsl:value-of select="ns0:Result/inv:HoldDate"/>
                                    </inv:HoldDate>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:HoldFlag">
                                    <inv:HoldFlag>
                                       <xsl:value-of select="ns0:Result/inv:HoldFlag"/>
                                    </inv:HoldFlag>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:HoldReason">
                                    <inv:HoldReason>
                                       <xsl:value-of select="ns0:Result/inv:HoldReason"/>
                                    </inv:HoldReason>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:HoldType">
                                    <inv:HoldType>
                                       <xsl:value-of select="ns0:Result/inv:HoldType"/>
                                    </inv:HoldType>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:InstallmentNumber">
                                    <inv:InstallmentNumber>
                                       <xsl:value-of select="ns0:Result/inv:InstallmentNumber"/>
                                    </inv:InstallmentNumber>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:LastUpdateDate">
                                    <inv:LastUpdateDate>
                                       <xsl:value-of select="ns0:Result/inv:LastUpdateDate"/>
                                    </inv:LastUpdateDate>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:LastUpdateLogin">
                                    <inv:LastUpdateLogin>
                                       <xsl:value-of select="ns0:Result/inv:LastUpdateLogin"/>
                                    </inv:LastUpdateLogin>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:LastUpdatedBy">
                                    <inv:LastUpdatedBy>
                                       <xsl:value-of select="ns0:Result/inv:LastUpdatedBy"/>
                                    </inv:LastUpdatedBy>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:NetAmountOne">
                                    <inv:NetAmountOne>
                                       <xsl:value-of select="ns0:Result/inv:NetAmountOne"/>
                                    </inv:NetAmountOne>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:NetAmountThree">
                                    <inv:NetAmountThree>
                                       <xsl:value-of select="ns0:Result/inv:NetAmountThree"/>
                                    </inv:NetAmountThree>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:NetAmountTwo">
                                    <inv:NetAmountTwo>
                                       <xsl:value-of select="ns0:Result/inv:NetAmountTwo"/>
                                    </inv:NetAmountTwo>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:PaymentMethod">
                                    <inv:PaymentMethod>
                                       <xsl:value-of select="ns0:Result/inv:PaymentMethod"/>
                                    </inv:PaymentMethod>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:PaymentMethodCode">
                                    <inv:PaymentMethodCode>
                                       <xsl:value-of select="ns0:Result/inv:PaymentMethodCode"/>
                                    </inv:PaymentMethodCode>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:PaymentPriority">
                                    <inv:PaymentPriority>
                                       <xsl:value-of select="ns0:Result/inv:PaymentPriority"/>
                                    </inv:PaymentPriority>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:RemitToAddressName">
                                    <inv:RemitToAddressName>
                                       <xsl:value-of select="ns0:Result/inv:RemitToAddressName"/>
                                    </inv:RemitToAddressName>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:RemitToSupplier">
                                    <inv:RemitToSupplier>
                                       <xsl:value-of select="ns0:Result/inv:RemitToSupplier"/>
                                    </inv:RemitToSupplier>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:RemittanceMessageOne">
                                    <inv:RemittanceMessageOne>
                                       <xsl:value-of select="ns0:Result/inv:RemittanceMessageOne"/>
                                    </inv:RemittanceMessageOne>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:RemittanceMessageThree">
                                    <inv:RemittanceMessageThree>
                                       <xsl:value-of select="ns0:Result/inv:RemittanceMessageThree"/>
                                    </inv:RemittanceMessageThree>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:RemittanceMessageTwo">
                                    <inv:RemittanceMessageTwo>
                                       <xsl:value-of select="ns0:Result/inv:RemittanceMessageTwo"/>
                                    </inv:RemittanceMessageTwo>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:SecondDiscountAmount">
                                    <inv:SecondDiscountAmount>
                                       <xsl:value-of select="ns0:Result/inv:SecondDiscountAmount"/>
                                    </inv:SecondDiscountAmount>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:SecondDiscountDate">
                                    <inv:SecondDiscountDate>
                                       <xsl:value-of select="ns0:Result/inv:SecondDiscountDate"/>
                                    </inv:SecondDiscountDate>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:ThirdDiscountAmount">
                                    <inv:ThirdDiscountAmount>
                                       <xsl:value-of select="ns0:Result/inv:ThirdDiscountAmount"/>
                                    </inv:ThirdDiscountAmount>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:ThirdDiscountDate">
                                    <inv:ThirdDiscountDate>
                                       <xsl:value-of select="ns0:Result/inv:ThirdDiscountDate"/>
                                    </inv:ThirdDiscountDate>
                                 </xsl:if>
                                 <xsl:if test="ns0:Result/inv:UnpaidAmount">
                                    <inv:UnpaidAmount>
                                       <xsl:value-of select="ns0:Result/inv:UnpaidAmount"/>
                                    </inv:UnpaidAmount>
                                 </xsl:if>
                                 <xsl:for-each select="ns0:Result/inv:links">
                                    <inv:links>
                                       <xsl:if test="inv:href">
                                          <inv:href>
                                             <xsl:value-of select="inv:href"/>
                                          </inv:href>
                                       </xsl:if>
                                       <xsl:if test="inv:kind">
                                          <inv:kind>
                                             <xsl:value-of select="inv:kind"/>
                                          </inv:kind>
                                       </xsl:if>
                                       <xsl:if test="inv:name">
                                          <inv:name>
                                             <xsl:value-of select="inv:name"/>
                                          </inv:name>
                                       </xsl:if>
                                       <xsl:if test="inv:properties">
                                          <inv:properties>
                                             <xsl:if test="inv:properties/inv:changeIndicator">
                                                <inv:changeIndicator>
                                                   <xsl:value-of select="inv:properties/inv:changeIndicator"/>
                                                </inv:changeIndicator>
                                             </xsl:if>
                                          </inv:properties>
                                       </xsl:if>
                                       <xsl:if test="inv:rel">
                                          <inv:rel>
                                             <xsl:value-of select="inv:rel"/>
                                          </inv:rel>
                                       </xsl:if>
                                    </inv:links>
                                 </xsl:for-each>
                              </ns0:Result>
                           </ns0:InvoiceInstallment>
                        </xsl:for-each>
                     </ns0:invoice>
                  </xsl:for-each>
               </ns0:invoices>
            </xsl:if>
         </ns0:Supplier>
               
      </ns0:UpdateSupplierInvoicesInstallmentsAPRs>
   </xsl:template>
</xsl:stylesheet>
