--------------------------------------------------------
-- Archivo creado  - martes-febrero-13-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXER_EAM_DATA_EXCEL_TBL
--------------------------------------------------------

  CREATE TABLE "XXER_EAM_DATA_EXCEL_TBL" 
   (	"ASSET_NUMBER" VARCHAR2(40 BYTE), 
	"ORIGIN" VARCHAR2(20 BYTE) DEFAULT 'EXCEL', 
	"READING_DATE" VARCHAR2(40 BYTE), 
	"READING_VALUE" NUMBER, 
	"STATUS" VARCHAR2(15 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "XERINTUSER_TBS" ;
