WITH
TXN AS (SELECT H.NUMERO_DOCUMENTO , TRUNC(H.FECHA_MOVIMIENTO) FECHA_MOVIMIENTO , H.NOMBRE_FISCAL_ORIGEN , H.SISTEMA_ORIGEN , H.TIPO_DOCUMENTO , H.TIPO_MOVIMIENTO , H.SUCURSAL_VENTA , L.ORIGEN_SERVICIO 
		, L.DESTINO_SERVICIO , L.SERVICIO , L.CONCEPTO_MODALIDAD , L.FORMA_PAGO , H.RFC_ORIGEN , H.ADICIONAL1 , H.ADICIONAL3 , H.ADICIONAL4 , H.ADICIONAL5 , H.ADICIONAL6
		 , H.ADICIONAL7 , H.ADICIONAL8 , H.ADICIONAL9 , H.ADICIONAL10 ,H.TABLA_PUENTE_ID ,L.TABLA_PUENTE_LINEA_ID ,L.TOTAL
		FROM XXER_TBL_PUENTE_HEADER H, XXER_TBL_PUENTE_LINES L WHERE H.TABLA_PUENTE_ID = L.TABLA_PUENTE_ID AND H.SISTEMA_ORIGEN NOT IN ('EAM', 'INV', 'PORTAL')
        AND H.TIPO_DOCUMENTO NOT IN ('RECIBO', 'REVERSO RECIBO')
		AND TRUNC(H.FECHA_MOVIMIENTO) BETWEEN  TO_DATE(:P57_FECHA_INICIO,'DD/MM/RRRR') and TO_DATE(NVL(:P57_FECHA_FIN,:P57_FECHA_INICIO),'DD/MM/RRRR')
		)
,CNF as (
select NVL(REGEXP_SUBSTR(cf3.METODO_RECIBO,'[^,]+'),cf3.METODO_RECIBO) METODO_RECIBO_M,
NVL(REGEXP_SUBSTR(cf3.CONCILIACION,'[^,]+'),cf3.CONCILIACION) CONCILIACION_M,
NVL(REGEXP_SUBSTR(cf3.MASCARA_CONC,'[^,]+'),cf3.MASCARA_CONC) MASCARA_CONC_M,
NVL(REGEXP_SUBSTR(cf3.SUBFIJO_CONC,'[^,]+'),cf3.SUBFIJO_CONC) SUBFIJO_CONC_M,
NVL(REGEXP_SUBSTR(cf3.FRECUENCIA_CONC,'[^,]+'),cf3.FRECUENCIA_CONC) FRECUENCIA_CONC_M,
NVL(REGEXP_SUBSTR(cf3.TOLERANCIA_CONC,'[^,]+'),cf3.TOLERANCIA_CONC) TOLERANCIA_CONC_M,
 cf2.prefijo_conc PREFIJO_CONC_M ,
         cf3.MEMO_LINE,cf3.TIPO_TRANSACCION_AR,cf3.ID_INTERFAZ,cf3.ORGANIZATION_ID, cf3.RECEIPT_METHOD_ID,cf3.SISTEMA_ORIGEN,cf3.TIPO_DOCUMENTO,
cf3.TIPO_MOVIMIENTO,cf3.SUCURSAL_VENTA,cf3.RFC_ORIGEN,cf3.ORIGEN_SERVICIO,cf3.DESTINO_SERVICIO,cf3.SERVICIO,cf3.FORMA_PAGO,cf3.CONCEPTO_MODALIDAD,cf3.ADICIONAL1,
cf3.ADICIONAL2,cf3.ADICIONAL3,cf3.ADICIONAL4,cf3.ADICIONAL5,cf3.ADICIONAL6,cf3.ADICIONAL7,cf3.ADICIONAL8,cf3.ADICIONAL9,cf3.ADICIONAL10 
from XXER_AR_CONC_ID_V cf2 
inner join xxer_cnf_interfase_ingresos_ar cf3 on cf3.id_interfaz=cf2.id_interfaz
)
SELECT 
    RPC.ID_INTERFAZ
    ,RPC.NUMERO_DOCUMENTO
    ,RPC.FECHA_MOVIMIENTO
	,RPC.NOMBRE_FISCAL_ORIGEN
    ,RPC.TOTAL
	,RPC.SISTEMA_ORIGEN
	,RPC.TIPO_DOCUMENTO
	,RPC.TIPO_MOVIMIENTO
	,RPC.SUCURSAL_VENTA
	,RPC.ORIGEN_SERVICIO
	,RPC.DESTINO_SERVICIO
	,RPC.SERVICIO
	,RPC.CONCEPTO_MODALIDAD
	,RPC.FORMA_PAGO
    ,RPC.REGISTROS
    ,RPC.TABLA_PUENTE_ID
    ,RPC.TABLA_PUENTE_LINEA_ID
    ,RPC.TIPO_TRANSACCION_AR
    ,RPC.MEMO_LINE
    ,RPC.CONCILIACION
	,TCO.FECHA_PAGO
	,RPC.METODO_RECIBO_M as "METODO RECIBO"
	,RPC.REFERENCE_PAYMENT "REFERENCIA CONFIGURADA"
    ,RPC."FRECUENCIA CONCILIACION"
    ,TCO.AMOUNT_TRANSACTIONS "TOTAL TRANSACCIONES TP"	
	,TCO.AMOUNT_PAYMENT "MONTO PAGO CASH"
	,(TCO.AMOUNT_TRANSACTIONS-TCO.AMOUNT_PAYMENT) AS "DIFERENCIA CONCILIACION"
	,TCO.STATUS "ESTATUS CONCILIACION"
	,TCO.MSJ_VALIDATION "DESCRIPCION ESTATUS CONCILIACION"
	,TCO.PAYMENT_NUMBER "REFERENCIA PAGO CASH"
FROM (
SELECT
	 CNF.ID_INTERFAZ
    ,TXN.NUMERO_DOCUMENTO
    ,TXN.FECHA_MOVIMIENTO
	,TXN.NOMBRE_FISCAL_ORIGEN
    ,TXN.TOTAL
	,TXN.SISTEMA_ORIGEN
	,TXN.TIPO_DOCUMENTO
	,TXN.TIPO_MOVIMIENTO
	,TXN.SUCURSAL_VENTA
	,TXN.ORIGEN_SERVICIO
	,TXN.DESTINO_SERVICIO
	,TXN.SERVICIO
	,TXN.CONCEPTO_MODALIDAD
	,TXN.FORMA_PAGO
    ,SUM(1) OVER (PARTITION BY TXN.TABLA_PUENTE_ID ,TXN.TABLA_PUENTE_LINEA_ID) REGISTROS
    ,TXN.TABLA_PUENTE_ID
    ,TXN.TABLA_PUENTE_LINEA_ID
    ,CNF.TIPO_TRANSACCION_AR
    ,CNF.MEMO_LINE
    ,NVL(CNF.CONCILIACION_M,'NO') CONCILIACION
	,CNF.METODO_RECIBO_M 
    ,CNF.FRECUENCIA_CONC_M AS "FRECUENCIA CONCILIACION"
    ,DECODE(CNF.CONCILIACION_M,'SI',NVL(CNF.TOLERANCIA_CONC_M,10),NULL) AS "TOLERANCIA CONCILIACION"
    ,(CASE
        WHEN SUBSTR(CNF.PREFIJO_CONC_M,1,4) = 'AFIL' THEN 
            CNF.PREFIJO_CONC_M||
			TO_CHAR(TO_DATE(TXN.FECHA_MOVIMIENTO)+
            (CASE MOD(TO_CHAR(TXN.FECHA_MOVIMIENTO,'J'),7)
            WHEN 4
            THEN 3
            WHEN 5
            THEN 2
            ELSE 1 END)
            ,CNF.MASCARA_CONC_M)||CNF.SUBFIJO_CONC_M
		WHEN SUBSTR(CNF.PREFIJO_CONC_M,1,9) = 'AMEXCO SE' THEN 
            CNF.PREFIJO_CONC_M||
			TO_CHAR(TO_DATE(TXN.FECHA_MOVIMIENTO)+
            (CASE MOD(TO_CHAR(TXN.FECHA_MOVIMIENTO,'J'),7)
            WHEN 4
            THEN 3
            WHEN 5
            THEN 2
            ELSE 1 END)
            ,CNF.MASCARA_CONC_M)||CNF.SUBFIJO_CONC_M
        ELSE
        (case
        WHEN CNF.FRECUENCIA_CONC_M = 'D' THEN CNF.PREFIJO_CONC_M||TO_CHAR(TXN.FECHA_MOVIMIENTO,CNF.MASCARA_CONC_M)||CNF.SUBFIJO_CONC_M
        WHEN CNF.FRECUENCIA_CONC_M = 'S' THEN CNF.PREFIJO_CONC_M||TO_CHAR(TXN.FECHA_MOVIMIENTO+(6-MOD(TO_CHAR(TXN.FECHA_MOVIMIENTO,'J'),7)),CNF.MASCARA_CONC_M)||CNF.SUBFIJO_CONC_M
        ELSE NULL END)
        end) as REFERENCE_PAYMENT 		
FROM TXN
    LEFT JOIN CNF ON NVL (TXN.SISTEMA_ORIGEN, 1) = NVL (CNF.SISTEMA_ORIGEN, 1)
         AND NVL (TXN.TIPO_DOCUMENTO, 1) = NVL (CNF.TIPO_DOCUMENTO, 1)
         AND NVL (TXN.TIPO_MOVIMIENTO, 1) = NVL (CNF.TIPO_MOVIMIENTO, 1)
         AND NVL (TXN.RFC_ORIGEN, 1) = DECODE (NVL (CNF.SISTEMA_ORIGEN, 1),'NOMINA', NVL (TXN.RFC_ORIGEN, 1),NVL (CNF.RFC_ORIGEN, 1))
         AND NVL (TXN.SUCURSAL_VENTA, 1) = DECODE (NVL (CNF.SUCURSAL_VENTA, 1),'TODOS', NVL (TXN.SUCURSAL_VENTA, 1),NVL (CNF.SUCURSAL_VENTA, 1))
         AND NVL (TXN.ORIGEN_SERVICIO, 1) = DECODE (NVL (CNF.ORIGEN_SERVICIO, 1),'TODOS', NVL (TXN.ORIGEN_SERVICIO, 1),NVL (CNF.ORIGEN_SERVICIO, 1))
         AND NVL (TXN.DESTINO_SERVICIO, 1) = DECODE (NVL (CNF.DESTINO_SERVICIO, 1),'TODOS', NVL (TXN.DESTINO_SERVICIO, 1),NVL (CNF.DESTINO_SERVICIO, 1))
         AND NVL (TXN.SERVICIO, 1) = DECODE (NVL (CNF.SERVICIO, 1),'TODOS', NVL (TXN.SERVICIO, 1),NVL (CNF.SERVICIO, 1))
         AND NVL (TXN.CONCEPTO_MODALIDAD, 1) = NVL (CNF.CONCEPTO_MODALIDAD, 1) 
         AND NVL (TXN.FORMA_PAGO, 1) = DECODE (NVL (CNF.FORMA_PAGO, 1),'TODOS', NVL (TXN.FORMA_PAGO, 1),NVL (CNF.FORMA_PAGO, 1))
         AND NVL (TXN.ADICIONAL1, 1) = NVL (CNF.ADICIONAL1, 1)
         AND NVL (TXN.ADICIONAL3, 1) = NVL (CNF.ADICIONAL3, 1)
         AND NVL (TXN.ADICIONAL4, 1) = NVL (CNF.ADICIONAL4, 1)
         AND NVL (TXN.ADICIONAL5, 1) = NVL (CNF.ADICIONAL5, 1)
         AND NVL (TXN.ADICIONAL6, 1) = NVL (CNF.ADICIONAL6, 1)
         AND NVL (TXN.ADICIONAL7, 1) = NVL (CNF.ADICIONAL7, 1)
         AND NVL (TXN.ADICIONAL8, 1) = NVL (CNF.ADICIONAL8, 1)
         AND NVL (TXN.ADICIONAL9, 1) = NVL (CNF.ADICIONAL9, 1)
         AND NVL (TXN.ADICIONAL10, 1) = NVL (CNF.ADICIONAL10, 1)
WHERE 1=1
AND CNF.CONCILIACION_M = 'SI'
) RPC
    LEFT JOIN XXER_AR_CONCILIACION_TBL TCO ON RPC.REFERENCE_PAYMENT = TCO.REFERENCE_PAYMENT 
	AND RPC.METODO_RECIBO_M = TCO.METODO_RECIBO;