--Elimina los datos del dia especificado.Ejecutar en el ambiente donde se desee realizar la limpieza

delete  XXER_TBL_PUENTE_AUXILIAR where TABLA_PUENTE_AUXILIAR_ID in (
		  SELECT A1.TABLA_PUENTE_AUXILIAR_ID 
          FROM XXER.XXER_TBL_PUENTE_AUXILIAR@SUMASII_LINK.ESTRELLAROJA.COM.MX A1,
          XXER.XXER_TBL_PUENTE_HEADER@SUMASII_LINK.ESTRELLAROJA.COM.MX H1,
          XXER.XXER_TBL_PUENTE_LINES@SUMASII_LINK.ESTRELLAROJA.COM.MX L1
          WHERE L1.TABLA_PUENTE_ID = H1.TABLA_PUENTE_ID
          AND TRUNC(H1.FECHA_MOVIMIENTO)= TRUNC(SYSDATE-2)--dia a eliminar
          AND A1.TABLA_PUENTE_LINEA_ID = L1.TABLA_PUENTE_LINEA_ID
          );
          

DELETE XXER_TBL_PUENTE_LINES WHERE TABLA_PUENTE_LINEA_ID in (
 SELECT L1.TABLA_PUENTE_LINEA_ID
             FROM XXER.XXER_TBL_PUENTE_LINES@SUMASII_LINK.ESTRELLAROJA.COM.MX L1,
             XXER.XXER_TBL_PUENTE_HEADER@SUMASII_LINK.ESTRELLAROJA.COM.MX H1 
             WHERE L1.TABLA_PUENTE_ID = H1.TABLA_PUENTE_ID
             AND TRUNC(H1.FECHA_MOVIMIENTO) = TRUNC(SYSDATE-2)--dia a eliminar
);


DELETE XXER_TBL_PUENTE_HEADER WHERE TABLA_PUENTE_ID IN(
SELECT TABLA_PUENTE_ID
FROM XXER.XXER_TBL_PUENTE_HEADER@SUMASII_LINK.ESTRELLAROJA.COM.MX H1 
           WHERE TRUNC(H1.FECHA_MOVIMIENTO)  = TRUNC(SYSDATE-2)--dia a eliminar
);

COMMIT;