--Replicamos la configuracion XXER_CNF_INTERFASE_INGRESOS_AR de PROD a TEST
--Se puede ejecutar en TEST o PROD


TRUNCATE TABLE  "XERINTUSER".XXER_CNF_INTERFASE_INGRESOS_AR;
COMMIT;
INSERT INTO "XERINTUSER".XXER_CNF_INTERFASE_INGRESOS_AR
          (Select * from "PXERINTUSER".XXER_CNF_INTERFASE_INGRESOS_AR);
COMMIT;
