--Consulta muestra los datos del ambiente donde sea EJECUTADO
SELECT H.ADICIONAL2
	,H.ESTATUS
	,H.FECHA_MOVIMIENTO
	,H.NUMERO_DOCUMENTO
	,H.RFC_DESTINO
	,H.SISTEMA_ORIGEN
	,H.TABLA_PUENTE_ID
	,L.TABLA_PUENTE_LINEA_ID AS TABLA_PUENTE_LINEA_ID_P
	,H.TIPO_DOCUMENTO
	,H.ADICIONAL1
	,H.ADICIONAL10
	,H.ADICIONAL9
	,H.ADICIONAL8
	,H.ADICIONAL7
	,H.ADICIONAL6
	,H.ADICIONAL5
	,H.ADICIONAL4
	,H.ADICIONAL3
	,H.SUCURSAL_VENTA
	,H.RFC_ORIGEN
	,L.SERVICIO
	,L.DESTINO_SERVICIO
	,L.ORIGEN_SERVICIO
	,H.TIPO_MOVIMIENTO
	,L.CODIGO_IVA
	,L.LINEA_ARTICULO
	,'60' || L.TABLA_PUENTE_LINEA_ID AS TABLA_PUENTE_LINEA_ID
	,L.TASA_IVA
	,L.TOTAL
	,L.UNIDAD_MEDIDA
	,L.FORMA_PAGO
	,L.CONCEPTO_MODALIDAD
	,A.UUID
--,COUNT(1) OVER (PARTITION BY TABLA_PUENTE_LINEA_ID)
FROM XXER_TBL_PUENTE_HEADER H
	,XXER_TBL_PUENTE_LINES L
	,XXER_TBL_PUENTE_AUXILIAR A
WHERE H.TABLA_PUENTE_ID = L.TABLA_PUENTE_ID
	AND L.TABLA_PUENTE_LINEA_ID = A.TABLA_PUENTE_LINEA_ID (+)
	--AND NVL(ESTATUS, 'P') = 'P'
	AND LENGTH(NUMERO_DOCUMENTO) <= 20 --LAS TABLAS DE APOLO NO SOPORTAN UN DOCUMENTO MAYOR A 20 CARACTERES
	AND H.SISTEMA_ORIGEN NOT IN (
		'EAM'
		,'INV'
		,'PORTAL'
		)
	AND H.TIPO_DOCUMENTO NOT IN (
		'RECIBO'
		,'REVERSO RECIBO'
		)
--AND NUMERO_DOCUMENTO = '02222115E19PE12665F'

UNION ALL

SELECT H.ADICIONAL2
	,H.ESTATUS
	,H.FECHA_MOVIMIENTO
	,H.NUMERO_DOCUMENTO
	,H.RFC_DESTINO
	,H.SISTEMA_ORIGEN
	,H.TABLA_PUENTE_ID
	,L.TABLA_PUENTE_LINEA_ID AS TABLA_PUENTE_LINEA_ID_P
	,H.TIPO_DOCUMENTO
	,H.ADICIONAL1
	,H.ADICIONAL10
	,H.ADICIONAL9
	,H.ADICIONAL8
	,H.ADICIONAL7
	,H.ADICIONAL6
	,H.ADICIONAL5
	,H.ADICIONAL4
	,H.ADICIONAL3
	,H.SUCURSAL_VENTA
	,H.RFC_ORIGEN
	,L.SERVICIO
	,L.DESTINO_SERVICIO
	,L.ORIGEN_SERVICIO
	,H.TIPO_MOVIMIENTO
	,L.CODIGO_IVA
	,L.LINEA_ARTICULO
	,'50' || L.TABLA_PUENTE_LINEA_ID AS TABLA_PUENTE_LINEA_ID
	,L.TASA_IVA * - 1
	,L.TOTAL * - 1
	,L.UNIDAD_MEDIDA
	,L.FORMA_PAGO
	,'BONIFICACION SOB VENTA' AS CONCEPTO_MODALIDAD
	,A.UUID
--,COUNT(1) OVER (PARTITION BY TABLA_PUENTE_LINEA_ID)
FROM XXER_TBL_PUENTE_HEADER H
	,XXER_TBL_PUENTE_LINES L
	,XXER_TBL_PUENTE_AUXILIAR A
WHERE H.TABLA_PUENTE_ID = L.TABLA_PUENTE_ID
	AND L.TABLA_PUENTE_LINEA_ID = A.TABLA_PUENTE_LINEA_ID (+)
	--AND NVL(ESTATUS, 'P') = 'P'
	AND H.SISTEMA_ORIGEN NOT IN (
		'EAM'
		,'INV'
		,'PORTAL'
		)
	AND H.TIPO_DOCUMENTO NOT IN (
		'RECIBO'
		,'REVERSO RECIBO'
		)
	AND L.CONCEPTO_MODALIDAD = 'BONIFICACION'
