<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://impl.utilities.cloud.estrellaroja.com.mx/" xmlns:tns="http://soa.estrellaroja.com.mx/SOAUtilitiesTec" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 tns oraxsl"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:ns1="http://impl.utilities.cloud.estrellaroja.com.mx/types"
                xmlns:ns2="http://impl.utilities.cloud.estrellaroja.com.mx"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns3="http://soa.estrellaroja.com.mx/EstrellaRojaCommons"
                xmlns:ns4="http://soa.estrellaroja.com.mx/SOAUtilitiesTec/types">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SOAUtilitiesImpl.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DecompressFileResponse" namespace="http://impl.utilities.cloud.estrellaroja.com.mx/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SOAUtilitiesTec.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DecompressFileRs" namespace="http://soa.estrellaroja.com.mx/SOAUtilitiesTec"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [THU APR 11 18:49:04 CDT 2024].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:DecompressFileRs>
         <ns3:Success>
            <xsl:value-of select="/ns0:DecompressFileResponse/return/ns1:Success"/>
         </ns3:Success>
         <xsl:if test="/ns0:DecompressFileResponse/return/ns1:Errors">
            <ns3:Errors>
               <xsl:for-each select="/ns0:DecompressFileResponse/return/ns1:Errors/ns1:Error">
                  <ns3:Error>
                     <ns3:ErrorCode>
                        <xsl:value-of select="ns1:ErrorCode"/>
                     </ns3:ErrorCode>
                     <ns3:ShortDescription>
                        <xsl:value-of select="ns1:ShortDescription"/>
                     </ns3:ShortDescription>
                     <ns3:Description>
                        <xsl:value-of select="ns1:Description"/>
                     </ns3:Description>
                     <ns3:BusinessProcess>
                        <xsl:value-of select="ns1:BusinessProcess"/>
                     </ns3:BusinessProcess>
                     <ns3:FailedService>
                        <xsl:value-of select="ns1:FailedService"/>
                     </ns3:FailedService>
                     <ns3:TimeStamp>
                        <xsl:value-of select="ns1:TimeStamp"/>
                     </ns3:TimeStamp>
                  </ns3:Error>
               </xsl:for-each>
            </ns3:Errors>
         </xsl:if>
         <xsl:for-each select="/ns0:DecompressFileResponse/return/ns1:Return">
            <tns:Return>
               <tns:AttachmentType>
                  <xsl:value-of select="ns1:AttachmentType"/>
               </tns:AttachmentType>
               <tns:AttachmentContent>
                  <xsl:value-of select="ns1:AttachmentContent"/>
               </tns:AttachmentContent>
               <tns:FileName>
                  <xsl:value-of select="ns1:FileName"/>
               </tns:FileName>
            </tns:Return>
         </xsl:for-each>
      </tns:DecompressFileRs>
   </xsl:template>
</xsl:stylesheet>
