--------------------------------------------------------
-- Archivo creado  - jueves-marzo-07-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXER_CNF_INTERFASE_INGRESOS_AR
--------------------------------------------------------

  CREATE TABLE "XXER_CNF_INTERFASE_INGRESOS_AR" 
   (	"ID_INTERFAZ" NUMBER, 
	"CD_UNIDAD_OPERATIVA" NUMBER, 
	"UNIDAD_OPERATIVA" VARCHAR2(100 BYTE), 
	"SISTEMA_ORIGEN" VARCHAR2(30 BYTE), 
	"TIPO_DOCUMENTO" VARCHAR2(30 BYTE), 
	"TIPO_MOVIMIENTO" VARCHAR2(30 BYTE), 
	"COORDINADO" VARCHAR2(30 BYTE), 
	"IMPUESTO" VARCHAR2(25 BYTE), 
	"ORIGEN_TRANSACCION" VARCHAR2(30 BYTE), 
	"TIPO_TRANSACCION_AR" VARCHAR2(30 BYTE), 
	"METODO_RECIBO" VARCHAR2(300 BYTE), 
	"UNIDAD_NEGOCIO_ORIGEN" VARCHAR2(50 BYTE), 
	"NOMBRE_FISCAL_ORIGEN" VARCHAR2(50 BYTE), 
	"EMPRESA_ORIGEN" VARCHAR2(240 BYTE), 
	"RFC_ORIGEN" VARCHAR2(50 BYTE), 
	"UNIDAD_NEGOCIO_DESTINO" VARCHAR2(50 BYTE), 
	"NOMBRE_FISCAL_DESTINO" VARCHAR2(50 BYTE), 
	"EMPRESA_DESTINO" VARCHAR2(240 BYTE), 
	"RFC_DESTINO" VARCHAR2(50 BYTE), 
	"SUCURSAL_VENTA" VARCHAR2(240 BYTE), 
	"ORIGEN_SERVICIO" VARCHAR2(240 BYTE), 
	"DESTINO_SERVICIO" VARCHAR2(240 BYTE), 
	"SERVICIO" VARCHAR2(100 BYTE), 
	"CONCEPTO_MODALIDAD" VARCHAR2(50 BYTE), 
	"FORMA_PAGO" VARCHAR2(30 BYTE), 
	"SUMARIZADO" VARCHAR2(30 BYTE), 
	"APLICA_AR" VARCHAR2(30 BYTE), 
	"APLICA_AP" VARCHAR2(30 BYTE), 
	"CUENTA_INGRESOS" VARCHAR2(50 BYTE), 
	"CUENTA_COBRAR" VARCHAR2(50 BYTE), 
	"CUENTA_IMPUESTO" VARCHAR2(50 BYTE), 
	"CUENTA_RETENCION" VARCHAR2(50 BYTE), 
	"CUENTA_AP" VARCHAR2(50 BYTE), 
	"ADICIONAL1" VARCHAR2(80 BYTE), 
	"ADICIONAL2" VARCHAR2(80 BYTE), 
	"ADICIONAL3" VARCHAR2(80 BYTE), 
	"ADICIONAL4" VARCHAR2(80 BYTE), 
	"ADICIONAL5" VARCHAR2(80 BYTE), 
	"ADICIONAL6" VARCHAR2(80 BYTE), 
	"ADICIONAL7" VARCHAR2(80 BYTE), 
	"ADICIONAL8" VARCHAR2(80 BYTE), 
	"ADICIONAL9" VARCHAR2(80 BYTE), 
	"ADICIONAL10" VARCHAR2(80 BYTE), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"CUENTA_INGRESOS_DESC" VARCHAR2(240 BYTE), 
	"CUENTA_COBRAR_DESC" VARCHAR2(240 BYTE), 
	"CUENTA_IMPUESTO_DESC" VARCHAR2(240 BYTE), 
	"CUENTA_RETENCION_DESC" VARCHAR2(240 BYTE), 
	"CUENTA_AP_DESC" VARCHAR2(240 BYTE), 
	"MEMO_LINE" VARCHAR2(120 BYTE), 
	"RECEIPT_METHOD_ID" NUMBER, 
	"ORGANIZATION_ID" NUMBER, 
	"UNIDAD_OPERATIVA_DESTINO" VARCHAR2(100 BYTE), 
	"AP_TERCEROS" NUMBER, 
	"CONCILIACION" VARCHAR2(100 BYTE), 
	"PREFIJO_CONC" VARCHAR2(300 BYTE), 
	"MASCARA_CONC" VARCHAR2(200 BYTE), 
	"SUBFIJO_CONC" VARCHAR2(300 BYTE), 
	"FRECUENCIA_CONC" VARCHAR2(150 BYTE), 
	"TOLERANCIA_CONC" VARCHAR2(150 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Index XXER_CNF_INTERFASE_INGRESOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXER_CNF_INTERFASE_INGRESOS_PK" ON "XXER_CNF_INTERFASE_INGRESOS_AR" ("ID_INTERFAZ");
--------------------------------------------------------
--  DDL for Trigger XXER_CNF_INTERFASE_IMP_TGR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "XXER_CNF_INTERFASE_IMP_TGR" 
BEFORE INSERT
ON XXER_CNF_INTERFASE_INGRESOS_AR
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE

BEGIN
   
   CASE 
     WHEN :NEW.IMPUESTO = 'AR_IVA_EXENTO' THEN :NEW.IMPUESTO := 'TAS-IVAEXE';  
     WHEN :NEW.IMPUESTO = 'AR_IVA00' THEN :NEW.IMPUESTO := 'TAS-IVACERO';  
     WHEN :NEW.IMPUESTO = 'AR_IVA16' THEN :NEW.IMPUESTO := 'TAS-IVAAR16%';
     WHEN :NEW.IMPUESTO = 'AP_IVA_NO_GRAVADO' THEN :NEW.IMPUESTO := 'IMP-IVAAP';
     ELSE NULL;  
   END CASE;
   
   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END XXER_CNF_INTERFASE_IMP_TGR;


/
ALTER TRIGGER "XXER_CNF_INTERFASE_IMP_TGR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUDIT_TRIGGER_CONF
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "AUDIT_TRIGGER_CONF" BEFORE INSERT OR UPDATE
  ON XXER_CNF_INTERFASE_INGRESOS_AR FOR EACH ROW
DECLARE
  v_oranization_id number:=null;
  v_oranization_id_destino number:=null;
  v_rfc_origen varchar(20):=null;
BEGIN
  select organization_id, rfc_origen
  into v_oranization_id,v_rfc_origen
  from cat_business_units_tbl where short_code=:new.UNIDAD_OPERATIVA;
  if (:new.UNIDAD_OPERATIVA_DESTINO is null or :new.UNIDAD_OPERATIVA_DESTINO='-') 
    then v_oranization_id_destino:=null;
  else 
    select organization_id into v_oranization_id_destino
    from cat_business_units_tbl where short_code=:new.UNIDAD_OPERATIVA_DESTINO;
  end if; 
  IF INSERTING THEN
  :new.CREATION_DATE:=sysdate;
  :new.CREATED_BY:=APEX_UTIL.GET_CURRENT_USER_ID;
  :new.ORGANIZATION_ID:=v_oranization_id;
  :new.RFC_ORIGEN:=v_rfc_origen;
  :new.AP_TERCEROS:=v_oranization_id_destino;
  ELSIF UPDATING THEN
  :new.LAST_UPDATE_DATE:=sysdate;
  :new.LAST_UPDATED_BY:=APEX_UTIL.GET_CURRENT_USER_ID;
  :new.AP_TERCEROS:=v_oranization_id_destino;
  :new.ORGANIZATION_ID:=v_oranization_id;
  :new.RFC_ORIGEN:=v_rfc_origen;
  END IF;
END;

/
ALTER TRIGGER "AUDIT_TRIGGER_CONF" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ID_INTERFAZ_SEQ
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ID_INTERFAZ_SEQ" 
	BEFORE INSERT ON XXER_CNF_INTERFASE_INGRESOS_AR
	FOR EACH ROW
BEGIN
    IF :NEW.ID_INTERFAZ IS NULL THEN
		SELECT ID_INTERFAZ_S.NEXTVAL INTO :NEW.ID_INTERFAZ FROM SYS.DUAL;
	END IF;
END;


/
ALTER TRIGGER "ID_INTERFAZ_SEQ" ENABLE;
--------------------------------------------------------
--  Constraints for Table XXER_CNF_INTERFASE_INGRESOS_AR
--------------------------------------------------------

  ALTER TABLE "XXER_CNF_INTERFASE_INGRESOS_AR" MODIFY ("ID_INTERFAZ" NOT NULL ENABLE);
  ALTER TABLE "XXER_CNF_INTERFASE_INGRESOS_AR" ADD CONSTRAINT "XXER_CNF_INTERFASE_INGRESOS_PK" PRIMARY KEY ("ID_INTERFAZ");
