DROP TABLE  "PREPCONTROL"."ER_CTRL_API_TBL"  CASCADE CONSTRAINTS;    
commit;
DROP SEQUENCE "PREPCONTROL"."ER_CTRL_API_SEQ"; 
commit;

CREATE TABLE "PREPCONTROL"."ER_CTRL_API_TBL" 
   ("ID" NUMBER, 
   "TRANSACTION_NUMBER" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"API" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ESTATUS" VARCHAR2(100 BYTE), 
    "FECHA_CREACION" DATE , 
	"ULTIMA_FECHA_ACTUALIZACION" DATE , 
	 CONSTRAINT "ER_CTRL_API_TBL_PK" PRIMARY KEY ("TRANSACTION_NUMBER", "API"))
  TABLESPACE "REPCONTROL_DATA_TBS" ;
commit;
CREATE SEQUENCE  "PREPCONTROL"."ER_CTRL_API_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
commit;
  CREATE OR REPLACE  TRIGGER "PREPCONTROL"."AUDIT_TRIGGER_ER_CTRL_API_TBL" BEFORE INSERT OR UPDATE
  ON "PREPCONTROL"."ER_CTRL_API_TBL" FOR EACH ROW
  DECLARE
BEGIN
  IF INSERTING THEN
  IF :new.ID is NULL THEN
  :new.ID :="PREPCONTROL"."ER_CTRL_API_SEQ".nextval;
  END IF;
  :new."FECHA_CREACION":=sysdate;
  ELSIF UPDATING THEN
  :new."ULTIMA_FECHA_ACTUALIZACION":=sysdate;
  END IF;
END;
/
commit;



